
const SUPABASE_URL = window.TAGER_SUPABASE_URL || '';
const SUPABASE_KEY = window.TAGER_SUPABASE_ANON_KEY || '';
let db = null;
try{ if(SUPABASE_URL && SUPABASE_KEY && window.supabase){ db = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY); } }catch(e){ console.error(e); }
const $ = (s)=>document.querySelector(s);
const money = (n)=>`${Number(n||0).toLocaleString('ar-EG')} ج.م`;
const uid = ()=> localStorage.getItem('tager_user_id')||'';
const role = ()=> localStorage.getItem('tager_role')||'';
const userName = ()=> localStorage.getItem('tager_name')||'';
const setRoute = (path)=>{ history.pushState(null,'',path); route(); };
const app = ()=>$('#app');
let cart = JSON.parse(localStorage.getItem('tager_cart')||'[]');
function saveCart(){localStorage.setItem('tager_cart',JSON.stringify(cart)); updateCart();}
function updateCart(){const el=$('#cartCount'); if(el) el.textContent=cart.reduce((s,i)=>s+i.qty,0)}
function msg(t,type=''){return `<div class="notice ${type}">${t}</div>`}
function layout(title,body){return `<section class="wrap" style="padding:28px 0"><h1 style="color:var(--green);font-size:36px">${title}</h1>${body}</section>`}
function input(name,label,type='text',req='required'){return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" ${req}></div>`}
function select(name,label,opts=[]){return `<div class="field"><label>${label}</label><select name="${name}">${opts.map(o=>`<option value="${o}">${o}</option>`).join('')}</select></div>`}
const EGYPT = {
'القاهرة':['مدينة نصر','مصر الجديدة','المعادي','التجمع الخامس','الزمالك','شبرا','حلوان','السلام','المرج','عين شمس'],
'الجيزة':['الدقي','المهندسين','الهرم','فيصل','6 أكتوبر','الشيخ زايد','العجوزة','البدرشين','العياط'],
'الإسكندرية':['سيدي جابر','محرم بك','العجمي','المنتزه','سموحة','برج العرب','كرموز','العامرية'],
'القليوبية':['بنها','قليوب','شبرا الخيمة','الخانكة','طوخ','القناطر الخيرية','كفر شكر'],
'الشرقية':['الزقازيق','العاشر من رمضان','بلبيس','منيا القمح','أبو حماد','فاقوس','أبو كبير'],
'الدقهلية':['المنصورة','طلخا','ميت غمر','السنبلاوين','أجا','منية النصر','دكرنس'],
'الغربية':['طنطا','المحلة الكبرى','كفر الزيات','زفتى','السنطة','بسيون'],
'المنوفية':['شبين الكوم','مدينة السادات','منوف','أشمون','قويسنا','تلا','الباجور'],
'البحيرة':['دمنهور','كفر الدوار','رشيد','إدكو','أبو حمص','وادي النطرون','إيتاي البارود'],
'كفر الشيخ':['كفر الشيخ','دسوق','فوه','بيلا','بلطيم','سيدي سالم'],
'دمياط':['دمياط','رأس البر','فارسكور','كفر سعد','الزرقا','دمياط الجديدة'],
'بورسعيد':['حي الشرق','حي العرب','حي المناخ','حي الزهور','بورفؤاد'],
'الإسماعيلية':['الإسماعيلية','فايد','القنطرة شرق','القنطرة غرب','التل الكبير'],
'السويس':['السويس','الأربعين','عتاقة','فيصل','الجناين'],
'شمال سيناء':['العريش','بئر العبد','الشيخ زويد','رفح','الحسنة'],
'جنوب سيناء':['طور سيناء','شرم الشيخ','دهب','نويبع','رأس سدر','سانت كاترين'],
'بني سويف':['بني سويف','الواسطى','ناصر','إهناسيا','ببا','الفشن'],
'الفيوم':['الفيوم','سنورس','طامية','إطسا','أبشواي','يوسف الصديق'],
'المنيا':['المنيا','ملوي','سمالوط','بني مزار','مطاي','أبو قرقاص','دير مواس'],
'أسيوط':['أسيوط','ديروط','منفلوط','القوصية','أبنوب','أبو تيج','صدفا'],
'سوهاج':['سوهاج','أخميم','المنشأة','جرجا','طهطا','طما','البلينا','دار السلام'],
'قنا':['قنا','نجع حمادي','دشنا','قوص','أبو تشت','فرشوط','نقادة'],
'الأقصر':['الأقصر','إسنا','أرمنت','القرنة','الزينية','البياضية'],
'أسوان':['أسوان','دراو','كوم أمبو','نصر النوبة','إدفو','أبو سمبل'],
'البحر الأحمر':['الغردقة','رأس غارب','سفاجا','القصير','مرسى علم','حلايب'],
'الوادي الجديد':['الخارجة','الداخلة','الفرافرة','باريس','بلاط'],
'مطروح':['مرسى مطروح','الحمام','العلمين','الضبعة','سيوة','السلوم']
};
const govOptions = ()=>Object.keys(EGYPT).map(g=>`<option value="${g}">${g}</option>`).join('');
const distOptions = (g)=> (EGYPT[g]||[]).map(d=>`<option value="${d}">${d}</option>`).join('');
function bindGov(form){ const g=form.querySelector('[name=governorate]'), d=form.querySelector('[name=district]'); if(g&&d){ d.innerHTML=distOptions(g.value); g.onchange=()=>{d.innerHTML=distOptions(g.value)}; } }
async function q(table){ if(!db) throw new Error('Supabase غير مربوط. تأكد من Environment Variables في Vercel.'); return db.from(table); }
async function insert(table,row){ const {data,error}=await (await q(table)).insert(row).select().single(); if(error) throw error; return data; }
async function update(table,row,eqCol,eqVal){ const {data,error}=await (await q(table)).update(row).eq(eqCol,eqVal).select(); if(error) throw error; return data; }
async function get(table,select='*'){ const {data,error}=await (await q(table)).select(select); if(error) throw error; return data||[]; }
async function getEq(table,col,val,select='*'){ const {data,error}=await (await q(table)).select(select).eq(col,val); if(error) throw error; return data||[]; }
function home(){ app().innerHTML=`<section class="wrap hero"><div><span class="badge">منصة تجارة السوق المصري</span><h1>قطاعي وجملة<br>وجملة الجملة</h1><p>اختار المورد ومكان التوصيل ونوع السعر، وتابع الطلبات والأرصدة والعمولات من لوحة واحدة.</p><div class="search"><input id="homeSearch" placeholder="ابحث عن منتج أو مورد"><button class="btn2" onclick="setRoute('/market?q='+encodeURIComponent($('#homeSearch').value))">بحث الآن</button></div><button class="btn2" onclick="setRoute('/market')">ابدأ التسوق</button> <button class="btn3" onclick="setRoute('/register/vendor')">انضم كمورد</button></div><div class="stats"><div class="stat"><strong>0</strong>لا توجد بيانات تجريبية</div><div class="stat"><strong>27</strong>محافظة مصرية</div><div class="stat"><strong>100%</strong>تحقق من تغطية التوصيل قبل الطلب</div></div></section><section class="wrap grid"><div class="card"><h3>للعميل</h3><p class="muted">سلة واضحة، تحقق تلقائي من أماكن التوصيل، وتتبع الطلب حتى التسليم.</p></div><div class="card"><h3>للمورد</h3><p class="muted">إدارة المنتجات، الأسعار، المحافظات، مراكز التوصيل، والعمولات المدفوعة والمتبقية.</p></div><div class="card"><h3>للإدارة</h3><p class="muted">اعتماد الموردين والمنتجات، متابعة الطلبات، التوصيلات، والقوائم المالية.</p></div></section>`; }
function setup(){ app().innerHTML=layout('إنشاء أول حساب إدارة', `${!db?msg('Supabase غير مربوط. راجع متغيرات Vercel: NEXT_PUBLIC_SUPABASE_URL و NEXT_PUBLIC_SUPABASE_ANON_KEY','error'):msg('هذه الصفحة تنشئ أول مدير فقط إذا لم يوجد مدير في قاعدة البيانات.','ok')}<form class="card form" id="setupForm">${input('name','اسم المدير')}${input('phone','رقم الهاتف')}${input('email','البريد الإلكتروني','email','')}${input('password','كلمة المرور','password')}<button class="btn">إنشاء حساب الإدارة</button></form><div id="out"></div>`); $('#setupForm').onsubmit=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); try{const admins=await getEq('users','role','admin'); if(admins.length){$('#out').innerHTML=msg('يوجد حساب إدارة بالفعل. استخدم تسجيل الدخول.','error');return;} await insert('users',{role:'admin',status:'approved',name:f.name,phone:f.phone,email:f.email||null,password_hash:f.password,permissions:{all:true}}); $('#out').innerHTML=msg('تم إنشاء المدير. توجه لتسجيل الدخول.','ok');}catch(err){$('#out').innerHTML=msg(err.message,'error')}} }
function login(){ app().innerHTML=layout('تسجيل الدخول', `<form class="card form" id="loginForm">${input('phone','رقم الهاتف')}${input('password','كلمة المرور','password')}<button class="btn">دخول</button></form><div class="grid"><a class="card" href="/register/customer"><h3>تسجيل عميل</h3><p>حساب مشتري جديد.</p></a><a class="card" href="/register/vendor"><h3>تسجيل مورد</h3><p>طلب انضمام مورد.</p></a></div><div id="out"></div>`); $('#loginForm').onsubmit=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); try{const {data,error}=await (await q('users')).select('*').eq('phone',f.phone).eq('password_hash',f.password).maybeSingle(); if(error) throw error; if(!data){$('#out').innerHTML=msg('رقم الهاتف أو كلمة المرور غير صحيحة.','error');return;} if(data.status!=='approved'){ $('#out').innerHTML=msg('الحساب غير معتمد حاليًا.','error');return;} localStorage.setItem('tager_user_id',data.id); localStorage.setItem('tager_role',data.role); localStorage.setItem('tager_name',data.name); $('#loginBtn').textContent=data.name; setRoute(data.role==='admin'?'/admin':data.role==='vendor'?'/vendor':'/customer');}catch(err){$('#out').innerHTML=msg(err.message,'error')}} }
function register(type){ const vendor=type==='vendor'; app().innerHTML=layout(vendor?'تسجيل مورد جديد':'تسجيل عميل جديد', `<form class="card form" id="regForm">${input('name',vendor?'اسم المسؤول':'اسم العميل')}${vendor?input('store_name','اسم المتجر / الشركة'):''}${input('phone','رقم الهاتف')}${input('email','البريد الإلكتروني','email','')}${input('password','كلمة المرور','password')}<div class="row"><div class="field"><label>المحافظة</label><select name="governorate">${govOptions()}</select></div><div class="field"><label>المركز</label><select name="district"></select></div>${input('area','القسم / الحي','text','')}</div>${input('address','العنوان التفصيلي','text','')}<button class="btn">تسجيل</button></form><div id="out"></div>`); bindGov($('#regForm')); $('#regForm').onsubmit=async(e)=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); try{ const u=await insert('users',{role:vendor?'vendor':'customer',status:vendor?'pending':'approved',name:f.name,phone:f.phone,email:f.email||null,password_hash:f.password,governorate:f.governorate,district:f.district,area:f.area,address:f.address}); if(vendor) await insert('vendors',{user_id:u.id,store_name:f.store_name,governorate:f.governorate,district:f.district,area:f.area}); if(!vendor) await insert('customer_addresses',{customer_id:u.id,governorate:f.governorate,district:f.district,area:f.area||'كل المناطق',address:f.address,is_default:true}); $('#out').innerHTML=msg(vendor?'تم تسجيل المورد، وفي انتظار موافقة الإدارة.':'تم تسجيل العميل. يمكنك تسجيل الدخول الآن.','ok'); }catch(err){$('#out').innerHTML=msg(err.message,'error')}} }
async function market(){ app().innerHTML=layout('السوق', msg('جاري تحميل المنتجات...')); try{ const products=await get('products','*, vendors!products_vendor_id_fkey(store_name,commission_percent,min_order)'); const approved=products.filter(p=>p.status==='approved'); let html=`<div class="row card"><div class="field"><label>بحث</label><input id="searchBox" placeholder="اسم المنتج"></div><div class="field"><label>المحافظة</label><select id="govFilter"><option value="">كل المحافظات</option>${govOptions()}</select></div><div class="field"><label>نوع السعر</label><select id="priceType"><option value="retail_price">قطاعي</option><option value="wholesale_price">جملة</option><option value="super_wholesale_price">جملة الجملة</option></select></div></div><div id="products" class="grid"></div>`; app().innerHTML=layout('السوق', html); const render=()=>{const s=$('#searchBox').value.trim(), pt=$('#priceType').value; let arr=approved.filter(p=>!s||p.name_ar.includes(s)||String(p.category||'').includes(s)); $('#products').innerHTML=arr.length?arr.map(p=>`<div class="card product"><img src="${p.image_url||'/tager-logo.png'}"><div class="pbody"><h3>${p.name_ar}</h3><p class="muted">${p.category||''} — ${p.vendors?.store_name||'مورد'}</p><div class="price">${money(p[pt])}</div><p>المخزون: ${p.stock}</p><button class="btn" onclick="addToCart('${p.id}','${p.vendor_id}','${String(p.name_ar).replaceAll("'","`")}',${Number(p[pt]||0)},1)">إضافة للسلة</button></div></div>`).join(''):'<div class="empty">لا توجد منتجات معتمدة حتى الآن.</div>';}; ['searchBox','priceType'].forEach(id=>setTimeout(()=>{$('#'+id).oninput=render; $('#'+id).onchange=render},0)); render(); }catch(err){app().innerHTML=layout('السوق',msg(err.message,'error'))} }
function addToCart(product_id,vendor_id,name,price,qty){ const ex=cart.find(i=>i.product_id===product_id); if(ex) ex.qty+=qty; else cart.push({product_id,vendor_id,name,price,qty}); saveCart(); alert('تمت الإضافة للسلة'); }
async function cartPage(){ if(!uid()) return setRoute('/login'); const udata=(await getEq('users','id',uid()))[0]; app().innerHTML=layout('السلة', `<div class="card"><table class="table"><tr><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th><th></th></tr>${cart.map((i,k)=>`<tr><td>${i.name}</td><td><input style="width:80px" value="${i.qty}" type="number" min="1" onchange="cart[${k}].qty=Number(this.value);saveCart();cartPage()"></td><td>${money(i.price)}</td><td>${money(i.price*i.qty)}</td><td><button class="danger" onclick="cart.splice(${k},1);saveCart();cartPage()">حذف</button></td></tr>`).join('')}</table><h2>الإجمالي: ${money(cart.reduce((s,i)=>s+i.price*i.qty,0))}</h2></div><form class="card form" id="checkoutForm"><h3>عنوان التوصيل</h3><div class="row"><div class="field"><label>المحافظة</label><select name="governorate">${govOptions()}</select></div><div class="field"><label>المركز</label><select name="district"></select></div>${input('area','القسم / الحي','text','')}</div>${input('address','العنوان التفصيلي','text','')}<div class="field"><label>طريقة الدفع</label><select name="payment_method"><option>نقدي عند الاستلام</option><option>تحويل بنكي</option><option>محفظة إلكترونية</option></select></div><div class="field"><label>نوع السلة</label><select name="cart_type"><option value="separate">سلة عادية</option><option value="premium">سلة مميزة</option></select></div><button class="btn">تأكيد الطلب</button></form><div id="out"></div>`); const form=$('#checkoutForm'); form.governorate.value=udata?.governorate||Object.keys(EGYPT)[0]; bindGov(form); form.district.value=udata?.district||form.district.value; form.area.value=udata?.area||''; form.address.value=udata?.address||''; form.onsubmit=async(e)=>{e.preventDefault(); if(!cart.length){$('#out').innerHTML=msg('السلة فارغة.','error');return;} const f=Object.fromEntries(new FormData(e.target)); try{ const vendors=[...new Set(cart.map(i=>i.vendor_id))]; for(const v of vendors){ const zones=await getEq('vendor_delivery_zones','vendor_id',v); const covered=zones.some(z=>z.is_active && z.governorate===f.governorate && z.district===f.district && (z.area===f.area || z.area==='كل المناطق')); if(!covered){$('#out').innerHTML=msg('لا يمكن إتمام الطلب: أحد الموردين لا يغطي عنوان التوصيل المختار.','error');return;} }
 const total=cart.reduce((s,i)=>s+i.price*i.qty,0); const order=await insert('orders',{customer_id:uid(),cart_type:f.cart_type,governorate:f.governorate,district:f.district,area:f.area,address:f.address,payment_method:f.payment_method,total:total,status:'new'});
 for(const i of cart){ const vend=(await getEq('vendors','user_id',i.vendor_id))[0]||{}; const commPct=Number(vend.commission_percent||10); const subtotal=i.price*i.qty; const comm=subtotal*commPct/100; await insert('order_items',{order_id:order.id,product_id:i.product_id,vendor_id:i.vendor_id,qty:i.qty,unit_price:i.price,subtotal,commission_percent:commPct,commission_amount:comm,vendor_net:subtotal-comm}); await insert('shipments',{order_id:order.id,vendor_id:i.vendor_id,status:'pending',governorate:f.governorate,district:f.district,area:f.area}); }
 cart=[]; saveCart(); $('#out').innerHTML=msg('تم إنشاء الطلب بنجاح.','ok'); }catch(err){$('#out').innerHTML=msg(err.message,'error')}} }
async function vendorsPage(){ app().innerHTML=layout('الموردون', msg('جاري التحميل...')); try{ const v=await get('vendors','*, users!vendors_user_id_fkey(name,status,phone)'); const list=v.filter(x=>x.users?.status==='approved'); app().innerHTML=layout('الموردون', list.length?`<div class="grid">${list.map(x=>`<div class="card"><h3>${x.store_name}</h3><p class="muted">${x.description||''}</p><p>الحد الأدنى: ${money(x.min_order)}</p><p>العمولة: ${x.commission_percent}%</p></div>`).join('')}</div>`:'<div class="empty">لا يوجد موردون معتمدون حتى الآن.</div>'); }catch(err){app().innerHTML=layout('الموردون',msg(err.message,'error'))} }
async function customer(){ if(role()!=='customer') return setRoute('/login'); app().innerHTML=layout('حساب العميل', msg('جاري التحميل...')); try{ const orders=await getEq('orders','customer_id',uid()); app().innerHTML=layout('حساب العميل', `<div class="card"><h3>مرحبًا ${userName()}</h3><button class="btn3" onclick="logout()">خروج</button></div><h2>طلباتي</h2>${orders.length?tableOrders(orders):'<div class="empty">لا توجد طلبات.</div>'}`); }catch(err){app().innerHTML=layout('حساب العميل',msg(err.message,'error'))} }
function tableOrders(orders){return `<table class="table"><tr><th>رقم</th><th>الحالة</th><th>العنوان</th><th>الإجمالي</th><th>تاريخ</th></tr>${orders.map(o=>`<tr><td>${o.id.slice(0,8)}</td><td><span class="badge">${o.status}</span></td><td>${o.governorate||''} - ${o.district||''}</td><td>${money(o.total)}</td><td>${new Date(o.created_at).toLocaleDateString('ar-EG')}</td></tr>`).join('')}</table>`}
async function vendor(){ if(role()!=='vendor') return setRoute('/login'); app().innerHTML=layout('لوحة المورد', msg('جاري التحميل...')); try{ const me=uid(); const vendor=(await getEq('vendors','user_id',me))[0]||{}; const zones=await getEq('vendor_delivery_zones','vendor_id',me); const products=await getEq('products','vendor_id',me); const items=await getEq('order_items','vendor_id',me); const pays=await getEq('commission_payments','vendor_id',me); const sales=items.reduce((s,i)=>s+Number(i.subtotal||0),0), comm=items.reduce((s,i)=>s+Number(i.commission_amount||0),0), paid=pays.filter(p=>p.status==='approved').reduce((s,p)=>s+Number(p.amount||0),0), pending=pays.filter(p=>p.status==='pending').reduce((s,p)=>s+Number(p.amount||0),0); app().innerHTML=layout('لوحة المورد', `<div class="tabs"><button class="tab active" onclick="showVendorTab('summary')">الملخص</button><button class="tab" onclick="showVendorTab('zones')">أماكن التوصيل</button><button class="tab" onclick="showVendorTab('products')">المنتجات</button><button class="tab" onclick="showVendorTab('finance')">الحساب المالي</button><button class="tab" onclick="logout()">خروج</button></div><div id="v-summary" class="vtab grid"><div class="card"><h3>المبيعات</h3><div class="price">${money(sales)}</div></div><div class="card"><h3>عمولة المنصة</h3><div class="price">${money(comm)}</div></div><div class="card"><h3>المدفوع</h3><div class="price">${money(paid)}</div></div><div class="card"><h3>المتبقي</h3><div class="price">${money(comm-paid)}</div></div></div><div id="v-zones" class="vtab hidden">${zoneForm()}${zones.length?zonesTable(zones):'<div class="empty">لم تضف أماكن توصيل بعد.</div>'}</div><div id="v-products" class="vtab hidden">${productForm()}${productsTable(products)}</div><div id="v-finance" class="vtab hidden"><div class="grid"><div class="card"><h3>المعلق</h3><div class="price">${money(pending)}</div></div><div class="card"><h3>صافي المورد</h3><div class="price">${money(sales-comm)}</div></div></div>${paymentForm()}${paymentsTable(pays)}</div><div id="out"></div>`); bindGov($('#zoneForm')); bindGov($('#productForm')); $('#zoneForm').onsubmit=saveZone; $('#productForm').onsubmit=saveProduct; $('#payForm').onsubmit=savePayment; }catch(err){app().innerHTML=layout('لوحة المورد',msg(err.message,'error'))} }
function showVendorTab(t){document.querySelectorAll('.vtab').forEach(e=>e.classList.add('hidden')); $('#v-'+t).classList.remove('hidden')}
function zoneForm(){return `<form class="card form" id="zoneForm"><h3>إضافة مكان توصيل</h3><div class="row"><div class="field"><label>المحافظة</label><select name="governorate">${govOptions()}</select></div><div class="field"><label>المركز</label><select name="district"></select></div>${input('area','القسم / الحي','text','value="كل المناطق"')}</div><div class="row">${input('delivery_fee','رسوم التوصيل','number')}${input('eta_days','مدة التوصيل بالأيام','number')}</div><button class="btn">حفظ مكان التوصيل</button></form>`}
function zonesTable(z){return `<table class="table"><tr><th>محافظة</th><th>مركز</th><th>قسم</th><th>رسوم</th><th>مدة</th></tr>${z.map(x=>`<tr><td>${x.governorate}</td><td>${x.district}</td><td>${x.area}</td><td>${money(x.delivery_fee)}</td><td>${x.eta_days} يوم</td></tr>`).join('')}</table>`}
async function saveZone(e){e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); try{await insert('vendor_delivery_zones',{vendor_id:uid(),governorate:f.governorate,district:f.district,area:f.area||'كل المناطق',delivery_fee:Number(f.delivery_fee||0),eta_days:Number(f.eta_days||2)}); vendor();}catch(err){$('#out').innerHTML=msg(err.message,'error')}}
function productForm(){return `<form class="card form" id="productForm"><h3>إضافة منتج</h3>${input('name_ar','اسم المنتج')}${input('category','الفئة','text','')}<div class="row">${input('retail_price','سعر القطاعي','number')}${input('wholesale_price','سعر الجملة','number')}${input('super_wholesale_price','سعر جملة الجملة','number')}</div><div class="row">${input('stock','المخزون','number')}${input('wholesale_min','حد الجملة','number')}${input('super_wholesale_min','حد جملة الجملة','number')}</div>${input('image_url','رابط الصورة / أو اتركه فارغًا','url','')}<button class="btn">إضافة المنتج للمراجعة</button></form>`}
function productsTable(p){return p.length?`<table class="table"><tr><th>المنتج</th><th>الحالة</th><th>قطاعي</th><th>جملة</th><th>مخزون</th></tr>${p.map(x=>`<tr><td>${x.name_ar}</td><td><span class="badge ${x.status}">${x.status}</span></td><td>${money(x.retail_price)}</td><td>${money(x.wholesale_price)}</td><td>${x.stock}</td></tr>`).join('')}</table>`:'<div class="empty">لا توجد منتجات.</div>'}
async function saveProduct(e){e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); try{await insert('products',{vendor_id:uid(),status:'pending',name_ar:f.name_ar,category:f.category,retail_price:Number(f.retail_price||0),wholesale_price:Number(f.wholesale_price||0),super_wholesale_price:Number(f.super_wholesale_price||0),stock:Number(f.stock||0),wholesale_min:Number(f.wholesale_min||12),super_wholesale_min:Number(f.super_wholesale_min||48),image_url:f.image_url||'/tager-logo.png'}); vendor();}catch(err){$('#out').innerHTML=msg(err.message,'error')}}
function paymentForm(){return `<form class="card form" id="payForm"><h3>تسجيل دفعة عمولة</h3><div class="row">${input('amount','المبلغ','number')}${select('method','طريقة الدفع',['تحويل بنكي','محفظة إلكترونية','Instapay','نقدي'])}${input('reference','رقم العملية','text','')}</div><div class="field"><label>ملاحظات</label><textarea name="notes"></textarea></div><button class="btn">إرسال للمراجعة</button></form>`}
function paymentsTable(p){return p.length?`<table class="table"><tr><th>مبلغ</th><th>طريقة</th><th>مرجع</th><th>حالة</th></tr>${p.map(x=>`<tr><td>${money(x.amount)}</td><td>${x.method}</td><td>${x.reference||''}</td><td><span class="badge ${x.status}">${x.status}</span></td></tr>`).join('')}</table>`:'<div class="empty">لا توجد دفعات.</div>'}
async function savePayment(e){e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)); try{await insert('commission_payments',{vendor_id:uid(),amount:Number(f.amount||0),method:f.method,reference:f.reference,notes:f.notes,status:'pending'}); vendor();}catch(err){$('#out').innerHTML=msg(err.message,'error')}}
async function admin(){ if(role()!=='admin') return setRoute('/login'); app().innerHTML=layout('لوحة الإدارة', msg('جاري التحميل...')); try{ const users=await get('users'); const vendors=await get('vendors'); const products=await get('products'); const orders=await get('orders'); const pays=await get('commission_payments'); const items=await get('order_items'); const sales=orders.reduce((s,o)=>s+Number(o.total||0),0), comm=items.reduce((s,i)=>s+Number(i.commission_amount||0),0), paid=pays.filter(p=>p.status==='approved').reduce((s,p)=>s+Number(p.amount||0),0); app().innerHTML=layout('لوحة الإدارة', `<div class="tabs"><button class="tab active" onclick="showAdminTab('summary')">الملخص</button><button class="tab" onclick="showAdminTab('vendors')">الموردون</button><button class="tab" onclick="showAdminTab('products')">المنتجات</button><button class="tab" onclick="showAdminTab('finance')">المالية</button><button class="tab" onclick="showAdminTab('orders')">الطلبات</button><button class="tab" onclick="logout()">خروج</button></div><div id="a-summary" class="atab grid"><div class="card"><h3>المستخدمون</h3><div class="price">${users.length}</div></div><div class="card"><h3>إجمالي المبيعات</h3><div class="price">${money(sales)}</div></div><div class="card"><h3>عمولات مستحقة</h3><div class="price">${money(comm)}</div></div><div class="card"><h3>عمولات مدفوعة</h3><div class="price">${money(paid)}</div></div></div><div id="a-vendors" class="atab hidden">${adminVendors(users,vendors)}</div><div id="a-products" class="atab hidden">${adminProducts(products)}</div><div id="a-finance" class="atab hidden">${adminPays(pays)}</div><div id="a-orders" class="atab hidden">${orders.length?tableOrders(orders):'<div class="empty">لا توجد طلبات.</div>'}</div><div id="out"></div>`); }catch(err){app().innerHTML=layout('لوحة الإدارة',msg(err.message,'error'))} }
function showAdminTab(t){document.querySelectorAll('.atab').forEach(e=>e.classList.add('hidden')); $('#a-'+t).classList.remove('hidden')}
function adminVendors(users,vendors){const vusers=users.filter(u=>u.role==='vendor'); return vusers.length?`<table class="table"><tr><th>المورد</th><th>الهاتف</th><th>الحالة</th><th>إجراء</th></tr>${vusers.map(u=>`<tr><td>${u.name}</td><td>${u.phone}</td><td><span class="badge ${u.status}">${u.status}</span></td><td><button class="ok" onclick="approveUser('${u.id}')">اعتماد</button> <button class="danger" onclick="rejectUser('${u.id}')">رفض</button></td></tr>`).join('')}</table>`:'<div class="empty">لا يوجد موردون.</div>'}
function adminProducts(products){return products.length?`<table class="table"><tr><th>المنتج</th><th>الحالة</th><th>سعر</th><th>إجراء</th></tr>${products.map(p=>`<tr><td>${p.name_ar}</td><td><span class="badge ${p.status}">${p.status}</span></td><td>${money(p.retail_price)}</td><td><button class="ok" onclick="approveProduct('${p.id}')">اعتماد</button> <button class="danger" onclick="rejectProduct('${p.id}')">رفض</button></td></tr>`).join('')}</table>`:'<div class="empty">لا توجد منتجات.</div>'}
function adminPays(p){return p.length?`<table class="table"><tr><th>المورد</th><th>المبلغ</th><th>طريقة</th><th>مرجع</th><th>حالة</th><th>إجراء</th></tr>${p.map(x=>`<tr><td>${x.vendor_id.slice(0,8)}</td><td>${money(x.amount)}</td><td>${x.method}</td><td>${x.reference||''}</td><td><span class="badge ${x.status}">${x.status}</span></td><td><button class="ok" onclick="approvePay('${x.id}')">اعتماد</button> <button class="danger" onclick="rejectPay('${x.id}')">رفض</button></td></tr>`).join('')}</table>`:'<div class="empty">لا توجد دفعات.</div>'}
async function approveUser(id){await update('users',{status:'approved'},'id',id); admin()} async function rejectUser(id){await update('users',{status:'rejected'},'id',id); admin()} async function approveProduct(id){await update('products',{status:'approved'},'id',id); admin()} async function rejectProduct(id){await update('products',{status:'rejected'},'id',id); admin()} async function approvePay(id){await update('commission_payments',{status:'approved'},'id',id); admin()} async function rejectPay(id){await update('commission_payments',{status:'rejected'},'id',id); admin()}
function how(){app().innerHTML=layout('كيف تعمل المنصة؟',`<div class="grid"><div class="card"><h3>1. المورد</h3><p>يسجل بياناته ويحدد أماكن التوصيل والأسعار والمنتجات.</p></div><div class="card"><h3>2. الإدارة</h3><p>تعتمد المورد والمنتجات وتتابع العمولات والدفعات.</p></div><div class="card"><h3>3. العميل</h3><p>يطلب فقط من مورد يغطي مكانه، وبذلك لا يحدث خطأ في التوصيل.</p></div></div>`)}
function support(){app().innerHTML=layout('الدعم',`<div class="card"><h3>تواصل معنا</h3><p>الدعم التجريبي: 01000000000</p><p>يمكن ربط واتساب و SMS لاحقًا بمزود فعلي.</p></div>`)}
function policies(){app().innerHTML=layout('السياسات',`<div class="card"><h3>سياسة الاستخدام</h3><p>الطلبات مرتبطة بتغطية المورد لمكان العميل. يتم اعتماد الموردين والمنتجات والدفعات من لوحة الإدارة.</p></div>`)}
function logout(){localStorage.removeItem('tager_user_id');localStorage.removeItem('tager_role');localStorage.removeItem('tager_name');setRoute('/login')}
function route(){ updateCart(); const p=location.pathname; if(uid()) $('#loginBtn').textContent=userName()||'حسابي'; if(p==='/setup') return setup(); if(p==='/login') return login(); if(p==='/register/customer') return register('customer'); if(p==='/register/vendor') return register('vendor'); if(p==='/market') return market(); if(p==='/vendors') return vendorsPage(); if(p==='/cart') return cartPage(); if(p==='/customer') return customer(); if(p==='/vendor') return vendor(); if(p==='/admin') return admin(); if(p==='/how') return how(); if(p==='/support') return support(); if(p==='/policies') return policies(); return home(); }
window.onpopstate=route; document.addEventListener('click',e=>{const a=e.target.closest('a'); if(a&&a.getAttribute('href')?.startsWith('/')){e.preventDefault(); setRoute(a.getAttribute('href'))}}); route();
