<?php
/**
 * Plugin Name: Tager V40 Complete Workspaces
 * Description: Complete connected customer, vendor and administration workspaces with working product entry, profile saving and approval workflow.
 * Version: 40.0.0
 */
if (!defined('ABSPATH')) exit;

final class Tager_V40_Complete_Workspaces {
    const NONCE = 'tager_v40_action';
    public static function boot(){
        add_action('init',[__CLASS__,'register'],130);
        add_action('admin_menu',[__CLASS__,'menu'],45);
        add_action('admin_post_tager_v40_product_save',[__CLASS__,'save_product']);
        add_action('admin_post_tager_v40_profile_save',[__CLASS__,'save_profile']);
        add_action('admin_post_tager_v40_vendor_decision',[__CLASS__,'vendor_decision']);
        add_action('admin_post_tager_v40_product_decision',[__CLASS__,'product_decision']);
        add_action('admin_post_tager_v40_repair',[__CLASS__,'repair_action']);
        add_shortcode('tager_v40_customer_workspace',[__CLASS__,'customer_workspace']);
        add_shortcode('tager_v40_vendor_workspace',[__CLASS__,'vendor_workspace']);
        add_shortcode('tager_v40_admin_workspace',[__CLASS__,'admin_workspace']);
        add_action('wp_enqueue_scripts',[__CLASS__,'assets']);
    }
    private static function url($slug){$p=get_page_by_path($slug);return $p?get_permalink($p):home_url('/'.$slug.'/');}
    private static function roles($u=null){$u=$u?:wp_get_current_user();return (array)$u->roles;}
    private static function vendor($u=null){return (bool)array_intersect(self::roles($u),['tager_vendor','tager_vendor_pending','vendor','wcfm_vendor','seller']);}
    private static function admin_team($u=null){$u=$u?:wp_get_current_user();return user_can($u,'manage_options') || (bool)array_intersect(self::roles($u),['tager_platform_manager','tager_operations_manager','tager_vendor_manager','tager_catalog_manager','tager_order_manager','tager_finance_manager','tager_support_agent','tager_marketing_manager']);}
    private static function pages(){return [
        'my-account'=>['حساب العميل','[tager_v40_customer_workspace]'],
        'vendor-dashboard'=>['لوحة المورد','[tager_v40_vendor_workspace]'],
        'admin-portal'=>['بوابة الإدارة','[tager_v40_admin_workspace]'],
    ];}
    public static function register(){
        foreach(self::pages() as $slug=>$d){$p=get_page_by_path($slug);if(!$p){wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$d[0],'post_name'=>$slug,'post_content'=>$d[1]]);}elseif(strpos((string)$p->post_content,'tager_v40_')===false){wp_update_post(['ID'=>$p->ID,'post_content'=>$d[1]]);}}
    }
    private static function tabs($type,$active){
        $map=$type==='vendor' ? ['overview'=>'الرئيسية','products'=>'المنتجات','add-product'=>'إضافة منتج','orders'=>'الطلبات','earnings'=>'الأرباح','market'=>'السوق','settings'=>'إعدادات المتجر'] : ['overview'=>'الرئيسية','orders'=>'طلباتي','addresses'=>'العناوين','wishlist'=>'المفضلة','profile'=>'بياناتي','support'=>'الدعم'];
        $base=$type==='vendor'?self::url('vendor-dashboard'):self::url('my-account');$out='<nav class="t40-tabs">';foreach($map as $k=>$v)$out.='<a class="'.($active===$k?'active':'').'" href="'.esc_url(add_query_arg('tab',$k,$base)).'">'.esc_html($v).'</a>';return $out.'</nav>';
    }
    public static function customer_workspace(){
        if(!is_user_logged_in())return '<div class="t40-card"><h2>سجّل الدخول أولًا</h2><a class="t40-btn" href="'.esc_url(self::url('login')).'">تسجيل الدخول</a></div>';
        if(self::vendor()||self::admin_team())return '<div class="t40-alert">هذه المساحة مخصصة للعملاء.</div>';
        $u=wp_get_current_user();$tab=sanitize_key($_GET['tab']??'overview');ob_start();
        echo '<section class="t40-shell"><aside><div class="t40-user"><div class="t40-avatar">'.esc_html(mb_substr($u->display_name?:'ع',0,1)).'</div><b>'.esc_html($u->display_name).'</b><small>'.esc_html(get_user_meta($u->ID,'phone',true)).'</small></div>'.self::tabs('customer',$tab).'</aside><main>';
        if($tab==='profile'||$tab==='addresses'){self::profile_form($u,$tab);}elseif($tab==='orders'){self::customer_orders($u);}elseif($tab==='wishlist'){echo '<div class="t40-card"><h2>المفضلة</h2><p>المنتجات التي تحفظها ستظهر هنا.</p><a class="t40-btn" href="'.esc_url(home_url('/shop/')).'">استكشف المنتجات</a></div>';}elseif($tab==='support'){echo '<div class="t40-card"><h2>الدعم</h2><p>تواصل مع فريق الدعم من خلال صفحة مركز المساعدة.</p><a class="t40-btn" href="'.esc_url(self::url('help-center')).'">فتح مركز المساعدة</a></div>';}else{self::customer_overview($u);}echo '</main></section>';return ob_get_clean();
    }
    private static function customer_overview($u){$orders=get_posts(['post_type'=>'tager_order','author'=>$u->ID,'post_status'=>'any','posts_per_page'=>-1]);$total=0;foreach($orders as $o)$total+=(float)get_post_meta($o->ID,'grand_total',true);echo '<div class="t40-head"><div><span>حساب العميل</span><h1>مرحبًا '.esc_html($u->display_name).'</h1><p>تابع طلباتك وعناوينك وبياناتك من مكان واحد.</p></div><a class="t40-btn" href="'.esc_url(home_url('/shop/')).'">ابدأ التسوق</a></div><div class="t40-stats"><article><b>'.count($orders).'</b><span>إجمالي الطلبات</span></article><article><b>'.number_format($total,2).'</b><span>إجمالي المشتريات</span></article><article><b>'.esc_html(get_user_meta($u->ID,'governorate',true)?:'غير محدد').'</b><span>المحافظة</span></article></div><div class="t40-grid"><a class="t40-card" href="'.esc_url(add_query_arg('tab','orders',self::url('my-account'))).'"><h3>طلباتي</h3><p>تابع الطلبات والفواتير.</p></a><a class="t40-card" href="'.esc_url(add_query_arg('tab','addresses',self::url('my-account'))).'"><h3>عناويني</h3><p>حدّث بيانات التوصيل.</p></a><a class="t40-card" href="'.esc_url(self::url('cart')).'"><h3>السلة</h3><p>راجع المنتجات قبل الطلب.</p></a></div>';}
    private static function profile_form($u,$tab){$phone=get_user_meta($u->ID,'phone',true);$gov=get_user_meta($u->ID,'governorate',true);$city=get_user_meta($u->ID,'city',true);$address=get_user_meta($u->ID,'address',true);echo '<div class="t40-card"><h1>'.($tab==='addresses'?'العنوان والتوصيل':'البيانات الشخصية').'</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" class="t40-form"><input type="hidden" name="action" value="tager_v40_profile_save">'.wp_nonce_field(self::NONCE,'_wpnonce',true,false).'<label>الاسم<input name="display_name" required value="'.esc_attr($u->display_name).'"></label><label>رقم الهاتف<input name="phone" required value="'.esc_attr($phone).'"></label><label>البريد الإلكتروني (اختياري)<input type="email" name="email" value="'.esc_attr(str_contains($u->user_email,'@tager.local')?'':$u->user_email).'"></label><label>المحافظة<input name="governorate" value="'.esc_attr($gov).'"></label><label>المدينة / المنطقة<input name="city" value="'.esc_attr($city).'"></label><label class="full">العنوان<textarea name="address">'.esc_textarea($address).'</textarea></label><button class="t40-btn">حفظ البيانات</button></form></div>';}
    private static function customer_orders($u){$orders=get_posts(['post_type'=>'tager_order','author'=>$u->ID,'post_status'=>'any','posts_per_page'=>30]);echo '<div class="t40-card"><h1>طلباتي</h1><div class="t40-table"><table><thead><tr><th>الطلب</th><th>التاريخ</th><th>الحالة</th><th>الإجمالي</th></tr></thead><tbody>';if(!$orders)echo '<tr><td colspan="4">لا توجد طلبات حتى الآن.</td></tr>';foreach($orders as $o)echo '<tr><td>#'.(int)$o->ID.'</td><td>'.esc_html(get_the_date('Y-m-d',$o)).'</td><td>'.esc_html(get_post_meta($o->ID,'order_status',true)?:$o->post_status).'</td><td>'.number_format((float)get_post_meta($o->ID,'grand_total',true),2).' ج.م</td></tr>';echo '</tbody></table></div></div>';}
    public static function vendor_workspace(){
        if(!is_user_logged_in())return '<div class="t40-card"><a class="t40-btn" href="'.esc_url(self::url('login')).'">تسجيل الدخول</a></div>';
        if(!self::vendor())return '<div class="t40-alert">هذه المساحة مخصصة للموردين.</div>';
        $u=wp_get_current_user();$status=get_user_meta($u->ID,'vendor_status',true)?:'pending';$tab=sanitize_key($_GET['tab']??'overview');ob_start();echo '<section class="t40-shell"><aside><div class="t40-user"><div class="t40-avatar">'.esc_html(mb_substr(get_user_meta($u->ID,'store_name',true)?:$u->display_name,0,1)).'</div><b>'.esc_html(get_user_meta($u->ID,'store_name',true)?:$u->display_name).'</b><small>حالة الحساب: '.esc_html($status).'</small></div>'.self::tabs('vendor',$tab).'</aside><main>';
        if($status!=='approved' && $tab!=='settings'){echo '<div class="t40-alert"><h3>الحساب تحت مراجعة الإدارة</h3><p>يمكنك استكمال بيانات المتجر، وسيتم فتح البيع بعد الموافقة.</p></div>';}
        switch($tab){case 'products': self::vendor_products($u);break;case 'add-product': self::product_form($u);break;case 'orders': self::vendor_orders($u);break;case 'earnings': self::vendor_earnings($u);break;case 'market': echo do_shortcode('[tager_v39_vendor_market]');break;case 'settings': self::vendor_settings($u);break;default:self::vendor_overview($u,$status);}echo '</main></section>';return ob_get_clean();
    }
    private static function vendor_overview($u,$status){$ids=get_posts(['post_type'=>'tager_product','author'=>$u->ID,'post_status'=>['publish','pending','draft'],'posts_per_page'=>-1,'fields'=>'ids']);$live=0;$pending=0;foreach($ids as $id){$s=get_post_status($id);$s==='publish'?$live++:$pending++;}$sales=(float)get_user_meta($u->ID,'tager_total_sales',true);$commission=(float)get_user_meta($u->ID,'tager_platform_commission_total',true);echo '<div class="t40-head"><div><span>لوحة المورد</span><h1>إدارة متجرك ومبيعاتك</h1><p>أضف المنتجات والأسعار والمخزون وتابع حالة المراجعة والطلبات.</p></div><a class="t40-btn" href="'.esc_url(add_query_arg('tab','add-product',self::url('vendor-dashboard'))).'">إضافة منتج</a></div><div class="t40-stats"><article><b>'.count($ids).'</b><span>كل المنتجات</span></article><article><b>'.$live.'</b><span>منتجات منشورة</span></article><article><b>'.$pending.'</b><span>تحت المراجعة</span></article><article><b>'.number_format($sales,2).'</b><span>إجمالي المبيعات</span></article><article><b>'.number_format(max(0,$sales-$commission),2).'</b><span>صافي المستحق</span></article></div>';}
    private static function vendor_products($u){$products=get_posts(['post_type'=>'tager_product','author'=>$u->ID,'post_status'=>['publish','pending','draft'],'posts_per_page'=>50]);echo '<div class="t40-card"><div class="t40-row"><h1>منتجاتي</h1><a class="t40-btn" href="'.esc_url(add_query_arg('tab','add-product',self::url('vendor-dashboard'))).'">إضافة منتج</a></div><div class="t40-table"><table><thead><tr><th>المنتج</th><th>قطاعي</th><th>جملة</th><th>جملة الجملة</th><th>المخزون</th><th>الحالة</th><th></th></tr></thead><tbody>';if(!$products)echo '<tr><td colspan="7">لم تضف منتجات بعد.</td></tr>';foreach($products as $p)echo '<tr><td>'.esc_html($p->post_title).'</td><td>'.esc_html(get_post_meta($p->ID,'retail_price',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'wholesale_price',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'bulk_price',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'stock',true)).'</td><td>'.esc_html($p->post_status).'</td><td><a href="'.esc_url(add_query_arg(['tab'=>'add-product','product_id'=>$p->ID],self::url('vendor-dashboard'))).'">تعديل</a></td></tr>';echo '</tbody></table></div></div>';}
    private static function product_form($u){$id=absint($_GET['product_id']??0);$p=$id?get_post($id):null;if($p && (int)$p->post_author!==$u->ID)$p=null;$get=function($k,$d='')use($p){return $p?get_post_meta($p->ID,$k,true):$d;};echo '<div class="t40-card"><h1>'.($p?'تعديل المنتج':'إضافة منتج جديد').'</h1><p>بعد الحفظ سيتم إرسال المنتج إلى الإدارة للمراجعة.</p><form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'" class="t40-form"><input type="hidden" name="action" value="tager_v40_product_save"><input type="hidden" name="product_id" value="'.($p?(int)$p->ID:0).'">'.wp_nonce_field(self::NONCE,'_wpnonce',true,false).'<label class="full">اسم المنتج<input name="title" required value="'.esc_attr($p?$p->post_title:'').'"></label><label>SKU<input name="sku" value="'.esc_attr($get('sku')).'"></label><label>القسم<input name="category" value="'.esc_attr($get('category')).'"></label><label>سعر القطاعي<input type="number" step="0.01" min="0" name="retail_price" required value="'.esc_attr($get('retail_price')).'"></label><label>سعر الجملة<input type="number" step="0.01" min="0" name="wholesale_price" required value="'.esc_attr($get('wholesale_price')).'"></label><label>سعر جملة الجملة<input type="number" step="0.01" min="0" name="bulk_price" required value="'.esc_attr($get('bulk_price')).'"></label><label>حد الجملة<input type="number" min="1" name="wholesale_min" required value="'.esc_attr($get('wholesale_min',10)).'"></label><label>حد جملة الجملة<input type="number" min="1" name="bulk_min" required value="'.esc_attr($get('bulk_min',50)).'"></label><label>المخزون<input type="number" min="0" name="stock" required value="'.esc_attr($get('stock',0)).'"></label><label>الحد الأقصى للطلب<input type="number" min="1" name="max_order" value="'.esc_attr($get('max_order')).'"></label><label>مدة التجهيز بالأيام<input type="number" min="0" name="lead_days" value="'.esc_attr($get('lead_days',2)).'"></label><label>صورة المنتج<input type="file" name="product_image" accept="image/jpeg,image/png,image/webp"></label><label class="full">الوصف<textarea name="description">'.esc_textarea($p?$p->post_content:'').'</textarea></label><button class="t40-btn">حفظ وإرسال للمراجعة</button></form></div>';}
    private static function vendor_orders($u){$orders=get_posts(['post_type'=>'tager_order','post_status'=>'any','posts_per_page'=>50,'meta_query'=>[['key'=>'vendor_ids','value'=>'"'.$u->ID.'"','compare'=>'LIKE']]]);echo '<div class="t40-card"><h1>طلبات المتجر</h1><div class="t40-table"><table><thead><tr><th>الطلب</th><th>الحالة</th><th>الإجمالي</th><th>التاريخ</th></tr></thead><tbody>';if(!$orders)echo '<tr><td colspan="4">لا توجد طلبات مرتبطة بمتجرك.</td></tr>';foreach($orders as $o)echo '<tr><td>#'.$o->ID.'</td><td>'.esc_html(get_post_meta($o->ID,'order_status',true)?:$o->post_status).'</td><td>'.number_format((float)get_post_meta($o->ID,'grand_total',true),2).'</td><td>'.esc_html(get_the_date('Y-m-d',$o)).'</td></tr>';echo '</tbody></table></div></div>';}
    private static function vendor_earnings($u){$sales=(float)get_user_meta($u->ID,'tager_total_sales',true);$commission=(float)get_user_meta($u->ID,'tager_platform_commission_total',true);$rate=get_user_meta($u->ID,'tager_commission_percent',true);echo '<div class="t40-stats"><article><b>'.number_format($sales,2).'</b><span>إجمالي المبيعات</span></article><article><b>'.number_format($commission,2).'</b><span>عمولة المنصة</span></article><article><b>'.number_format(max(0,$sales-$commission),2).'</b><span>صافي المستحق</span></article><article><b>'.esc_html($rate!==''?$rate:'الافتراضي').'%</b><span>نسبة العمولة</span></article></div>';}
    private static function vendor_settings($u){echo '<div class="t40-card"><h1>إعدادات المتجر</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" class="t40-form"><input type="hidden" name="action" value="tager_v40_profile_save">'.wp_nonce_field(self::NONCE,'_wpnonce',true,false).'<label>اسم المتجر<input name="store_name" required value="'.esc_attr(get_user_meta($u->ID,'store_name',true)).'"></label><label>رقم الهاتف<input name="phone" required value="'.esc_attr(get_user_meta($u->ID,'phone',true)).'"></label><label>البريد (اختياري)<input type="email" name="email" value="'.esc_attr(str_contains($u->user_email,'@tager.local')?'':$u->user_email).'"></label><label>المحافظة<input name="governorate" value="'.esc_attr(get_user_meta($u->ID,'governorate',true)).'"></label><label>الحد الأدنى للطلب<input type="number" min="0" name="vendor_min_order" value="'.esc_attr(get_user_meta($u->ID,'vendor_min_order',true)).'"></label><label>رقم السجل التجاري<input name="commercial_register" value="'.esc_attr(get_user_meta($u->ID,'commercial_register',true)).'"></label><label>الرقم الضريبي<input name="tax_number" value="'.esc_attr(get_user_meta($u->ID,'tax_number',true)).'"></label><label>IBAN<input name="iban" value="'.esc_attr(get_user_meta($u->ID,'iban',true)).'"></label><label class="full">وصف المتجر<textarea name="store_description">'.esc_textarea(get_user_meta($u->ID,'store_description',true)).'</textarea></label><button class="t40-btn">حفظ إعدادات المتجر</button></form></div>';}
    public static function save_profile(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer(self::NONCE);$u=wp_get_current_user();$phone=sanitize_text_field($_POST['phone']??'');if(!$phone)wp_die('رقم الهاتف مطلوب');$display=sanitize_text_field($_POST['display_name']??'');if($display)wp_update_user(['ID'=>$u->ID,'display_name'=>$display]);$email=sanitize_email($_POST['email']??'');if($email && !email_exists($email))wp_update_user(['ID'=>$u->ID,'user_email'=>$email]);foreach(['phone','governorate','city','address','store_name','vendor_min_order','commercial_register','tax_number','iban','store_description'] as $k)if(isset($_POST[$k]))update_user_meta($u->ID,$k,sanitize_textarea_field(wp_unslash($_POST[$k])));wp_safe_redirect(wp_get_referer()?:self::url(self::vendor($u)?'vendor-dashboard':'my-account'));exit;}
    public static function save_product(){if(!is_user_logged_in()||!self::vendor())wp_die('No permission');check_admin_referer(self::NONCE);$u=wp_get_current_user();$id=absint($_POST['product_id']??0);if($id && (int)get_post_field('post_author',$id)!==$u->ID)wp_die('No permission');$title=sanitize_text_field($_POST['title']??'');$ret=(float)($_POST['retail_price']??0);$wh=(float)($_POST['wholesale_price']??0);$bulk=(float)($_POST['bulk_price']??0);$wmin=max(1,(int)($_POST['wholesale_min']??1));$bmin=max(1,(int)($_POST['bulk_min']??1));$stock=max(0,(int)($_POST['stock']??0));if(!$title||$ret<=0||$wh<=0||$bulk<=0)wp_die('أكمل بيانات المنتج والأسعار');if(!($ret>=$wh && $wh>=$bulk))wp_die('يجب أن يكون سعر القطاعي أكبر أو يساوي الجملة، والجملة أكبر أو تساوي جملة الجملة');if($bmin<=$wmin)wp_die('حد جملة الجملة يجب أن يكون أكبر من حد الجملة');$data=['post_type'=>'tager_product','post_status'=>'pending','post_title'=>$title,'post_content'=>wp_kses_post($_POST['description']??''),'post_author'=>$u->ID];if($id)$data['ID']=$id;$pid=$id?wp_update_post($data,true):wp_insert_post($data,true);if(is_wp_error($pid))wp_die($pid->get_error_message());$meta=['vendor_id'=>$u->ID,'sku'=>sanitize_text_field($_POST['sku']??''),'category'=>sanitize_text_field($_POST['category']??''),'retail_price'=>$ret,'wholesale_price'=>$wh,'bulk_price'=>$bulk,'wholesale_min'=>$wmin,'bulk_min'=>$bmin,'stock'=>$stock,'max_order'=>max(0,(int)($_POST['max_order']??0)),'lead_days'=>max(0,(int)($_POST['lead_days']??0))];foreach($meta as $k=>$v)update_post_meta($pid,$k,$v);if(!empty($_FILES['product_image']['name'])){require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$aid=media_handle_upload('product_image',$pid);if(!is_wp_error($aid))set_post_thumbnail($pid,$aid);}wp_safe_redirect(add_query_arg(['tab'=>'products','saved'=>1],self::url('vendor-dashboard')));exit;}
    public static function admin_workspace(){if(!is_user_logged_in()||!self::admin_team())return '<div class="t40-alert">غير مصرح.</div>';$pending_users=get_users(['role'=>'tager_vendor_pending','number'=>20]);$pending_products=get_posts(['post_type'=>'tager_product','post_status'=>'pending','posts_per_page'=>20]);ob_start();echo '<div class="t40-head"><div><span>مركز الإدارة</span><h1>الموافقات والمتابعة</h1><p>راجع الموردين والمنتجات والطلبات من لوحة واحدة.</p></div><a class="t40-btn" href="'.esc_url(admin_url('admin.php?page=tager-v40')).'">فتح لوحة WordPress</a></div><div class="t40-grid"><section class="t40-card"><h2>موردون للمراجعة</h2>';if(!$pending_users)echo '<p>لا توجد طلبات جديدة.</p>';foreach($pending_users as $v)echo '<div class="t40-item"><b>'.esc_html(get_user_meta($v->ID,'store_name',true)?:$v->display_name).'</b><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v40_vendor_decision"><input type="hidden" name="user_id" value="'.$v->ID.'"><input type="hidden" name="decision" value="approve">'.wp_nonce_field(self::NONCE,'_wpnonce',true,false).'<button class="t40-btn small">قبول</button></form></div>';echo '</section><section class="t40-card"><h2>منتجات للمراجعة</h2>';if(!$pending_products)echo '<p>لا توجد منتجات معلقة.</p>';foreach($pending_products as $p)echo '<div class="t40-item"><b>'.esc_html($p->post_title).'</b><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v40_product_decision"><input type="hidden" name="product_id" value="'.$p->ID.'"><input type="hidden" name="decision" value="publish">'.wp_nonce_field(self::NONCE,'_wpnonce',true,false).'<button class="t40-btn small">نشر</button></form></div>';echo '</section></div>';return ob_get_clean();}
    public static function vendor_decision(){if(!self::admin_team())wp_die('No permission');check_admin_referer(self::NONCE);$id=absint($_POST['user_id']??0);if($id && ($_POST['decision']??'')==='approve'){$u=new WP_User($id);$u->set_role('tager_vendor');update_user_meta($id,'vendor_status','approved');}wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=tager-v40'));exit;}
    public static function product_decision(){if(!self::admin_team())wp_die('No permission');check_admin_referer(self::NONCE);$id=absint($_POST['product_id']??0);if($id && ($_POST['decision']??'')==='publish')wp_update_post(['ID'=>$id,'post_status'=>'publish']);wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=tager-v40'));exit;}
    public static function menu(){add_menu_page('Tager V40','Tager V40','read','tager-v40',[__CLASS__,'screen'],'dashicons-dashboard',2);}
    public static function screen(){if(!self::admin_team())wp_die('No permission');echo '<div class="wrap"><h1>Tager V40 — مركز التشغيل الكامل</h1><p>هذه الصفحة تعرض حالة المسارات الأساسية وروابط الاختبار.</p><p><a class="button button-primary" href="'.esc_url(self::url('admin-portal')).'">فتح بوابة الإدارة</a> <a class="button" href="'.esc_url(self::url('vendor-dashboard')).'">فتح لوحة المورد</a> <a class="button" href="'.esc_url(self::url('my-account')).'">فتح حساب العميل</a></p><table class="widefat striped"><thead><tr><th>العنصر</th><th>الحالة</th></tr></thead><tbody>';foreach(self::pages() as $slug=>$d){$p=get_page_by_path($slug);echo '<tr><td>'.esc_html($d[0]).'</td><td>'.($p?'✅ موجودة':'❌ مفقودة').'</td></tr>';}echo '<tr><td>نوع المنتجات tager_product</td><td>'.(post_type_exists('tager_product')?'✅ مسجل':'❌ غير مسجل').'</td></tr></tbody></table><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="margin-top:15px"><input type="hidden" name="action" value="tager_v40_repair">'.wp_nonce_field(self::NONCE,'_wpnonce',true,false).'<button class="button">إصلاح الصفحات</button></form></div>';}
    public static function repair_action(){if(!self::admin_team())wp_die('No permission');check_admin_referer(self::NONCE);foreach(self::pages() as $slug=>$d){$p=get_page_by_path($slug);if(!$p)wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$d[0],'post_name'=>$slug,'post_content'=>$d[1]]);else wp_update_post(['ID'=>$p->ID,'post_content'=>$d[1]]);}flush_rewrite_rules(false);wp_safe_redirect(admin_url('admin.php?page=tager-v40&repaired=1'));exit;}
    public static function assets(){wp_register_style('tager-v40',false);wp_enqueue_style('tager-v40');wp_add_inline_style('tager-v40','.t40-shell{display:grid;grid-template-columns:260px 1fr;gap:24px;margin:28px auto;max-width:1280px}.t40-shell aside{background:#0b4d3b;color:#fff;border-radius:22px;padding:22px;height:max-content;position:sticky;top:20px}.t40-user{text-align:center;padding:12px}.t40-avatar{width:64px;height:64px;border-radius:50%;background:#d8ad37;color:#12392e;display:grid;place-items:center;font-size:28px;font-weight:900;margin:auto auto 10px}.t40-user small{display:block;opacity:.8;margin-top:5px}.t40-tabs{display:grid;gap:7px}.t40-tabs a{padding:12px 14px;border-radius:11px;color:#fff;text-decoration:none}.t40-tabs a:hover,.t40-tabs a.active{background:#d8ad37;color:#163c31}.t40-head{background:linear-gradient(135deg,#0b4d3b,#17745a);color:#fff;padding:30px;border-radius:22px;display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.t40-head span{color:#f4d47a;font-weight:800}.t40-btn{display:inline-flex;align-items:center;justify-content:center;background:#d8ad37;color:#173c31!important;border:0;border-radius:11px;padding:12px 18px;text-decoration:none;font-weight:800;cursor:pointer}.t40-btn.small{padding:7px 12px}.t40-stats,.t40-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin:18px 0}.t40-stats article,.t40-card{background:#fff;border:1px solid #e4ebe7;border-radius:18px;padding:22px;box-shadow:0 10px 30px rgba(14,61,48,.07)}.t40-stats b{font-size:28px;display:block;color:#0b4d3b}.t40-card{text-decoration:none;color:inherit}.t40-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.t40-form label{font-weight:700}.t40-form input,.t40-form textarea{width:100%;padding:12px;border:1px solid #cad8d2;border-radius:10px;margin-top:6px;box-sizing:border-box}.t40-form textarea{min-height:120px}.t40-form .full{grid-column:1/-1}.t40-table{overflow:auto}.t40-table table{width:100%;border-collapse:collapse}.t40-table th,.t40-table td{padding:12px;border-bottom:1px solid #e6ece9;text-align:right}.t40-row,.t40-item{display:flex;justify-content:space-between;align-items:center;gap:12px}.t40-item{padding:12px 0;border-bottom:1px solid #eee}.t40-alert{padding:18px;background:#fff4d5;border:1px solid #ecd27b;border-radius:14px;margin-bottom:16px}@media(max-width:850px){.t40-shell{grid-template-columns:1fr}.t40-shell aside{position:static}.t40-tabs{grid-template-columns:repeat(2,1fr)}.t40-form{grid-template-columns:1fr}.t40-head{display:block}.t40-head .t40-btn{margin-top:14px}}');}
}
Tager_V40_Complete_Workspaces::boot();
