<?php
/**
 * Plugin Name: Tager V33 Authentication & Full Dashboards
 * Description: Phone-first registration, optional email, and expanded customer/vendor/admin experiences.
 * Version: 33.0.0
 */
if (!defined('ABSPATH')) exit;
class Tager_V33 {
 const V='33.0.0';
 static function init(){
  add_action('init',[__CLASS__,'override'],999);
  add_action('admin_post_nopriv_tager_customer_register',[__CLASS__,'reg_customer'],0);
  add_action('admin_post_nopriv_tager_vendor_apply',[__CLASS__,'reg_vendor'],0);
  add_action('admin_post_tager_v33_save_profile',[__CLASS__,'save_profile']);
  add_action('admin_post_tager_v33_save_product',[__CLASS__,'save_product']);
  add_action('admin_post_tager_v33_product_action',[__CLASS__,'product_action']);
  add_filter('authenticate',[__CLASS__,'phone_login'],1,3);
  add_action('wp_enqueue_scripts',[__CLASS__,'assets'],999);
  add_action('admin_menu',[__CLASS__,'admin_menu'],99);
 }
 static function t($a,$e){return (!empty($_GET['lang'])&&$_GET['lang']==='en')?$e:$a;}
 static function url($s){$p=get_page_by_path($s);return $p?get_permalink($p):home_url('/'.$s.'/');}
 static function phone($p){$p=preg_replace('/\D+/','',(string)$p);if(strpos($p,'0020')===0)$p=substr($p,4);if(strpos($p,'20')===0&&strlen($p)===12)$p=substr($p,2);if(strlen($p)===10&&$p[0]==='1')$p='0'.$p;return $p;}
 static function valid_phone($p){return (bool)preg_match('/^01[0125]\d{8}$/',$p);}
 static function user_phone($p,$exclude=0){$u=get_users(['number'=>1,'meta_key'=>'phone_normalized','meta_value'=>$p]);if($u&&$u[0]->ID!=$exclude)return $u[0];return false;}
 static function public_email($u){$e=$u instanceof WP_User?$u->user_email:(string)$u;return (strpos($e,'@tager.local')!==false||strpos($e,'@phone.tager')!==false)?'':$e;}
 static function gen_email($phone){return 'u'.$phone.'@phone.tager';}
 static function override(){
  remove_shortcode('tager_customer_register');remove_shortcode('tager_vendor_register');remove_shortcode('tager_customer_account');remove_shortcode('tager_vendor_dashboard');
  add_shortcode('tager_customer_register',[__CLASS__,'customer_register']);add_shortcode('tager_vendor_register',[__CLASS__,'vendor_register']);add_shortcode('tager_customer_account',[__CLASS__,'customer_dash']);add_shortcode('tager_vendor_dashboard',[__CLASS__,'vendor_dash']);
  foreach([['Tager_V28_Phone_Email_Auth','customer_register'],['Tager_V28_Phone_Email_Auth','vendor_register'],['Tager_Marketplace_Complete','handle_customer_register'],['Tager_Marketplace_Complete','handle_vendor_apply']] as $x){remove_action('admin_post_nopriv_tager_customer_register',$x);remove_action('admin_post_nopriv_tager_vendor_apply',$x);}
 }
 static function auth_form($vendor=false){if(is_user_logged_in())return '<div class="t33-card">'.esc_html(self::t('أنت مسجل الدخول بالفعل.','You are already signed in.')).'</div>';$action=$vendor?'tager_vendor_apply':'tager_customer_register';ob_start();?><div class="t33-auth"><aside><span class="t33-logo">T</span><h1><?php echo esc_html($vendor?self::t('ابدأ البيع على تاجر','Start selling on Tager'):self::t('أنشئ حسابك','Create your account'));?></h1><p><?php echo esc_html(self::t('رقم الهاتف هو وسيلة التسجيل الأساسية. البريد الإلكتروني اختياري تمامًا.','Your phone number is the primary registration method. Email is completely optional.'));?></p><ul><li>✓ <?php echo esc_html(self::t('دخول برقم الهاتف','Sign in by phone'));?></li><li>✓ <?php echo esc_html(self::t('متابعة الطلبات والإشعارات','Orders and notifications'));?></li><li>✓ <?php echo esc_html(self::t('حساب آمن وسهل','Simple secure account'));?></li></ul></aside><main><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="<?php echo esc_attr($action);?>"><?php wp_nonce_field($action);?><h2><?php echo esc_html($vendor?self::t('تسجيل مورد','Vendor registration'):self::t('تسجيل عميل','Customer registration'));?></h2><div class="t33-grid"><label><?php echo esc_html(self::t('الاسم الكامل','Full name'));?><input required name="name"></label><?php if($vendor):?><label><?php echo esc_html(self::t('اسم المتجر','Store name'));?><input required name="store_name"></label><?php endif;?><label><?php echo esc_html(self::t('رقم الهاتف','Phone number'));?><input required inputmode="tel" name="phone" placeholder="01012345678"></label><label><?php echo esc_html(self::t('البريد الإلكتروني (اختياري)','Email (optional)'));?><input type="email" name="email" placeholder="name@example.com"></label><label class="wide"><?php echo esc_html(self::t('كلمة المرور','Password'));?><input required minlength="8" type="password" name="password"></label><?php if($vendor):?><label class="wide"><?php echo esc_html(self::t('تفاصيل النشاط والسجل التجاري','Business and registration details'));?><textarea name="notes"></textarea></label><?php endif;?></div><button class="btn primary widebtn"><?php echo esc_html($vendor?self::t('إرسال طلب المورد','Submit vendor application'):self::t('إنشاء الحساب','Create account'));?></button></form><div class="t33-login"><h3><?php echo esc_html(self::t('لديك حساب؟','Already have an account?'));?></h3><?php wp_login_form(['redirect'=>self::url($vendor?'vendor-dashboard':'my-account'),'label_username'=>self::t('رقم الهاتف أو البريد','Phone or email'),'label_log_in'=>self::t('تسجيل الدخول','Sign in')]);?></div></main></div><?php return ob_get_clean();}
 static function customer_register(){return self::auth_form(false);}static function vendor_register(){return self::auth_form(true);}
 static function do_reg($vendor){check_admin_referer($vendor?'tager_vendor_apply':'tager_customer_register');$phone=self::phone($_POST['phone']??'');$email=sanitize_email($_POST['email']??'');$name=sanitize_text_field($_POST['name']??'');$pass=(string)($_POST['password']??'');if(!$name||!self::valid_phone($phone)||strlen($pass)<8)wp_die('راجع الاسم ورقم الهاتف وكلمة المرور.');if(self::user_phone($phone))wp_die('رقم الهاتف مستخدم بالفعل.');if($email&&(!is_email($email)||email_exists($email)))wp_die('البريد غير صحيح أو مستخدم.');$login=$phone;$i=1;while(username_exists($login))$login=$phone.'_'.$i++;$actual=$email?:self::gen_email($phone);$role=$vendor?'tager_vendor_pending':'tager_customer';$id=wp_insert_user(['user_login'=>$login,'user_pass'=>$pass,'user_email'=>$actual,'display_name'=>$name,'role'=>$role]);if(is_wp_error($id))wp_die($id->get_error_message());update_user_meta($id,'phone',$phone);update_user_meta($id,'phone_normalized',$phone);update_user_meta($id,'email_optional',$email?0:1);if($vendor){update_user_meta($id,'store_name',sanitize_text_field($_POST['store_name']??''));update_user_meta($id,'notes',sanitize_textarea_field($_POST['notes']??''));update_user_meta($id,'vendor_status','pending');wp_safe_redirect(add_query_arg('registered','vendor',self::url('vendor-register')));}else{wp_set_auth_cookie($id,true);wp_safe_redirect(self::url('my-account'));}exit;}
 static function reg_customer(){self::do_reg(false);}static function reg_vendor(){self::do_reg(true);}
 static function phone_login($user,$username,$password){if($user instanceof WP_User||!$username||!$password)return $user;$p=self::phone($username);if(!self::valid_phone($p))return $user;$u=self::user_phone($p);return $u?wp_authenticate_username_password(null,$u->user_login,$password):$user;}
 static function nav($type,$tab){$items=$type==='vendor'?['overview'=>'الرئيسية','products'=>'المنتجات','add-product'=>'إضافة منتج','orders'=>'الطلبات','earnings'=>'الأرباح','store'=>'إعدادات المتجر','profile'=>'الحساب']:['overview'=>'الرئيسية','orders'=>'طلباتي','addresses'=>'العناوين','wishlist'=>'المفضلة','support'=>'الدعم','profile'=>'الحساب'];$slug=$type==='vendor'?'vendor-dashboard':'my-account';$o='<nav class="t33-nav">';foreach($items as $k=>$v)$o.='<a class="'.($tab===$k?'active':'').'" href="'.esc_url(add_query_arg('tab',$k,self::url($slug))).'">'.esc_html($v).'</a>';return $o.'</nav>';}
 static function shell($type,$body,$tab){$u=wp_get_current_user();return '<div class="t33-shell"><aside><div class="t33-brand">Tager <small>'.esc_html($type==='vendor'?(get_user_meta($u->ID,'store_name',true)?:'Vendor'):$u->display_name).'</small></div>'.self::nav($type,$tab).'<a class="logout" href="'.esc_url(wp_logout_url(home_url())).'">'.esc_html(self::t('تسجيل الخروج','Sign out')).'</a></aside><main>'.$body.'</main></div>';}
 static function customer_dash(){if(!is_user_logged_in())return self::auth_form(false);$u=wp_get_current_user();$tab=sanitize_key($_GET['tab']??'overview');$orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1,'meta_key'=>'customer_user','meta_value'=>$u->ID]);$total=0;foreach($orders as $o)$total+=(float)get_post_meta($o->ID,'total',true);ob_start();echo '<header class="t33-head"><div><h1>'.esc_html(self::t('مرحبًا، ','Welcome, ')).esc_html($u->display_name).'</h1><p>'.esc_html(self::t('تابع حسابك وطلباتك من مكان واحد.','Manage your account and orders in one place.')).'</p></div><a class="btn primary" href="'.esc_url(self::url('shop')).'">'.esc_html(self::t('تسوق الآن','Shop now')).'</a></header>';
 if($tab==='overview'){echo '<div class="t33-stats"><article><b>'.count($orders).'</b><span>الطلبات</span></article><article><b>'.number_format($total,2).'</b><span>إجمالي المشتريات</span></article><article><b>'.esc_html(get_user_meta($u->ID,'governorate',true)?:'—').'</b><span>المحافظة</span></article></div><section class="t33-card"><h2>آخر الطلبات</h2>'.self::orders_table($orders).'</section>';}elseif($tab==='orders'){echo '<section class="t33-card"><h2>جميع الطلبات</h2>'.self::orders_table($orders).'</section>';}elseif(in_array($tab,['addresses','profile'])){echo self::profile_form($u,$tab==='addresses');}else echo '<section class="t33-card"><h2>'.esc_html($tab==='wishlist'?'المفضلة':'مركز الدعم').'</h2><p>'.esc_html($tab==='wishlist'?'احفظ المنتجات للرجوع إليها لاحقًا.':'أنشئ تذكرة دعم وتابع الردود من هنا.').'</p></section>';return self::shell('customer',ob_get_clean(),$tab);}
 static function orders_table($orders){$h='<div class="table-wrap"><table><tr><th>#</th><th>التاريخ</th><th>الإجمالي</th><th>الحالة</th></tr>';foreach($orders as $o)$h.='<tr><td>'.$o->ID.'</td><td>'.esc_html(get_the_date('', $o)).'</td><td>'.esc_html(number_format((float)get_post_meta($o->ID,'total',true),2)).' EGP</td><td><span class="badge">'.esc_html(get_post_meta($o->ID,'order_status',true)).'</span></td></tr>';return $h.($orders?'':'<tr><td colspan="4">لا توجد طلبات بعد.</td></tr>').'</table></div>';}
 static function profile_form($u,$address=false){ob_start();?><section class="t33-card"><h2><?php echo $address?'العناوين والتوصيل':'بيانات الحساب';?></h2><form class="t33-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v33_save_profile"><?php wp_nonce_field('tager_v33_save_profile');?><label>الاسم الكامل<input required name="name" value="<?php echo esc_attr($u->display_name);?>"></label><label>رقم الهاتف<input required name="phone" value="<?php echo esc_attr(get_user_meta($u->ID,'phone',true));?>"></label><label>البريد الإلكتروني (اختياري)<input type="email" name="email" value="<?php echo esc_attr(self::public_email($u));?>"></label><label>المحافظة<input name="governorate" value="<?php echo esc_attr(get_user_meta($u->ID,'governorate',true));?>"></label><label>المدينة / المنطقة<input name="city" value="<?php echo esc_attr(get_user_meta($u->ID,'city',true));?>"></label><label class="wide">العنوان بالتفصيل<textarea name="address"><?php echo esc_textarea(get_user_meta($u->ID,'address',true));?></textarea></label><button class="btn primary">حفظ التغييرات</button></form></section><?php return ob_get_clean();}
 static function save_profile(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v33_save_profile');$u=wp_get_current_user();$p=self::phone($_POST['phone']??'');if(!self::valid_phone($p)||self::user_phone($p,$u->ID))wp_die('رقم الهاتف غير صحيح أو مستخدم.');$e=sanitize_email($_POST['email']??'');if($e&&(!is_email($e)||(email_exists($e)&&email_exists($e)!=$u->ID)))wp_die('البريد غير صحيح أو مستخدم.');wp_update_user(['ID'=>$u->ID,'display_name'=>sanitize_text_field($_POST['name']??''),'user_email'=>$e?:self::gen_email($p)]);foreach(['governorate','city','address'] as $k)update_user_meta($u->ID,$k,sanitize_textarea_field($_POST[$k]??''));update_user_meta($u->ID,'phone',$p);update_user_meta($u->ID,'phone_normalized',$p);wp_safe_redirect(wp_get_referer()?:self::url('my-account'));exit;}
 static function vendor_dash(){if(!is_user_logged_in())return self::auth_form(true);$u=wp_get_current_user();if(in_array('tager_vendor_pending',$u->roles,true))return '<div class="t33-card pending"><h1>طلبك تحت المراجعة</h1><p>سيتم تفعيل لوحة المورد بعد موافقة الإدارة.</p></div>';if(!in_array('tager_vendor',$u->roles,true)&&!current_user_can('manage_options'))return '<div class="t33-card">غير مصرح.</div>';$tab=sanitize_key($_GET['tab']??'overview');$products=get_posts(['post_type'=>'tager_product','numberposts'=>-1,'author'=>$u->ID,'post_status'=>['publish','pending','draft']]);$orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1]);$sales=0;$count=0;foreach($orders as $o){$groups=get_post_meta($o->ID,'vendor_groups',true);if(is_array($groups))foreach($groups as $g)if((int)($g['vendor_id']??0)===$u->ID){$sales+=(float)($g['total']??0);$count++;}}ob_start();echo '<header class="t33-head"><div><h1>لوحة المورد</h1><p>'.esc_html(get_user_meta($u->ID,'store_name',true)).'</p></div><a class="btn primary" href="'.esc_url(add_query_arg('tab','add-product',self::url('vendor-dashboard'))).'">+ إضافة منتج</a></header>';
 if($tab==='overview'){echo '<div class="t33-stats"><article><b>'.count($products).'</b><span>المنتجات</span></article><article><b>'.$count.'</b><span>الطلبات</span></article><article><b>'.number_format($sales,2).'</b><span>المبيعات</span></article><article><b>'.number_format($sales*.9,2).'</b><span>صافي المستحق</span></article></div><section class="t33-card"><h2>آخر المنتجات</h2>'.self::products_table($products).'</section>';}elseif($tab==='products'){echo '<section class="t33-card"><h2>إدارة المنتجات</h2>'.self::products_table($products).'</section>';}elseif($tab==='add-product'){echo self::product_form();}elseif($tab==='orders'){echo '<section class="t33-card"><h2>طلبات المتجر</h2><p>عرض الطلبات المرتبطة بمنتجاتك وحالات التجهيز والشحن.</p></section>';}elseif($tab==='earnings'){echo '<div class="t33-stats"><article><b>'.number_format($sales,2).'</b><span>إجمالي المبيعات</span></article><article><b>'.number_format($sales*.1,2).'</b><span>عمولة المنصة</span></article><article><b>'.number_format($sales*.9,2).'</b><span>صافي المورد</span></article></div>';}else echo self::vendor_settings($u);return self::shell('vendor',ob_get_clean(),$tab);}
 static function products_table($ps){$h='<div class="table-wrap"><table><tr><th>المنتج</th><th>قطاعي</th><th>جملة</th><th>جملة الجملة</th><th>المخزون</th><th>الحالة</th><th></th></tr>';foreach($ps as $p)$h.='<tr><td>'.esc_html($p->post_title).'</td><td>'.esc_html(get_post_meta($p->ID,'retail_price',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'wholesale_price',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'bulk_price',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'stock',true)).'</td><td><span class="badge">'.esc_html($p->post_status).'</span></td><td><a href="'.esc_url(add_query_arg(['tab'=>'add-product','edit'=>$p->ID],self::url('vendor-dashboard'))).'">تعديل</a></td></tr>';return $h.($ps?'':'<tr><td colspan="7">لا توجد منتجات.</td></tr>').'</table></div>';}
 static function product_form(){$id=(int)($_GET['edit']??0);$p=$id?get_post($id):null;if($p&&$p->post_author!=get_current_user_id()&&!current_user_can('manage_options'))$p=null;ob_start();?><section class="t33-card"><h2><?php echo $p?'تعديل المنتج':'إضافة منتج جديد';?></h2><form class="t33-form" method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v33_save_product"><input type="hidden" name="product_id" value="<?php echo (int)$id;?>"><?php wp_nonce_field('tager_v33_save_product');?><label class="wide">اسم المنتج<input required name="title" value="<?php echo esc_attr($p?$p->post_title:'');?>"></label><label class="wide">الوصف<textarea required name="description"><?php echo esc_textarea($p?$p->post_content:'');?></textarea></label><label>سعر القطاعي<input required min="0" step="0.01" type="number" name="retail_price" value="<?php echo esc_attr($id?get_post_meta($id,'retail_price',true):'');?>"></label><label>سعر الجملة<input required min="0" step="0.01" type="number" name="wholesale_price" value="<?php echo esc_attr($id?get_post_meta($id,'wholesale_price',true):'');?>"></label><label>سعر جملة الجملة<input required min="0" step="0.01" type="number" name="bulk_price" value="<?php echo esc_attr($id?get_post_meta($id,'bulk_price',true):'');?>"></label><label>حد الجملة<input required min="1" type="number" name="wholesale_min" value="<?php echo esc_attr($id?get_post_meta($id,'wholesale_min',true):10);?>"></label><label>حد جملة الجملة<input required min="1" type="number" name="bulk_min" value="<?php echo esc_attr($id?get_post_meta($id,'bulk_min',true):50);?>"></label><label>المخزون<input required min="0" type="number" name="stock" value="<?php echo esc_attr($id?get_post_meta($id,'stock',true):0);?>"></label><label>أقصى كمية للطلب<input min="1" type="number" name="max_qty" value="<?php echo esc_attr($id?get_post_meta($id,'max_qty',true):9999);?>"></label><label class="wide">صورة المنتج<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><button class="btn primary">حفظ وإرسال للمراجعة</button></form></section><?php return ob_get_clean();}
 static function save_product(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v33_save_product');$u=wp_get_current_user();if(!in_array('tager_vendor',$u->roles,true)&&!current_user_can('manage_options'))wp_die('Not allowed');$id=(int)($_POST['product_id']??0);if($id&&get_post_field('post_author',$id)!=$u->ID&&!current_user_can('manage_options'))wp_die('Not allowed');$r=(float)$_POST['retail_price'];$w=(float)$_POST['wholesale_price'];$b=(float)$_POST['bulk_price'];$wm=(int)$_POST['wholesale_min'];$bm=(int)$_POST['bulk_min'];if($r<$w||$w<$b||$bm<=$wm)wp_die('راجع تدرج الأسعار وحدود الكميات.');$data=['post_type'=>'tager_product','post_title'=>sanitize_text_field($_POST['title']??''),'post_content'=>sanitize_textarea_field($_POST['description']??''),'post_status'=>'pending','post_author'=>$u->ID];if($id){$data['ID']=$id;$id=wp_update_post($data);}else$id=wp_insert_post($data);foreach(['retail_price'=>$r,'wholesale_price'=>$w,'bulk_price'=>$b,'wholesale_min'=>$wm,'bulk_min'=>$bm,'stock'=>(int)$_POST['stock'],'max_qty'=>(int)$_POST['max_qty']] as $k=>$v)update_post_meta($id,$k,$v);if(!empty($_FILES['image']['name'])){require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$att=media_handle_upload('image',$id);if(!is_wp_error($att))set_post_thumbnail($id,$att);}wp_safe_redirect(add_query_arg('tab','products',self::url('vendor-dashboard')));exit;}
 static function product_action(){}
 static function vendor_settings($u){ob_start();?><section class="t33-card"><h2>إعدادات المتجر والحساب</h2><form class="t33-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v33_save_profile"><?php wp_nonce_field('tager_v33_save_profile');?><label>اسم المسؤول<input required name="name" value="<?php echo esc_attr($u->display_name);?>"></label><label>رقم الهاتف<input required name="phone" value="<?php echo esc_attr(get_user_meta($u->ID,'phone',true));?>"></label><label>البريد (اختياري)<input type="email" name="email" value="<?php echo esc_attr(self::public_email($u));?>"></label><label>المحافظة<input name="governorate" value="<?php echo esc_attr(get_user_meta($u->ID,'governorate',true));?>"></label><label class="wide">العنوان<textarea name="address"><?php echo esc_textarea(get_user_meta($u->ID,'address',true));?></textarea></label><button class="btn primary">حفظ</button></form></section><?php return ob_get_clean();}
 static function admin_menu(){add_menu_page('Tager Admin','Tager Admin','manage_options','tager-v33-admin',[__CLASS__,'admin_page'],'dashicons-store',2);}
 static function admin_page(){if(!current_user_can('manage_options'))return;$vendors=get_users(['role__in'=>['tager_vendor','tager_vendor_pending']]);$customers=get_users(['role'=>'tager_customer']);$products=wp_count_posts('tager_product');$orders=wp_count_posts('tager_order');echo '<div class="wrap"><h1>Tager Admin Command Center</h1><div class="t33-adminstats"><div><b>'.count($vendors).'</b><span>الموردون</span></div><div><b>'.count($customers).'</b><span>العملاء</span></div><div><b>'.(int)($products->publish??0).'</b><span>المنتجات المنشورة</span></div><div><b>'.(int)($orders->publish??0).'</b><span>الطلبات</span></div></div><h2>روابط الإدارة السريعة</h2><p><a class="button button-primary" href="'.admin_url('users.php').'">إدارة المستخدمين</a> <a class="button" href="'.admin_url('edit.php?post_type=tager_product').'">المنتجات</a> <a class="button" href="'.admin_url('edit.php?post_type=tager_order').'">الطلبات</a> <a class="button" href="'.admin_url('admin.php?page=tager-v30-staff').'">فريق الإدارة والصلاحيات</a></p></div>';}
 static function assets(){wp_register_style('tager-v33',false,[],self::V);wp_enqueue_style('tager-v33');wp_add_inline_style('tager-v33',self::css());wp_add_inline_script('jquery','document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("input[type=email]").forEach(e=>{e.required=false;});});');}
 static function css(){return '.t33-auth{max-width:1100px;margin:35px auto;display:grid;grid-template-columns:.8fr 1.2fr;background:#fff;border-radius:28px;overflow:hidden;box-shadow:0 24px 70px rgba(16,55,39,.14)}.t33-auth aside{padding:48px;background:linear-gradient(145deg,#103f2d,#082a1d);color:#fff}.t33-logo{display:grid;width:56px;height:56px;place-items:center;background:#d6ad46;color:#123a2a;border-radius:18px;font-size:28px;font-weight:900}.t33-auth main{padding:42px}.t33-grid,.t33-form{display:grid;grid-template-columns:1fr 1fr;gap:16px}.t33-grid label,.t33-form label{display:grid;gap:7px;font-weight:700}.t33-grid .wide,.t33-form .wide{grid-column:1/-1}.t33-grid input,.t33-grid textarea,.t33-form input,.t33-form textarea,.t33-form select{padding:13px;border:1px solid #d6dfda;border-radius:12px;width:100%;box-sizing:border-box}.widebtn{width:100%;margin-top:16px}.t33-login{margin-top:28px;border-top:1px solid #eee;padding-top:22px}.t33-shell{max-width:1400px;margin:28px auto;display:grid;grid-template-columns:250px 1fr;min-height:75vh;background:#f5f7f5;border-radius:26px;overflow:hidden}.t33-shell>aside{background:#0e3b2a;color:#fff;padding:24px 16px;display:flex;flex-direction:column}.t33-brand{font-size:25px;font-weight:900;margin-bottom:25px}.t33-brand small{display:block;font-size:12px;opacity:.7}.t33-nav{display:grid;gap:6px}.t33-nav a,.logout{color:#fff;text-decoration:none;padding:12px;border-radius:12px}.t33-nav a.active,.t33-nav a:hover{background:rgba(255,255,255,.13)}.logout{margin-top:auto}.t33-shell>main{padding:28px;min-width:0}.t33-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.t33-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-bottom:20px}.t33-stats article,.t33-card{background:#fff;border:1px solid #e2e8e4;border-radius:18px;padding:20px}.t33-stats b{font-size:25px;display:block;color:#123d2b}.t33-stats span{color:#718077}.badge{padding:5px 9px;border-radius:99px;background:#edf4ef}.table-wrap{overflow:auto}.table-wrap table{width:100%;border-collapse:collapse}.table-wrap th,.table-wrap td{padding:12px;border-bottom:1px solid #edf0ee;text-align:start;white-space:nowrap}.t33-adminstats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}.t33-adminstats div{background:#fff;border:1px solid #ddd;padding:20px;border-radius:12px}.t33-adminstats b{font-size:28px;display:block}@media(max-width:900px){.t33-auth,.t33-shell{grid-template-columns:1fr}.t33-auth aside{padding:28px}.t33-stats{grid-template-columns:1fr 1fr}}@media(max-width:600px){.t33-auth main,.t33-shell>main{padding:18px}.t33-grid,.t33-form,.t33-stats{grid-template-columns:1fr}.t33-grid .wide,.t33-form .wide{grid-column:auto}.t33-head{align-items:flex-start;gap:12px}}';}
}
Tager_V33::init();
