<?php
/**
 * Plugin Name: Tager Marketplace V5 Fixes
 * Description: Completes vendor permissions, coupon deletion, vendor product management, customer cancellation, navigation and safer marketplace workflows.
 * Version: 5.0.0
 */
if(!defined('ABSPATH')) exit;
class Tager_V5_Fixes{
 static function init(){
  add_action('init',[__CLASS__,'bootstrap'],150);
  add_action('admin_menu',[__CLASS__,'menu'],40);
  add_action('admin_post_tager_coupon_delete',[__CLASS__,'coupon_delete'],1);
  add_action('admin_post_tager_vendor_permission_save',[__CLASS__,'permission_save'],1);
  add_action('admin_post_tager_vendor_product_delete',[__CLASS__,'product_delete']);
  add_action('admin_post_tager_vendor_product_edit',[__CLASS__,'product_edit']);
  add_action('admin_post_tager_customer_cancel_order',[__CLASS__,'cancel_order']);
  add_action('admin_post_tager_admin_product_review',[__CLASS__,'product_review']);
 }
 static function bootstrap(){
  if(wp_get_theme('tager-marketplace')->exists() && get_option('tager_v5_theme')!=='1'){switch_theme('tager-marketplace');update_option('tager_v5_theme','1');}
  $settings=wp_parse_args(get_option('tager_pro_settings',[]),['allow_vendor_product_edit'=>1,'allow_vendor_product_delete'=>0,'allow_vendor_coupons'=>1,'allow_vendor_order_status'=>1]);update_option('tager_pro_settings',$settings);
 }
 static function menu(){add_submenu_page('tager-control','Vendor Permissions','Vendor Permissions','manage_options','tager-vendor-permissions',[__CLASS__,'permissions_page']);add_submenu_page('tager-control','Product Review Queue','Product Review Queue','manage_options','tager-product-review',[__CLASS__,'review_page']);}
 static function permissions_page(){if(!current_user_can('manage_options'))return;$users=get_users(['role__in'=>['tager_vendor','tager_vendor_pending']]);echo '<div class="wrap"><h1>Vendor Permissions</h1><table class="widefat striped"><tr><th>Vendor</th><th>Status</th><th>Edit</th><th>Delete</th><th>Coupons</th><th>Orders</th><th>Save</th></tr>';foreach($users as $u){$p=wp_parse_args((array)get_user_meta($u->ID,'tager_permissions',true),['edit'=>1,'delete'=>0,'coupons'=>1,'orders'=>1]);echo '<tr><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><td>'.esc_html($u->display_name).'<br><small>'.esc_html($u->user_email).'</small></td><td>'.esc_html(get_user_meta($u->ID,'vendor_status',true)).'</td>';foreach(['edit','delete','coupons','orders'] as $k)echo '<td><input type="checkbox" name="'.$k.'" '.checked(!empty($p[$k]),true,false).'></td>';echo '<td><input type="hidden" name="action" value="tager_vendor_permission_save"><input type="hidden" name="user" value="'.$u->ID.'">'.wp_nonce_field('tager_permission_'.$u->ID,'_wpnonce',true,false).'<button class="button button-primary">Save</button></td></form></tr>';}echo '</table></div>';}
 static function permission_save(){if(!current_user_can('manage_options'))wp_die('Not allowed');$uid=(int)($_POST['user']??0);check_admin_referer('tager_permission_'.$uid);$p=[];foreach(['edit','delete','coupons','orders'] as $k)$p[$k]=isset($_POST[$k])?1:0;update_user_meta($uid,'tager_permissions',$p);wp_safe_redirect(admin_url('admin.php?page=tager-vendor-permissions'));exit;}
 static function coupon_delete(){if(!is_user_logged_in())wp_die('Login required');$id=(int)($_GET['coupon']??$_POST['coupon']??0);check_admin_referer('tager_coupon_delete_'.$id);$post=get_post($id);if(!$post||$post->post_type!=='tager_coupon'||((int)$post->post_author!==get_current_user_id()&&!current_user_can('manage_options')))wp_die('Not allowed');wp_delete_post($id,true);wp_safe_redirect(add_query_arg('tab','coupons',self::page('vendor-dashboard')));exit;}
 static function product_delete(){if(!is_user_logged_in())wp_die('Login required');$id=(int)($_GET['product']??0);check_admin_referer('tager_vendor_product_delete_'.$id);$p=get_post($id);$perm=(array)get_user_meta(get_current_user_id(),'tager_permissions',true);if(!$p||$p->post_type!=='tager_product'||(int)$p->post_author!==get_current_user_id()||empty($perm['delete']))wp_die('Not allowed');wp_trash_post($id);wp_safe_redirect(add_query_arg('tab','products',self::page('vendor-dashboard')));exit;}
 static function product_edit(){if(!is_user_logged_in())wp_die('Login required');$id=(int)($_POST['product']??0);check_admin_referer('tager_vendor_product_edit_'.$id);$p=get_post($id);$perm=wp_parse_args((array)get_user_meta(get_current_user_id(),'tager_permissions',true),['edit'=>1]);if(!$p||$p->post_type!=='tager_product'||(int)$p->post_author!==get_current_user_id()||empty($perm['edit']))wp_die('Not allowed');wp_update_post(['ID'=>$id,'post_title'=>sanitize_text_field($_POST['title_ar']??$p->post_title),'post_content'=>sanitize_textarea_field($_POST['description_ar']??$p->post_content),'post_status'=>'pending']);foreach(['name_en'=>'title_en','retail_price'=>'retail','wholesale_price'=>'wholesale','bulk_price'=>'bulk','wholesale_min'=>'wholesale_min','bulk_min'=>'bulk_min','max_qty'=>'max_qty','stock'=>'stock'] as $m=>$f)if(isset($_POST[$f]))update_post_meta($id,$m,sanitize_text_field($_POST[$f]));update_post_meta($id,'approval_status','pending');wp_safe_redirect(add_query_arg('tab','products',self::page('vendor-dashboard')));exit;}
 static function cancel_order(){if(!is_user_logged_in())wp_die('Login required');$id=(int)($_POST['order']??0);check_admin_referer('tager_cancel_'.$id);$o=get_post($id);if(!$o||$o->post_type!=='tager_order'||(int)$o->post_author!==get_current_user_id())wp_die('Not allowed');$status=get_post_meta($id,'order_status',true);if(!in_array($status,['New','Confirmed'],true))wp_die('Order can no longer be cancelled');update_post_meta($id,'order_status','Cancelled');wp_safe_redirect(self::page('my-account'));exit;}
 static function review_page(){if(!current_user_can('manage_options'))return;$q=new WP_Query(['post_type'=>'tager_product','post_status'=>['pending','draft'],'posts_per_page'=>100]);echo '<div class="wrap"><h1>Product Review Queue</h1><table class="widefat striped"><tr><th>Product</th><th>Vendor</th><th>Prices</th><th>Stock</th><th>Decision</th></tr>';while($q->have_posts()){$q->the_post();$id=get_the_ID();echo '<tr><td><b>'.esc_html(get_the_title()).'</b><br><small>'.esc_html(wp_trim_words(get_the_content(),18)).'</small></td><td>'.esc_html(get_the_author()).'</td><td>Retail '.esc_html(get_post_meta($id,'retail_price',true)).'<br>Wholesale '.esc_html(get_post_meta($id,'wholesale_price',true)).'<br>Bulk '.esc_html(get_post_meta($id,'bulk_price',true)).'</td><td>'.esc_html(get_post_meta($id,'stock',true)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_admin_product_review"><input type="hidden" name="product" value="'.$id.'">'.wp_nonce_field('tager_review_'.$id,'_wpnonce',true,false).'<select name="decision"><option value="approve">Approve</option><option value="reject">Reject</option></select><input name="note" placeholder="Review note"><button class="button button-primary">Save</button></form></td></tr>';}wp_reset_postdata();echo '</table></div>';}
 static function product_review(){if(!current_user_can('manage_options'))wp_die('Not allowed');$id=(int)($_POST['product']??0);check_admin_referer('tager_review_'.$id);$d=sanitize_key($_POST['decision']??'reject');if($d==='approve'){wp_update_post(['ID'=>$id,'post_status'=>'publish']);update_post_meta($id,'approval_status','approved');}else{wp_update_post(['ID'=>$id,'post_status'=>'draft']);update_post_meta($id,'approval_status','rejected');}update_post_meta($id,'review_note',sanitize_textarea_field($_POST['note']??''));wp_safe_redirect(admin_url('admin.php?page=tager-product-review'));exit;}
 static function page($slug){$p=get_option('tager_pages',[]);return isset($p[$slug])?get_permalink($p[$slug]):home_url('/'.$slug.'/');}
}
Tager_V5_Fixes::init();
