<?php
/**
 * Plugin Name: Tager Commerce Operations V8
 * Description: Vendor subscriptions, promotions, internal messaging, shipment tracking, bulk product import, KYC expiry monitoring, staff roles and advanced admin KPIs.
 * Version: 8.0.0
 */
if (!defined('ABSPATH')) exit;

class Tager_V8_Commerce_Ops {
    const V='8.0.0';
    public static function init(){
        add_action('init',[__CLASS__,'register'],60);
        add_action('init',[__CLASS__,'bootstrap'],160);
        add_action('admin_init',[__CLASS__,'roles']);
        add_action('admin_menu',[__CLASS__,'admin_menu'],50);
        add_action('wp_enqueue_scripts',[__CLASS__,'assets'],70);
        add_shortcode('tager_v8_messages',[__CLASS__,'messages_page']);
        add_shortcode('tager_v8_tracking',[__CLASS__,'tracking_page']);
        add_shortcode('tager_v8_vendor_plans',[__CLASS__,'plans_page']);
        add_shortcode('tager_v8_promotions',[__CLASS__,'promotions_page']);
        foreach(['message_send','tracking_update','plan_assign','promotion_save','promotion_status','bulk_import','kyc_update','staff_create'] as $a){
            add_action('admin_post_tager_v8_'.$a,[__CLASS__,$a]);
            if($a==='message_send') add_action('admin_post_nopriv_tager_v8_'.$a,[__CLASS__,$a]);
        }
    }
    public static function register(){
        register_post_type('tager_message',['labels'=>['name'=>'Marketplace Messages','singular_name'=>'Message'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor','author']]);
        register_post_type('tager_promotion',['labels'=>['name'=>'Promotions','singular_name'=>'Promotion'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor','thumbnail']]);
        register_post_type('tager_vendor_plan',['labels'=>['name'=>'Vendor Plans','singular_name'=>'Vendor Plan'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor']]);
        register_post_type('tager_shipment_event',['labels'=>['name'=>'Shipment Events','singular_name'=>'Shipment Event'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor','author']]);
    }
    public static function roles(){
        add_role('tager_support_agent','Tager Support Agent',['read'=>true,'edit_posts'=>false,'manage_tager_support'=>true]);
        add_role('tager_catalog_manager','Tager Catalog Manager',['read'=>true,'edit_posts'=>true,'publish_posts'=>false,'manage_tager_catalog'=>true]);
        add_role('tager_finance_agent','Tager Finance Agent',['read'=>true,'manage_tager_finance'=>true]);
        if($r=get_role('administrator')) foreach(['manage_tager_support','manage_tager_catalog','manage_tager_finance'] as $c)$r->add_cap($c);
    }
    private static function pages(){return get_option('tager_pages',[]);} private static function url($slug){$p=self::pages();return !empty($p[$slug])?get_permalink($p[$slug]):home_url('/'.$slug.'/');}
    private static function t($ar,$en){return (isset($_GET['lang'])&&$_GET['lang']==='en')?$en:$ar;}
    private static function nonce($a){return wp_nonce_field($a,'_wpnonce',true,false);} private static function money($v){return number_format((float)$v,2).' EGP';}
    public static function bootstrap(){
        if(get_option('tager_v8_bootstrap')===self::V)return;
        $pages=self::pages();$extra=[
            'messages'=>['الرسائل','[tager_v8_messages]'],
            'tracking'=>['تتبع الشحنات','[tager_v8_tracking]'],
            'vendor-plans'=>['باقات الموردين','[tager_v8_vendor_plans]'],
            'promotions'=>['العروض','[tager_v8_promotions]'],
        ];
        foreach($extra as $slug=>$d){$p=get_page_by_path($slug);$pages[$slug]=$p?$p->ID:wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_name'=>$slug,'post_title'=>$d[0],'post_content'=>$d[1]]);} update_option('tager_pages',$pages);
        self::seed_plans(); self::seed_promotions(); update_option('tager_v8_bootstrap',self::V);
    }
    private static function seed_plans(){if(get_option('tager_v8_plans_seeded'))return;$plans=[['Starter',0,25,10,0],['Growth',499,250,8,1],['Enterprise',1499,9999,5,1]];foreach($plans as $p){$id=wp_insert_post(['post_type'=>'tager_vendor_plan','post_status'=>'publish','post_title'=>$p[0]]);update_post_meta($id,'monthly_fee',$p[1]);update_post_meta($id,'product_limit',$p[2]);update_post_meta($id,'commission_percent',$p[3]);update_post_meta($id,'featured_enabled',$p[4]);}update_option('tager_v8_plans_seeded',1);}
    private static function seed_promotions(){if(get_option('tager_v8_promotions_seeded'))return;$id=wp_insert_post(['post_type'=>'tager_promotion','post_status'=>'publish','post_title'=>'عرض الجملة الأسبوعي','post_content'=>'خصومات على طلبات الجملة المختارة.']);update_post_meta($id,'start_date',date('Y-m-d'));update_post_meta($id,'end_date',date('Y-m-d',strtotime('+30 days')));update_post_meta($id,'discount_percent',10);update_post_meta($id,'promotion_status','active');update_option('tager_v8_promotions_seeded',1);}
    public static function assets(){
        wp_add_inline_style('tager-style','.v8-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.v8-panel{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px}.v8-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;font-size:12px}.v8-chat{max-height:460px;overflow:auto;padding:12px;background:#f8fafc;border-radius:14px}.v8-msg{max-width:78%;padding:10px 12px;border-radius:14px;margin:8px 0;background:#fff;border:1px solid #e5e7eb}.v8-msg.me{margin-inline-start:auto;background:#ecfdf5}.v8-timeline{border-inline-start:3px solid #cbd5e1;padding-inline-start:16px}.v8-event{position:relative;margin:0 0 18px}.v8-event:before{content:"";position:absolute;inset-inline-start:-23px;top:4px;width:11px;height:11px;border-radius:50%;background:#0f766e}.plan-card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:20px}.plan-card.featured{box-shadow:0 10px 30px rgba(15,118,110,.15);transform:translateY(-3px)}@media(max-width:800px){.v8-grid{grid-template-columns:1fr}}');
    }
    public static function admin_menu(){
        add_menu_page('Tager Commerce Ops','Tager Commerce Ops','manage_options','tager-v8',[__CLASS__,'dashboard'],'dashicons-store',3);
        add_submenu_page('tager-v8','Messages','Messages','manage_options','tager-v8-messages',[__CLASS__,'messages_admin']);
        add_submenu_page('tager-v8','Promotions','Promotions','manage_options','tager-v8-promotions',[__CLASS__,'promotions_admin']);
        add_submenu_page('tager-v8','Vendor Plans','Vendor Plans','manage_options','tager-v8-plans',[__CLASS__,'plans_admin']);
        add_submenu_page('tager-v8','KYC Monitor','KYC Monitor','manage_options','tager-v8-kyc',[__CLASS__,'kyc_admin']);
        add_submenu_page('tager-v8','Bulk Product Import','Bulk Product Import','manage_options','tager-v8-import',[__CLASS__,'import_admin']);
        add_submenu_page('tager-v8','Staff & Roles','Staff & Roles','manage_options','tager-v8-staff',[__CLASS__,'staff_admin']);
    }
    public static function dashboard(){
        $orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1]);$sales=0;$pending=0;foreach($orders as $o){$sales+=(float)get_post_meta($o->ID,'total',true);if((get_post_meta($o->ID,'order_status',true)?:'pending')==='pending')$pending++;}
        $vendors=count(get_users(['role'=>'tager_vendor']));$messages=count(get_posts(['post_type'=>'tager_message','numberposts'=>-1]));$expiring=0;foreach(get_users(['role__in'=>['tager_vendor','tager_vendor_pending']]) as $v){$d=get_user_meta($v->ID,'kyc_expiry',true);if($d&&strtotime($d)<=strtotime('+30 days'))$expiring++;}
        echo '<div class="wrap"><h1>Tager Commerce Operations V8</h1><div class="v8-grid"><div class="v8-panel">Gross Sales<h2>'.esc_html(self::money($sales)).'</h2></div><div class="v8-panel">Pending Orders<h2>'.$pending.'</h2></div><div class="v8-panel">Active Vendors<h2>'.$vendors.'</h2></div><div class="v8-panel">Messages<h2>'.$messages.'</h2></div><div class="v8-panel">KYC expiring ≤30 days<h2>'.$expiring.'</h2></div><div class="v8-panel">Version<h2>8.0.0</h2></div></div><h2>Operations added in V8</h2><ul><li>Vendor plans and plan-based limits</li><li>Marketplace messaging</li><li>Shipment timeline tracking</li><li>Promotions center</li><li>KYC expiry control</li><li>Bulk CSV product import</li><li>Operational staff roles</li></ul></div>';
    }
    public static function messages_page(){if(!is_user_logged_in())return '<div class="notice">Login required</div>';$uid=get_current_user_id();$peer=(int)($_GET['with']??0);$msgs=get_posts(['post_type'=>'tager_message','numberposts'=>200,'orderby'=>'date','order'=>'ASC','meta_query'=>[['key'=>'participants','value'=>'|'.$uid.'|','compare'=>'LIKE']]]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('الرسائل','Messages'));?></h1></section><div class="v8-chat"><?php foreach($msgs as $m){$to=(int)get_post_meta($m->ID,'to_user',true);$from=(int)$m->post_author;if($peer&&$peer!==$to&&$peer!==$from)continue;?><div class="v8-msg <?php echo $from===$uid?'me':'';?>"><b><?php echo esc_html(get_the_author_meta('display_name',$from));?></b><p><?php echo esc_html($m->post_content);?></p><small><?php echo esc_html($m->post_date);?></small></div><?php }?></div><form class="form-card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v8_message_send"><?php echo self::nonce('tager_v8_message_send');?><label><?php echo esc_html(self::t('رقم المستخدم المستلم','Recipient user ID'));?><input type="number" name="to_user" value="<?php echo esc_attr($peer);?>" required></label><label><?php echo esc_html(self::t('الرسالة','Message'));?><textarea name="message" required></textarea></label><button class="btn primary"><?php echo esc_html(self::t('إرسال','Send'));?></button></form><?php return ob_get_clean();}
    public static function message_send(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v8_message_send');$from=get_current_user_id();$to=(int)($_POST['to_user']??0);if(!$to||!get_user_by('id',$to))wp_die('Invalid recipient');$id=wp_insert_post(['post_type'=>'tager_message','post_status'=>'publish','post_author'=>$from,'post_title'=>'Conversation '.$from.'-'.$to,'post_content'=>sanitize_textarea_field($_POST['message']??'')]);update_post_meta($id,'to_user',$to);update_post_meta($id,'participants','|'.$from.'||'.$to.'|');wp_safe_redirect(add_query_arg('with',$to,self::url('messages')));exit;}
    public static function tracking_page(){if(!is_user_logged_in())return '<div class="notice">Login required</div>';$oid=(int)($_GET['order']??0);$orders=get_posts(['post_type'=>'tager_order','author'=>get_current_user_id(),'numberposts'=>100]);if(!$oid&&$orders)$oid=$orders[0]->ID;$o=get_post($oid);if(!$o||((int)$o->post_author!==get_current_user_id()&&!current_user_can('manage_options')))return '<div class="notice">Order not found</div>';$events=get_posts(['post_type'=>'tager_shipment_event','numberposts'=>100,'orderby'=>'date','order'=>'ASC','meta_key'=>'order_id','meta_value'=>$oid]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('تتبع الطلب','Track order'));?> #<?php echo $oid;?></h1></section><div class="v8-timeline"><?php if(!$events)echo '<div class="v8-event"><b>Order created</b><p>Waiting for shipment updates.</p></div>';foreach($events as $e){?><div class="v8-event"><b><?php echo esc_html(get_post_meta($e->ID,'status',true));?></b><p><?php echo esc_html($e->post_content);?></p><small><?php echo esc_html($e->post_date);?></small></div><?php }?></div><?php return ob_get_clean();}
    public static function tracking_update(){if(!current_user_can('manage_options')&&!current_user_can('tager_vendor'))wp_die('No permission');$oid=(int)($_POST['order_id']??0);check_admin_referer('tager_v8_tracking_'.$oid);$id=wp_insert_post(['post_type'=>'tager_shipment_event','post_status'=>'publish','post_author'=>get_current_user_id(),'post_title'=>'Shipment update '.$oid,'post_content'=>sanitize_textarea_field($_POST['note']??'')]);update_post_meta($id,'order_id',$oid);update_post_meta($id,'status',sanitize_text_field($_POST['status']??'Updated'));update_post_meta($id,'tracking_number',sanitize_text_field($_POST['tracking_number']??''));wp_safe_redirect(wp_get_referer()?:admin_url());exit;}
    public static function plans_page(){$plans=get_posts(['post_type'=>'tager_vendor_plan','numberposts'=>20,'orderby'=>'meta_value_num','meta_key'=>'monthly_fee','order'=>'ASC']);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('باقات الموردين','Vendor plans'));?></h1></section><div class="v8-grid"><?php foreach($plans as $i=>$p){?><div class="plan-card <?php echo $i===1?'featured':'';?>"><h2><?php echo esc_html($p->post_title);?></h2><h3><?php echo esc_html(self::money(get_post_meta($p->ID,'monthly_fee',true)));?> / month</h3><p>Product limit: <?php echo esc_html(get_post_meta($p->ID,'product_limit',true));?></p><p>Commission: <?php echo esc_html(get_post_meta($p->ID,'commission_percent',true));?>%</p><p>Featured listings: <?php echo get_post_meta($p->ID,'featured_enabled',true)?'Yes':'No';?></p></div><?php }?></div><?php return ob_get_clean();}
    public static function promotions_page(){$rows=get_posts(['post_type'=>'tager_promotion','numberposts'=>50]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('العروض','Promotions'));?></h1></section><div class="v8-grid"><?php foreach($rows as $p){if(get_post_meta($p->ID,'promotion_status',true)!=='active')continue;?><div class="v8-panel"><span class="v8-badge"><?php echo esc_html(get_post_meta($p->ID,'discount_percent',true));?>% OFF</span><h2><?php echo esc_html($p->post_title);?></h2><p><?php echo esc_html($p->post_content);?></p><small><?php echo esc_html(get_post_meta($p->ID,'start_date',true));?> → <?php echo esc_html(get_post_meta($p->ID,'end_date',true));?></small></div><?php }?></div><?php return ob_get_clean();}
    public static function messages_admin(){if(!current_user_can('manage_options'))return;$rows=get_posts(['post_type'=>'tager_message','numberposts'=>200,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>Marketplace Messages</h1><table class="widefat striped"><tr><th>#</th><th>From</th><th>To</th><th>Message</th><th>Date</th></tr>';foreach($rows as $m)echo '<tr><td>'.$m->ID.'</td><td>'.esc_html(get_the_author_meta('display_name',$m->post_author)).'</td><td>'.esc_html(get_the_author_meta('display_name',(int)get_post_meta($m->ID,'to_user',true))).'</td><td>'.esc_html(wp_trim_words($m->post_content,20)).'</td><td>'.esc_html($m->post_date).'</td></tr>';echo '</table></div>';}
    public static function promotions_admin(){if(!current_user_can('manage_options'))return;$rows=get_posts(['post_type'=>'tager_promotion','numberposts'=>100]);echo '<div class="wrap"><h1>Promotions</h1><table class="widefat striped"><tr><th>Name</th><th>Discount</th><th>Dates</th><th>Status</th></tr>';foreach($rows as $p)echo '<tr><td>'.esc_html($p->post_title).'</td><td>'.esc_html(get_post_meta($p->ID,'discount_percent',true)).'%</td><td>'.esc_html(get_post_meta($p->ID,'start_date',true)).' → '.esc_html(get_post_meta($p->ID,'end_date',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'promotion_status',true)).'</td></tr>';echo '</table><h2>Add promotion</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v8_promotion_save">'.self::nonce('tager_v8_promotion_save').'<p><input name="name" placeholder="Promotion name" required> <input type="number" name="discount" min="0" max="100" placeholder="Discount %" required></p><p><input type="date" name="start" required> <input type="date" name="end" required></p><p><textarea name="details" placeholder="Details"></textarea></p><button class="button button-primary">Save</button></form></div>';}
    public static function promotion_save(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_v8_promotion_save');$id=wp_insert_post(['post_type'=>'tager_promotion','post_status'=>'publish','post_title'=>sanitize_text_field($_POST['name']??'Promotion'),'post_content'=>sanitize_textarea_field($_POST['details']??'')]);update_post_meta($id,'discount_percent',max(0,min(100,(float)($_POST['discount']??0))));update_post_meta($id,'start_date',sanitize_text_field($_POST['start']??''));update_post_meta($id,'end_date',sanitize_text_field($_POST['end']??''));update_post_meta($id,'promotion_status','active');wp_safe_redirect(admin_url('admin.php?page=tager-v8-promotions'));exit;}
    public static function promotion_status(){}
    public static function plans_admin(){if(!current_user_can('manage_options'))return;$plans=get_posts(['post_type'=>'tager_vendor_plan','numberposts'=>50]);echo '<div class="wrap"><h1>Vendor Plans</h1><table class="widefat striped"><tr><th>Plan</th><th>Monthly fee</th><th>Product limit</th><th>Commission</th><th>Featured</th></tr>';foreach($plans as $p)echo '<tr><td>'.esc_html($p->post_title).'</td><td>'.esc_html(self::money(get_post_meta($p->ID,'monthly_fee',true))).'</td><td>'.esc_html(get_post_meta($p->ID,'product_limit',true)).'</td><td>'.esc_html(get_post_meta($p->ID,'commission_percent',true)).'%</td><td>'.(get_post_meta($p->ID,'featured_enabled',true)?'Yes':'No').'</td></tr>';echo '</table><h2>Assign plan to vendor</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v8_plan_assign">'.self::nonce('tager_v8_plan_assign').'<select name="vendor">';foreach(get_users(['role'=>'tager_vendor']) as $v)echo '<option value="'.$v->ID.'">'.esc_html($v->display_name).'</option>';echo '</select> <select name="plan">';foreach($plans as $p)echo '<option value="'.$p->ID.'">'.esc_html($p->post_title).'</option>';echo '</select> <button class="button button-primary">Assign</button></form></div>';}
    public static function plan_assign(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_v8_plan_assign');$v=(int)($_POST['vendor']??0);$p=(int)($_POST['plan']??0);update_user_meta($v,'vendor_plan_id',$p);update_user_meta($v,'vendor_plan_started',current_time('mysql'));wp_safe_redirect(admin_url('admin.php?page=tager-v8-plans'));exit;}
    public static function kyc_admin(){if(!current_user_can('manage_options'))return;$vendors=get_users(['role__in'=>['tager_vendor','tager_vendor_pending']]);echo '<div class="wrap"><h1>Vendor KYC Monitor</h1><table class="widefat striped"><tr><th>Vendor</th><th>Status</th><th>Expiry</th><th>Document note</th><th>Update</th></tr>';foreach($vendors as $v){echo '<tr><td>'.esc_html($v->display_name).'</td><td>'.esc_html(get_user_meta($v->ID,'vendor_status',true)).'</td><td>'.esc_html(get_user_meta($v->ID,'kyc_expiry',true)?:'-').'</td><td>'.esc_html(get_user_meta($v->ID,'kyc_note',true)?:'-').'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v8_kyc_update"><input type="hidden" name="vendor" value="'.$v->ID.'">'.self::nonce('tager_v8_kyc_'.$v->ID).'<input type="date" name="expiry" value="'.esc_attr(get_user_meta($v->ID,'kyc_expiry',true)).'"> <input name="note" placeholder="Note" value="'.esc_attr(get_user_meta($v->ID,'kyc_note',true)).'"> <button class="button">Save</button></form></td></tr>';}echo '</table></div>';}
    public static function kyc_update(){if(!current_user_can('manage_options'))wp_die('No');$v=(int)($_POST['vendor']??0);check_admin_referer('tager_v8_kyc_'.$v);update_user_meta($v,'kyc_expiry',sanitize_text_field($_POST['expiry']??''));update_user_meta($v,'kyc_note',sanitize_text_field($_POST['note']??''));wp_safe_redirect(admin_url('admin.php?page=tager-v8-kyc'));exit;}
    public static function import_admin(){if(!current_user_can('manage_options'))return;echo '<div class="wrap"><h1>Bulk Product Import</h1><p>CSV columns: name_ar,name_en,description,retail_price,wholesale_price,bulk_price,wholesale_min,bulk_min,stock,max_qty,vendor_id</p><form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v8_bulk_import">'.self::nonce('tager_v8_bulk_import').'<input type="file" name="csv" accept=".csv" required> <button class="button button-primary">Import CSV</button></form></div>';}
    public static function bulk_import(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_v8_bulk_import');if(empty($_FILES['csv']['tmp_name']))wp_die('Missing file');$h=fopen($_FILES['csv']['tmp_name'],'r');$head=fgetcsv($h);$count=0;while(($r=fgetcsv($h))!==false){$d=array_combine($head,$r);if(!$d||empty($d['name_ar']))continue;$id=wp_insert_post(['post_type'=>'tager_product','post_status'=>'pending','post_author'=>(int)($d['vendor_id']??get_current_user_id()),'post_title'=>sanitize_text_field($d['name_ar']),'post_content'=>sanitize_textarea_field($d['description']??'')]);foreach(['name_en','retail_price','wholesale_price','bulk_price','wholesale_min','bulk_min','stock','max_qty'] as $k)if(isset($d[$k]))update_post_meta($id,$k,sanitize_text_field($d[$k]));$count++;}fclose($h);set_transient('tager_v8_import_notice','Imported '.$count.' products for review',60);wp_safe_redirect(admin_url('admin.php?page=tager-v8-import'));exit;}
    public static function staff_admin(){if(!current_user_can('manage_options'))return;$roles=['tager_support_agent'=>'Support Agent','tager_catalog_manager'=>'Catalog Manager','tager_finance_agent'=>'Finance Agent'];echo '<div class="wrap"><h1>Staff & Roles</h1><table class="widefat striped"><tr><th>User</th><th>Email</th><th>Role</th></tr>';foreach(get_users(['role__in'=>array_keys($roles)]) as $u)echo '<tr><td>'.esc_html($u->display_name).'</td><td>'.esc_html($u->user_email).'</td><td>'.esc_html(implode(', ',$u->roles)).'</td></tr>';echo '</table><h2>Create staff user</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v8_staff_create">'.self::nonce('tager_v8_staff_create').'<p><input name="username" placeholder="Username" required> <input type="email" name="email" placeholder="Email" required></p><p><input type="password" name="password" placeholder="Password" required> <select name="role">';foreach($roles as $k=>$n)echo '<option value="'.$k.'">'.esc_html($n).'</option>';echo '</select></p><button class="button button-primary">Create user</button></form></div>';}
    public static function staff_create(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_v8_staff_create');$role=sanitize_key($_POST['role']??'');if(!in_array($role,['tager_support_agent','tager_catalog_manager','tager_finance_agent'],true))wp_die('Invalid role');$id=wp_create_user(sanitize_user($_POST['username']??''),$_POST['password']??'',sanitize_email($_POST['email']??''));if(is_wp_error($id))wp_die($id->get_error_message());(new WP_User($id))->set_role($role);wp_safe_redirect(admin_url('admin.php?page=tager-v8-staff'));exit;}
}
Tager_V8_Commerce_Ops::init();
