<?php
/**
 * Plugin Name: Tager Enterprise Suite V7
 * Description: RFQ, product comparison, vendor directory, invoices, returns, shipping zones, product detail pages, analytics and CSV exports.
 * Version: 7.0.0
 */
if (!defined('ABSPATH')) exit;

class Tager_V7_Enterprise_Suite {
    const V='7.0.0';
    public static function init(){
        add_action('init',[__CLASS__,'register'],50);
        add_action('init',[__CLASS__,'bootstrap'],130);
        add_action('wp_enqueue_scripts',[__CLASS__,'assets'],60);
        add_filter('the_content',[__CLASS__,'product_detail']);
        add_action('admin_menu',[__CLASS__,'admin_menu'],40);
        foreach(['rfq_submit','rfq_status','return_submit','return_status','shipping_save'] as $a){
            add_action('admin_post_tager_'.$a,[__CLASS__,$a]);
            if(in_array($a,['rfq_submit','return_submit'],true)) add_action('admin_post_nopriv_tager_'.$a,[__CLASS__,$a]);
        }
        add_action('admin_post_tager_export_orders',[__CLASS__,'export_orders']);
        add_action('admin_post_tager_export_vendors',[__CLASS__,'export_vendors']);
        add_shortcode('tager_v7_vendor_directory',[__CLASS__,'vendor_directory']);
        add_shortcode('tager_v7_rfq',[__CLASS__,'rfq_page']);
        add_shortcode('tager_v7_returns',[__CLASS__,'returns_page']);
        add_shortcode('tager_v7_invoices',[__CLASS__,'invoices_page']);
        add_shortcode('tager_v7_compare',[__CLASS__,'compare_page']);
    }
    public static function register(){
        register_post_type('tager_rfq',['labels'=>['name'=>'RFQ Requests','singular_name'=>'RFQ Request'],'public'=>false,'show_ui'=>true,'supports'=>['title','editor','author'],'menu_icon'=>'dashicons-media-spreadsheet']);
        register_post_type('tager_return',['labels'=>['name'=>'Returns','singular_name'=>'Return Request'],'public'=>false,'show_ui'=>true,'supports'=>['title','editor','author'],'menu_icon'=>'dashicons-undo']);
        register_post_type('tager_shipping_zone',['labels'=>['name'=>'Shipping Zones','singular_name'=>'Shipping Zone'],'public'=>false,'show_ui'=>false,'supports'=>['title']]);
    }
    public static function bootstrap(){
        if(get_option('tager_v7_bootstrap')===self::V)return;
        $pages=get_option('tager_pages',[]);
        $extra=[
            'vendors'=>['دليل الموردين','[tager_v7_vendor_directory]'],
            'request-quote'=>['طلب عرض سعر','[tager_v7_rfq]'],
            'returns'=>['المرتجعات','[tager_v7_returns]'],
            'invoices'=>['الفواتير','[tager_v7_invoices]'],
            'compare'=>['مقارنة المنتجات','[tager_v7_compare]'],
        ];
        foreach($extra as $slug=>$d){$p=get_page_by_path($slug);$pages[$slug]=$p?$p->ID:wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_name'=>$slug,'post_title'=>$d[0],'post_content'=>$d[1]]);}        
        update_option('tager_pages',$pages);
        if(!get_option('tager_v7_settings'))update_option('tager_v7_settings',['return_days'=>14,'rfq_enabled'=>1,'compare_enabled'=>1,'invoice_prefix'=>'TAG','shipping_default'=>50]);
        self::seed_shipping();
        update_option('tager_v7_bootstrap',self::V);
    }
    private static function seed_shipping(){if(get_option('tager_v7_shipping_seeded'))return;$zones=[['القاهرة الكبرى',40,1],['الدلتا',55,2],['الصعيد',75,4],['المناطق النائية',100,6]];foreach($zones as $z){$id=wp_insert_post(['post_type'=>'tager_shipping_zone','post_status'=>'publish','post_title'=>$z[0]]);update_post_meta($id,'fee',$z[1]);update_post_meta($id,'days',$z[2]);}update_option('tager_v7_shipping_seeded',1);}
    private static function lang(){return (isset($_GET['lang'])&&$_GET['lang']==='en')?'en':'ar';}
    private static function t($ar,$en){return self::lang()==='en'?$en:$ar;}
    private static function pages(){return get_option('tager_pages',[]);}
    private static function url($slug){$p=self::pages();return !empty($p[$slug])?get_permalink($p[$slug]):home_url('/'.$slug.'/');}
    private static function money($v){return number_format((float)$v,2).' EGP';}
    private static function nonce($a){return wp_nonce_field($a,'_wpnonce',true,false);}
    public static function assets(){
        wp_add_inline_style('tager-style','.v7-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px;margin:20px 0}.v7-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px}.v7-card b{font-size:28px;display:block;margin-top:8px}.v7-detail{display:grid;grid-template-columns:1.1fr 1fr;gap:30px;align-items:start}.v7-gallery{background:#f8fafc;border-radius:20px;padding:20px;min-height:350px;display:grid;place-items:center}.v7-gallery img{max-width:100%;height:auto}.v7-table{width:100%;border-collapse:collapse}.v7-table th,.v7-table td{padding:12px;border-bottom:1px solid #e5e7eb;text-align:start}.vendor-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.vendor-box{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:20px}.rating{color:#f59e0b}.compare-bar{position:sticky;bottom:12px;background:#0f172a;color:#fff;padding:12px;border-radius:14px;display:flex;justify-content:space-between;align-items:center;z-index:20}@media(max-width:800px){.v7-detail,.vendor-grid,.v7-kpis{grid-template-columns:1fr}}');
        wp_add_inline_script('tager-js',"window.tagerCompare=function(id,name){let c=[];try{c=JSON.parse(localStorage.getItem('tager_compare')||'[]')}catch(e){};if(!c.find(x=>x.id===id))c.push({id:id,name:name});c=c.slice(-4);localStorage.setItem('tager_compare',JSON.stringify(c));alert('Added to comparison');};window.tagerRenderCompare=function(){let el=document.getElementById('tager-compare');if(!el)return;let c=[];try{c=JSON.parse(localStorage.getItem('tager_compare')||'[]')}catch(e){};if(!c.length){el.innerHTML='<div class=empty-state>No products selected</div>';return;}document.getElementById('compare_json').value=JSON.stringify(c);let h='<table class=v7-table><tr><th>Product</th><th>ID</th></tr>';c.forEach(x=>h+='<tr><td>'+x.name+'</td><td>'+x.id+'</td></tr>');el.innerHTML=h+'</table>';};",'after');
    }
    public static function product_detail($content){
        if(!is_singular('tager_product')||!in_the_loop()||!is_main_query())return $content;
        $id=get_the_ID();$name=self::lang()==='en'?(get_post_meta($id,'name_en',true)?:get_the_title()):get_the_title();$r=(float)get_post_meta($id,'retail_price',true);$w=(float)get_post_meta($id,'wholesale_price',true);$b=(float)get_post_meta($id,'bulk_price',true);$wm=(int)get_post_meta($id,'wholesale_min',true);$bm=(int)get_post_meta($id,'bulk_min',true);$stock=(int)get_post_meta($id,'stock',true);$max=(int)(get_post_meta($id,'max_qty',true)?:$stock?:9999);$vendor=(int)get_post_field('post_author',$id);$store=get_user_meta($vendor,'store_name',true)?:get_the_author_meta('display_name',$vendor);$rating=(float)(get_user_meta($vendor,'vendor_score_rating',true)?:5);
        ob_start();?><section class="v7-detail"><div class="v7-gallery"><?php echo has_post_thumbnail()?get_the_post_thumbnail($id,'large'):'<span style="font-size:90px">📦</span>';?></div><div><small><?php echo esc_html($store);?> · <span class="rating">★ <?php echo esc_html($rating);?></span></small><h1><?php echo esc_html($name);?></h1><p><?php echo wp_kses_post($content);?></p><div class="v7-card"><h3><?php echo esc_html(self::t('شرائح السعر','Pricing tiers'));?></h3><table class="v7-table"><tr><td><?php echo esc_html(self::t('قطاعي','Retail'));?></td><td><?php echo esc_html(self::money($r));?></td><td>1+</td></tr><tr><td><?php echo esc_html(self::t('جملة','Wholesale'));?></td><td><?php echo esc_html(self::money($w));?></td><td><?php echo esc_html($wm);?>+</td></tr><tr><td><?php echo esc_html(self::t('جملة الجملة','Bulk wholesale'));?></td><td><?php echo esc_html(self::money($b));?></td><td><?php echo esc_html($bm);?>+</td></tr></table></div><p><?php echo esc_html(self::t('المخزون المتاح','Available stock'));?>: <b><?php echo esc_html($stock);?></b></p><div class="qty-row"><input id="qty-<?php echo $id;?>" type="number" min="1" max="<?php echo esc_attr($max);?>" value="1"><button class="btn primary" onclick="tagerAdd(<?php echo $id;?>,'<?php echo esc_js($name);?>')"><?php echo esc_html(self::t('أضف للسلة','Add to cart'));?></button><button class="btn secondary" onclick="tagerCompare(<?php echo $id;?>,'<?php echo esc_js($name);?>')"><?php echo esc_html(self::t('مقارنة','Compare'));?></button></div><p><a class="btn secondary" href="<?php echo esc_url(add_query_arg('product',$id,self::url('request-quote')));?>"><?php echo esc_html(self::t('اطلب عرض سعر خاص','Request custom quote'));?></a></p></div></section><?php return ob_get_clean();
    }
    public static function vendor_directory(){
        $vendors=get_users(['role'=>'tager_vendor']);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('دليل الموردين','Vendor directory'));?></h1></section><div class="vendor-grid"><?php foreach($vendors as $v){$store=get_user_meta($v->ID,'store_name',true)?:$v->display_name;$rating=get_user_meta($v->ID,'vendor_score_rating',true)?:5;$risk=get_user_meta($v->ID,'vendor_risk_level',true)?:'low';$products=count(get_posts(['post_type'=>'tager_product','author'=>$v->ID,'post_status'=>'publish','numberposts'=>-1]));?><article class="vendor-box"><h3><?php echo esc_html($store);?></h3><div class="rating">★★★★★ <?php echo esc_html($rating);?>/5</div><p><?php echo esc_html(self::t('عدد المنتجات','Products'));?>: <?php echo esc_html($products);?></p><p><?php echo esc_html(self::t('مستوى المخاطر','Risk level'));?>: <?php echo esc_html($risk);?></p><a class="btn primary" href="<?php echo esc_url(add_query_arg('vendor',$v->ID,self::url('vendor-store')));?>"><?php echo esc_html(self::t('زيارة المتجر','Visit store'));?></a></article><?php }?></div><?php return ob_get_clean();
    }
    public static function rfq_page(){
        if(!is_user_logged_in())return '<div class="notice">'.esc_html(self::t('سجل الدخول لإرسال طلب عرض سعر','Sign in to submit an RFQ')).'</div>';
        $pid=(int)($_GET['product']??0);$mine=get_posts(['post_type'=>'tager_rfq','author'=>get_current_user_id(),'numberposts'=>50]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('طلب عرض سعر','Request for quotation'));?></h1></section><form class="auth-card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_rfq_submit"><?php echo self::nonce('tager_rfq_submit');?><label><?php echo esc_html(self::t('المنتج','Product'));?><select name="product" required><?php foreach(get_posts(['post_type'=>'tager_product','post_status'=>'publish','numberposts'=>200]) as $p)echo '<option value="'.$p->ID.'" '.selected($pid,$p->ID,false).'>'.esc_html($p->post_title).'</option>';?></select></label><label><?php echo esc_html(self::t('الكمية المطلوبة','Required quantity'));?><input type="number" name="qty" min="1" required></label><label><?php echo esc_html(self::t('السعر المستهدف','Target price'));?><input type="number" step="0.01" name="target_price"></label><label><?php echo esc_html(self::t('موعد التوريد','Delivery date'));?><input type="date" name="delivery_date"></label><label><?php echo esc_html(self::t('ملاحظات','Notes'));?><textarea name="notes"></textarea></label><button class="btn primary"><?php echo esc_html(self::t('إرسال الطلب','Submit RFQ'));?></button></form><h2><?php echo esc_html(self::t('طلباتي','My requests'));?></h2><table class="v7-table"><tr><th>#</th><th><?php echo esc_html(self::t('المنتج','Product'));?></th><th><?php echo esc_html(self::t('الكمية','Qty'));?></th><th><?php echo esc_html(self::t('الحالة','Status'));?></th><th><?php echo esc_html(self::t('عرض المورد','Vendor offer'));?></th></tr><?php foreach($mine as $r){$product=(int)get_post_meta($r->ID,'product_id',true);echo '<tr><td>'.$r->ID.'</td><td>'.esc_html(get_the_title($product)).'</td><td>'.esc_html(get_post_meta($r->ID,'qty',true)).'</td><td>'.esc_html(get_post_meta($r->ID,'rfq_status',true)?:'pending').'</td><td>'.esc_html(get_post_meta($r->ID,'vendor_offer',true)?:'-').'</td></tr>';}?></table><?php return ob_get_clean();
    }
    public static function rfq_submit(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_rfq_submit');$pid=(int)($_POST['product']??0);$id=wp_insert_post(['post_type'=>'tager_rfq','post_status'=>'publish','post_author'=>get_current_user_id(),'post_title'=>'RFQ '.current_time('YmdHis'),'post_content'=>sanitize_textarea_field($_POST['notes']??'')]);foreach(['product_id'=>$pid,'qty'=>max(1,(int)($_POST['qty']??1)),'target_price'=>(float)($_POST['target_price']??0),'delivery_date'=>sanitize_text_field($_POST['delivery_date']??''),'rfq_status'=>'pending'] as $k=>$v)update_post_meta($id,$k,$v);wp_safe_redirect(self::url('request-quote'));exit;}
    public static function returns_page(){if(!is_user_logged_in())return '<div class="notice">Login required</div>';$uid=get_current_user_id();$orders=get_posts(['post_type'=>'tager_order','author'=>$uid,'numberposts'=>100]);$mine=get_posts(['post_type'=>'tager_return','author'=>$uid,'numberposts'=>50]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('طلبات الاسترجاع','Return requests'));?></h1></section><form class="auth-card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_return_submit"><?php echo self::nonce('tager_return_submit');?><label><?php echo esc_html(self::t('رقم الطلب','Order'));?><select name="order" required><?php foreach($orders as $o)echo '<option value="'.$o->ID.'">#'.$o->ID.' - '.esc_html(get_post_meta($o->ID,'total',true)).' EGP</option>';?></select></label><label><?php echo esc_html(self::t('السبب','Reason'));?><select name="reason"><option>Damaged</option><option>Wrong item</option><option>Quality issue</option><option>Other</option></select></label><label><?php echo esc_html(self::t('التفاصيل','Details'));?><textarea name="details" required></textarea></label><button class="btn primary"><?php echo esc_html(self::t('إرسال طلب الاسترجاع','Submit return'));?></button></form><h2><?php echo esc_html(self::t('الطلبات السابقة','Previous requests'));?></h2><table class="v7-table"><tr><th>#</th><th><?php echo esc_html(self::t('الطلب','Order'));?></th><th><?php echo esc_html(self::t('الحالة','Status'));?></th><th><?php echo esc_html(self::t('قرار الإدارة','Admin note'));?></th></tr><?php foreach($mine as $r)echo '<tr><td>'.$r->ID.'</td><td>#'.esc_html(get_post_meta($r->ID,'order_id',true)).'</td><td>'.esc_html(get_post_meta($r->ID,'return_status',true)?:'pending').'</td><td>'.esc_html(get_post_meta($r->ID,'admin_note',true)?:'-').'</td></tr>';?></table><?php return ob_get_clean();}
    public static function return_submit(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_return_submit');$oid=(int)($_POST['order']??0);$o=get_post($oid);if(!$o||((int)$o->post_author!==get_current_user_id()&&!current_user_can('manage_options')))wp_die('Invalid order');$id=wp_insert_post(['post_type'=>'tager_return','post_status'=>'publish','post_author'=>get_current_user_id(),'post_title'=>'Return for order #'.$oid,'post_content'=>sanitize_textarea_field($_POST['details']??'')]);update_post_meta($id,'order_id',$oid);update_post_meta($id,'reason',sanitize_text_field($_POST['reason']??'Other'));update_post_meta($id,'return_status','pending');wp_safe_redirect(self::url('returns'));exit;}
    public static function invoices_page(){if(!is_user_logged_in())return '<div class="notice">Login required</div>';$orders=get_posts(['post_type'=>'tager_order','author'=>get_current_user_id(),'numberposts'=>100]);$s=get_option('tager_v7_settings',[]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('الفواتير','Invoices'));?></h1></section><table class="v7-table"><tr><th><?php echo esc_html(self::t('الفاتورة','Invoice'));?></th><th><?php echo esc_html(self::t('التاريخ','Date'));?></th><th><?php echo esc_html(self::t('الإجمالي','Total'));?></th><th><?php echo esc_html(self::t('الحالة','Status'));?></th></tr><?php foreach($orders as $o){$inv=($s['invoice_prefix']??'TAG').'-'.str_pad($o->ID,6,'0',STR_PAD_LEFT);echo '<tr><td>'.esc_html($inv).'</td><td>'.esc_html(get_the_date('Y-m-d',$o)).'</td><td>'.esc_html(get_post_meta($o->ID,'total',true)).' EGP</td><td>'.esc_html(get_post_meta($o->ID,'order_status',true)).'</td></tr>';}?></table><?php return ob_get_clean();}
    public static function compare_page(){ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('مقارنة المنتجات','Compare products'));?></h1></section><input type="hidden" id="compare_json"><div id="tager-compare"></div><script>document.addEventListener('DOMContentLoaded',tagerRenderCompare)</script><?php return ob_get_clean();}
    public static function admin_menu(){add_menu_page('Tager Enterprise','Tager Enterprise','manage_options','tager-v7',[__CLASS__,'analytics'],'dashicons-chart-area',4);add_submenu_page('tager-v7','RFQ Management','RFQ Management','manage_options','tager-v7-rfq',[__CLASS__,'rfq_admin']);add_submenu_page('tager-v7','Returns','Returns','manage_options','tager-v7-returns',[__CLASS__,'returns_admin']);add_submenu_page('tager-v7','Shipping Zones','Shipping Zones','manage_options','tager-v7-shipping',[__CLASS__,'shipping_admin']);}
    public static function analytics(){if(!current_user_can('manage_options'))return;$orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1]);$sales=0;foreach($orders as $o)$sales+=(float)get_post_meta($o->ID,'total',true);$vendors=count(get_users(['role'=>'tager_vendor']));$customers=count(get_users(['role'=>'tager_customer']));$products=count(get_posts(['post_type'=>'tager_product','post_status'=>'publish','numberposts'=>-1]));?><div class="wrap"><h1>Tager Enterprise Analytics</h1><div class="v7-kpis"><div class="v7-card">Total Sales<b><?php echo esc_html(self::money($sales));?></b></div><div class="v7-card">Orders<b><?php echo count($orders);?></b></div><div class="v7-card">Vendors<b><?php echo $vendors;?></b></div><div class="v7-card">Products<b><?php echo $products;?></b></div></div><div class="v7-card"><h2>Data exports</h2><p><a class="button button-primary" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=tager_export_orders'),'tager_export_orders'));?>">Export orders CSV</a> <a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=tager_export_vendors'),'tager_export_vendors'));?>">Export vendors CSV</a></p><p>Customers: <b><?php echo $customers;?></b></p></div></div><?php }
    public static function rfq_admin(){if(!current_user_can('manage_options'))return;$rows=get_posts(['post_type'=>'tager_rfq','numberposts'=>200,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>RFQ Management</h1><table class="widefat striped"><tr><th>#</th><th>Customer</th><th>Product</th><th>Qty</th><th>Target</th><th>Status / Offer</th></tr>';foreach($rows as $r){$pid=(int)get_post_meta($r->ID,'product_id',true);echo '<tr><td>'.$r->ID.'</td><td>'.esc_html(get_the_author_meta('display_name',$r->post_author)).'</td><td>'.esc_html(get_the_title($pid)).'</td><td>'.esc_html(get_post_meta($r->ID,'qty',true)).'</td><td>'.esc_html(get_post_meta($r->ID,'target_price',true)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_rfq_status"><input type="hidden" name="rfq" value="'.$r->ID.'">'.self::nonce('tager_rfq_'.$r->ID).'<select name="status"><option>pending</option><option>quoted</option><option>accepted</option><option>rejected</option></select><input name="offer" type="number" step="0.01" placeholder="Vendor offer" value="'.esc_attr(get_post_meta($r->ID,'vendor_offer',true)).'"><button class="button">Save</button></form></td></tr>';}echo '</table></div>';}
    public static function rfq_status(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_POST['rfq']??0);check_admin_referer('tager_rfq_'.$id);update_post_meta($id,'rfq_status',sanitize_key($_POST['status']??'pending'));update_post_meta($id,'vendor_offer',(float)($_POST['offer']??0));wp_safe_redirect(admin_url('admin.php?page=tager-v7-rfq'));exit;}
    public static function returns_admin(){if(!current_user_can('manage_options'))return;$rows=get_posts(['post_type'=>'tager_return','numberposts'=>200,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>Return Requests</h1><table class="widefat striped"><tr><th>#</th><th>Customer</th><th>Order</th><th>Reason</th><th>Status / Note</th></tr>';foreach($rows as $r)echo '<tr><td>'.$r->ID.'</td><td>'.esc_html(get_the_author_meta('display_name',$r->post_author)).'</td><td>#'.esc_html(get_post_meta($r->ID,'order_id',true)).'</td><td>'.esc_html(get_post_meta($r->ID,'reason',true)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_return_status"><input type="hidden" name="return" value="'.$r->ID.'">'.self::nonce('tager_return_'.$r->ID).'<select name="status"><option>pending</option><option>approved</option><option>rejected</option><option>refunded</option></select><input name="note" placeholder="Admin note" value="'.esc_attr(get_post_meta($r->ID,'admin_note',true)).'"><button class="button">Save</button></form></td></tr>';echo '</table></div>';}
    public static function return_status(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_POST['return']??0);check_admin_referer('tager_return_'.$id);update_post_meta($id,'return_status',sanitize_key($_POST['status']??'pending'));update_post_meta($id,'admin_note',sanitize_text_field($_POST['note']??''));wp_safe_redirect(admin_url('admin.php?page=tager-v7-returns'));exit;}
    public static function shipping_admin(){if(!current_user_can('manage_options'))return;$zones=get_posts(['post_type'=>'tager_shipping_zone','numberposts'=>100]);echo '<div class="wrap"><h1>Shipping Zones</h1><table class="widefat striped"><tr><th>Zone</th><th>Fee</th><th>Delivery days</th></tr>';foreach($zones as $z)echo '<tr><td>'.esc_html($z->post_title).'</td><td>'.esc_html(get_post_meta($z->ID,'fee',true)).' EGP</td><td>'.esc_html(get_post_meta($z->ID,'days',true)).'</td></tr>';echo '</table><h2>Add zone</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_shipping_save">'.self::nonce('tager_shipping_save').'<input name="zone" placeholder="Zone name" required> <input type="number" name="fee" placeholder="Fee" required> <input type="number" name="days" placeholder="Days" required> <button class="button button-primary">Add</button></form></div>';}
    public static function shipping_save(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_shipping_save');$id=wp_insert_post(['post_type'=>'tager_shipping_zone','post_status'=>'publish','post_title'=>sanitize_text_field($_POST['zone']??'Zone')]);update_post_meta($id,'fee',(float)($_POST['fee']??0));update_post_meta($id,'days',max(1,(int)($_POST['days']??1)));wp_safe_redirect(admin_url('admin.php?page=tager-v7-shipping'));exit;}
    public static function export_orders(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_export_orders');header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=tager-orders.csv');$out=fopen('php://output','w');fputcsv($out,['Order ID','Customer','Total','Status','Date']);foreach(get_posts(['post_type'=>'tager_order','numberposts'=>-1]) as $o)fputcsv($out,[$o->ID,get_post_meta($o->ID,'customer_name',true),get_post_meta($o->ID,'total',true),get_post_meta($o->ID,'order_status',true),$o->post_date]);fclose($out);exit;}
    public static function export_vendors(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_export_vendors');header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=tager-vendors.csv');$out=fopen('php://output','w');fputcsv($out,['Vendor ID','Name','Store','Email','Status','Rating','Risk']);foreach(get_users(['role__in'=>['tager_vendor','tager_vendor_pending']]) as $v)fputcsv($out,[$v->ID,$v->display_name,get_user_meta($v->ID,'store_name',true),$v->user_email,get_user_meta($v->ID,'vendor_status',true),get_user_meta($v->ID,'vendor_score_rating',true),get_user_meta($v->ID,'vendor_risk_level',true)]);fclose($out);exit;}
}
Tager_V7_Enterprise_Suite::init();
