<?php
/**
 * Plugin Name: Tager V47 Vendor & Market Discovery
 * Description: Governorate/center vendor discovery, tier-aware product search, richer vendor stores, and vendor service-area settings.
 * Version: 47.0.0
 */
if (!defined('ABSPATH')) exit;

final class Tager_V47_Discovery {
    const VER='47.0.0';
    public static function init(){
        add_action('init',[__CLASS__,'register'],99);
        add_action('admin_post_tager_v47_save_location',[__CLASS__,'save_location']);
        add_shortcode('tager_v47_vendor_directory',[__CLASS__,'vendor_directory']);
        add_shortcode('tager_v47_market_search',[__CLASS__,'market_search']);
        add_shortcode('tager_v47_vendor_store',[__CLASS__,'vendor_store']);
        add_shortcode('tager_v47_vendor_location_settings',[__CLASS__,'vendor_location_settings']);
        add_action('wp_enqueue_scripts',[__CLASS__,'assets']);
    }
    public static function register(){
        self::ensure_page('vendor-directory','دليل الموردين','[tager_v47_vendor_directory]');
        self::ensure_page('products','المنتجات والسوق','[tager_v47_market_search]');
        self::ensure_page('vendor-store','متجر المورد','[tager_v47_vendor_store]');
        self::ensure_page('vendor-location-settings','مناطق خدمة المورد','[tager_v47_vendor_location_settings]');
    }
    private static function ensure_page($slug,$title,$content){
        $p=get_page_by_path($slug);
        if(!$p){wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$title,'post_name'=>$slug,'post_content'=>$content]);return;}
        if(trim((string)$p->post_content)!==$content) wp_update_post(['ID'=>$p->ID,'post_content'=>$content]);
    }
    public static function govs(){return [
        'القاهرة'=>['مدينة نصر','مصر الجديدة','المعادي','حلوان','التجمع الخامس','الشروق','بدر','المرج','عين شمس','وسط البلد'],
        'الجيزة'=>['الدقي','العجوزة','الهرم','فيصل','6 أكتوبر','الشيخ زايد','البدرشين','العياط','أوسيم','كرداسة'],
        'الإسكندرية'=>['المنتزه','الرمل','سيدي جابر','سموحة','العجمي','برج العرب','محرم بك','العامرية'],
        'القليوبية'=>['بنها','شبرا الخيمة','قليوب','الخانكة','القناطر الخيرية','طوخ','كفر شكر','العبور'],
        'الشرقية'=>['الزقازيق','العاشر من رمضان','بلبيس','منيا القمح','أبو حماد','فاقوس','ههيا','كفر صقر'],
        'الدقهلية'=>['المنصورة','طلخا','ميت غمر','دكرنس','السنبلاوين','المنزلة','بلقاس','جمصة'],
        'البحيرة'=>['دمنهور','كفر الدوار','رشيد','إدكو','أبو حمص','الدلنجات','وادي النطرون','النوبارية'],
        'الغربية'=>['طنطا','المحلة الكبرى','كفر الزيات','زفتى','السنطة','بسيون','سمنود'],
        'المنوفية'=>['شبين الكوم','منوف','السادات','أشمون','قويسنا','الباجور','بركة السبع'],
        'كفر الشيخ'=>['كفر الشيخ','دسوق','فوه','مطوبس','بلطيم','الحامول','بيلا'],
        'دمياط'=>['دمياط','دمياط الجديدة','رأس البر','فارسكور','الزرقا','كفر سعد'],
        'بورسعيد'=>['بورفؤاد','الشرق','العرب','المناخ','الضواحي','الزهور'],
        'الإسماعيلية'=>['الإسماعيلية','فايد','القنطرة شرق','القنطرة غرب','التل الكبير','أبو صوير'],
        'السويس'=>['السويس','الأربعين','عتاقة','الجناين','فيصل'],
        'الفيوم'=>['الفيوم','سنورس','إطسا','طامية','أبشواي','يوسف الصديق'],
        'بني سويف'=>['بني سويف','ببا','الواسطى','ناصر','سمسطا','الفشن'],
        'المنيا'=>['المنيا','ملوي','سمالوط','بني مزار','مغاغة','أبو قرقاص','مطاي'],
        'أسيوط'=>['أسيوط','ديروط','القوصية','منفلوط','أبنوب','البداري','ساحل سليم'],
        'سوهاج'=>['سوهاج','أخميم','جرجا','طهطا','البلينا','المراغة','المنشأة'],
        'قنا'=>['قنا','نجع حمادي','دشنا','قفط','قوص','نقادة','أبو تشت'],
        'الأقصر'=>['الأقصر','إسنا','أرمنت','البياضية','القرنة','الزينية'],
        'أسوان'=>['أسوان','كوم أمبو','إدفو','دراو','نصر النوبة'],
        'البحر الأحمر'=>['الغردقة','رأس غارب','سفاجا','القصير','مرسى علم','الشلاتين'],
        'الوادي الجديد'=>['الخارجة','الداخلة','الفرافرة','باريس','بلاط'],
        'مطروح'=>['مرسى مطروح','الحمام','العلمين','الضبعة','السلوم','سيوة'],
        'شمال سيناء'=>['العريش','بئر العبد','الشيخ زويد','رفح','الحسنة','نخل'],
        'جنوب سيناء'=>['الطور','شرم الشيخ','دهب','نويبع','رأس سدر','سانت كاترين','أبو رديس']
    ];}
    private static function is_vendor($uid=0){$u=get_userdata($uid?:get_current_user_id());return $u && (in_array('tager_vendor',(array)$u->roles,true)||current_user_can('manage_options'));}
    private static function url($slug,$args=[]){$p=get_page_by_path($slug);$u=$p?get_permalink($p):home_url('/'.$slug.'/');return $args?add_query_arg($args,$u):$u;}
    public static function assets(){
        wp_register_style('tager-v47',false,[],self::VER);wp_enqueue_style('tager-v47');
        wp_add_inline_style('tager-v47','.tv47-wrap{max-width:1240px;margin:auto;padding:24px 16px}.tv47-hero{background:linear-gradient(135deg,#0d4f3c,#176b4f);color:#fff;border-radius:24px;padding:32px;margin-bottom:24px}.tv47-filter{display:grid;grid-template-columns:2fr repeat(4,1fr) auto;gap:12px;background:#fff;padding:18px;border:1px solid #e7ece9;border-radius:18px;box-shadow:0 8px 26px #0d4f3c12}.tv47-filter input,.tv47-filter select{width:100%;padding:12px;border:1px solid #ccd8d2;border-radius:10px}.tv47-btn{background:#b8922e;color:#fff!important;border:0;border-radius:10px;padding:12px 18px;text-decoration:none;cursor:pointer}.tv47-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:22px}.tv47-card{background:#fff;border:1px solid #e4ebe7;border-radius:18px;overflow:hidden;box-shadow:0 7px 22px #173b2c12}.tv47-card-body{padding:18px}.tv47-logo{height:150px;background:#f1f6f3;display:flex;align-items:center;justify-content:center}.tv47-logo img{width:100%;height:100%;object-fit:cover}.tv47-tags{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.tv47-tag{background:#edf6f1;color:#14553f;border-radius:999px;padding:5px 10px;font-size:12px}.tv47-prices{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.tv47-price{background:#f8faf9;padding:9px;border-radius:10px;text-align:center;font-size:12px}.tv47-price b{display:block;font-size:16px;color:#154f3d}.tv47-empty{padding:35px;text-align:center;background:#fff;border-radius:16px;border:1px dashed #b8c9c0}.tv47-settings{max-width:760px}.tv47-settings label{display:block;margin:14px 0;font-weight:600}.tv47-settings input,.tv47-settings select,.tv47-settings textarea{width:100%;padding:12px;border:1px solid #ccd8d2;border-radius:10px}.tv47-cover{height:230px;border-radius:20px;overflow:hidden;background:#eaf3ee}.tv47-cover img{width:100%;height:100%;object-fit:cover}.tv47-store-head{display:grid;grid-template-columns:120px 1fr;gap:20px;align-items:center;margin-top:-55px;padding:0 24px}.tv47-store-head img{width:120px;height:120px;object-fit:cover;border-radius:18px;border:5px solid #fff;background:#fff}@media(max-width:900px){.tv47-filter{grid-template-columns:1fr 1fr}.tv47-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.tv47-filter,.tv47-grid{grid-template-columns:1fr}.tv47-prices{grid-template-columns:1fr}.tv47-store-head{grid-template-columns:80px 1fr}.tv47-store-head img{width:80px;height:80px}}');
        wp_add_inline_script('jquery-core','window.TAGER_V47_CENTERS='.wp_json_encode(self::govs()).';document.addEventListener("change",function(e){if(e.target.matches("[data-tv47-gov]")){var c=document.querySelector("[data-tv47-center]");if(!c)return;var v=e.target.value,arr=window.TAGER_V47_CENTERS[v]||[];c.innerHTML="<option value=\"\">كل المراكز</option>"+arr.map(function(x){return "<option>"+x+"</option>"}).join("");}});');
    }
    public static function vendor_directory(){
        $gov=sanitize_text_field($_GET['gov']??'');$center=sanitize_text_field($_GET['center']??'');$q=sanitize_text_field($_GET['q']??'');
        $args=['role'=>'tager_vendor','number'=>200,'orderby'=>'display_name'];$meta=[];
        if($gov)$meta[]=['key'=>'tager_governorate','value'=>$gov];if($center)$meta[]=['key'=>'tager_center','value'=>$center];if($meta)$args['meta_query']=$meta;
        $vendors=get_users($args);if($q)$vendors=array_values(array_filter($vendors,function($u)use($q){$hay=$u->display_name.' '.get_user_meta($u->ID,'store_name',true).' '.get_user_meta($u->ID,'store_description',true);return mb_stripos($hay,$q)!==false;}));
        ob_start();?><div class="tv47-wrap"><section class="tv47-hero"><h1>ابحث عن المورد المناسب في منطقتك</h1><p>اختر المحافظة ثم المركز، وقارن الموردين والحد الأدنى للطلب ومنتجاتهم.</p></section>
        <form class="tv47-filter"><input name="q" value="<?php echo esc_attr($q);?>" placeholder="اسم المورد أو النشاط"><select name="gov" data-tv47-gov><option value="">كل المحافظات</option><?php foreach(self::govs() as $g=>$cs)echo '<option '.selected($gov,$g,false).'>'.esc_html($g).'</option>';?></select><select name="center" data-tv47-center><option value="">كل المراكز</option><?php foreach((self::govs()[$gov]??[]) as $c)echo '<option '.selected($center,$c,false).'>'.esc_html($c).'</option>';?></select><button class="tv47-btn">بحث</button><a class="tv47-btn" href="<?php echo esc_url(self::url('vendor-directory'));?>">مسح</a></form>
        <div class="tv47-grid"><?php if(!$vendors)echo '<div class="tv47-empty">لا توجد نتائج مطابقة.</div>';foreach($vendors as $v){$logo=(int)get_user_meta($v->ID,'store_logo_id',true);$img=$logo?wp_get_attachment_image_url($logo,'medium'):'';$min=get_user_meta($v->ID,'vendor_min_order',true)?:get_user_meta($v->ID,'minimum_order',true)?:0;$g=get_user_meta($v->ID,'tager_governorate',true);$c=get_user_meta($v->ID,'tager_center',true);$count=count(get_posts(['post_type'=>'tager_product','author'=>$v->ID,'post_status'=>'publish','numberposts'=>-1]));?><article class="tv47-card"><div class="tv47-logo"><?php echo $img?'<img src="'.esc_url($img).'">':'<span style="font-size:50px">🏪</span>';?></div><div class="tv47-card-body"><h3><?php echo esc_html(get_user_meta($v->ID,'store_name',true)?:$v->display_name);?></h3><div class="tv47-tags"><span class="tv47-tag"><?php echo esc_html(trim($g.' - '.$c,' -'));?></span><span class="tv47-tag"><?php echo intval($count);?> منتج</span><span class="tv47-tag">حد أدنى <?php echo esc_html($min);?> ج.م</span></div><p><?php echo esc_html(wp_trim_words(get_user_meta($v->ID,'store_description',true),18));?></p><a class="tv47-btn" href="<?php echo esc_url(self::url('vendor-store',['vendor_id'=>$v->ID]));?>">فتح متجر المورد</a></div></article><?php }?></div></div><?php return ob_get_clean();
    }
    public static function market_search(){
        $q=sanitize_text_field($_GET['q']??'');$tier=sanitize_key($_GET['tier']??'');$gov=sanitize_text_field($_GET['gov']??'');$center=sanitize_text_field($_GET['center']??'');$cat=sanitize_text_field($_GET['cat']??'');$min=(float)($_GET['min_price']??0);$max=(float)($_GET['max_price']??0);
        $args=['post_type'=>'tager_product','post_status'=>'publish','posts_per_page'=>60,'s'=>$q,'meta_query'=>[['key'=>'approval_status','value'=>'approved']]];
        if($cat)$args['meta_query'][]=['key'=>'category_name','value'=>$cat,'compare'=>'LIKE'];$products=get_posts($args);
        $products=array_values(array_filter($products,function($p)use($gov,$center,$tier,$min,$max){$uid=$p->post_author;if($gov&&get_user_meta($uid,'tager_governorate',true)!==$gov)return false;if($center&&get_user_meta($uid,'tager_center',true)!==$center)return false;$key=$tier==='wholesale'?'wholesale_price':($tier==='bulk'?'bulk_price':'retail_price');$price=(float)get_post_meta($p->ID,$key,true);if($min&&$price<$min)return false;if($max&&$price>$max)return false;return true;}));
        ob_start();?><div class="tv47-wrap"><section class="tv47-hero"><h1>سوق تاجر</h1><p>ابحث في القطاعي أو الجملة أو جملة الجملة، وبحسب موقع المورد.</p></section><form class="tv47-filter"><input name="q" value="<?php echo esc_attr($q);?>" placeholder="ابحث عن منتج"><select name="tier"><option value="">كل أنواع البيع</option><option value="retail" <?php selected($tier,'retail');?>>قطاعي</option><option value="wholesale" <?php selected($tier,'wholesale');?>>جملة</option><option value="bulk" <?php selected($tier,'bulk');?>>جملة الجملة</option></select><select name="gov" data-tv47-gov><option value="">كل المحافظات</option><?php foreach(self::govs() as $g=>$cs)echo '<option '.selected($gov,$g,false).'>'.esc_html($g).'</option>';?></select><select name="center" data-tv47-center><option value="">كل المراكز</option><?php foreach((self::govs()[$gov]??[]) as $c)echo '<option '.selected($center,$c,false).'>'.esc_html($c).'</option>';?></select><input name="cat" value="<?php echo esc_attr($cat);?>" placeholder="القسم"><input type="number" step="0.01" name="min_price" value="<?php echo esc_attr($min?:'');?>" placeholder="أقل سعر"><input type="number" step="0.01" name="max_price" value="<?php echo esc_attr($max?:'');?>" placeholder="أعلى سعر"><button class="tv47-btn">تطبيق</button></form>
        <div class="tv47-grid"><?php if(!$products)echo '<div class="tv47-empty">لا توجد منتجات مطابقة.</div>';foreach($products as $p){$id=$p->ID;$r=get_post_meta($id,'retail_price',true);$w=get_post_meta($id,'wholesale_price',true);$b=get_post_meta($id,'bulk_price',true);$wm=get_post_meta($id,'wholesale_min',true);$bm=get_post_meta($id,'bulk_min',true);$vendor=get_userdata($p->post_author);?><article class="tv47-card"><div class="tv47-logo"><?php echo get_the_post_thumbnail($id,'medium')?:'<span style="font-size:50px">📦</span>';?></div><div class="tv47-card-body"><h3><?php echo esc_html($p->post_title);?></h3><a href="<?php echo esc_url(self::url('vendor-store',['vendor_id'=>$p->post_author]));?>"><?php echo esc_html(get_user_meta($p->post_author,'store_name',true)?:$vendor->display_name);?></a><div class="tv47-prices"><div class="tv47-price">قطاعي<b><?php echo esc_html($r);?> ج.م</b></div><div class="tv47-price">جملة<b><?php echo esc_html($w);?> ج.م</b><small><?php echo esc_html($wm);?>+</small></div><div class="tv47-price">جملة الجملة<b><?php echo esc_html($b);?> ج.م</b><small><?php echo esc_html($bm);?>+</small></div></div><div class="tv47-tags"><span class="tv47-tag"><?php echo esc_html(get_post_meta($id,'category_name',true));?></span><span class="tv47-tag">مخزون <?php echo esc_html(get_post_meta($id,'stock',true));?></span></div></div></article><?php }?></div></div><?php return ob_get_clean();
    }
    public static function vendor_store(){
        $id=(int)($_GET['vendor_id']??0);$v=get_userdata($id);if(!$v||!in_array('tager_vendor',(array)$v->roles,true))return '<div class="tv47-empty">المورد غير موجود.</div>';$cover=(int)get_user_meta($id,'store_cover_id',true);$logo=(int)get_user_meta($id,'store_logo_id',true);$products=get_posts(['post_type'=>'tager_product','author'=>$id,'post_status'=>'publish','numberposts'=>100,'meta_key'=>'approval_status','meta_value'=>'approved']);ob_start();?><div class="tv47-wrap"><div class="tv47-cover"><?php if($cover)echo wp_get_attachment_image($cover,'full');?></div><div class="tv47-store-head"><?php echo $logo?wp_get_attachment_image($logo,'medium'):'<div style="font-size:55px">🏪</div>';?><div><h1><?php echo esc_html(get_user_meta($id,'store_name',true)?:$v->display_name);?></h1><p><?php echo esc_html(get_user_meta($id,'tager_governorate',true).' - '.get_user_meta($id,'tager_center',true));?></p><div class="tv47-tags"><span class="tv47-tag">حد أدنى <?php echo esc_html(get_user_meta($id,'vendor_min_order',true)?:0);?> ج.م</span><span class="tv47-tag"><?php echo count($products);?> منتج</span></div></div></div><section style="padding:24px"><p><?php echo nl2br(esc_html(get_user_meta($id,'store_description',true)));?></p><h2>منتجات المورد</h2><div class="tv47-grid"><?php foreach($products as $p){$pid=$p->ID;?><article class="tv47-card"><div class="tv47-logo"><?php echo get_the_post_thumbnail($pid,'medium')?:'<span style="font-size:50px">📦</span>';?></div><div class="tv47-card-body"><h3><?php echo esc_html($p->post_title);?></h3><div class="tv47-prices"><div class="tv47-price">قطاعي<b><?php echo esc_html(get_post_meta($pid,'retail_price',true));?></b></div><div class="tv47-price">جملة<b><?php echo esc_html(get_post_meta($pid,'wholesale_price',true));?></b></div><div class="tv47-price">جملة الجملة<b><?php echo esc_html(get_post_meta($pid,'bulk_price',true));?></b></div></div></div></article><?php }?></div></section></div><?php return ob_get_clean();
    }
    public static function vendor_location_settings(){if(!is_user_logged_in())return '<div class="tv47-empty">سجل الدخول أولًا.</div>';if(!self::is_vendor())return '<div class="tv47-empty">هذه الصفحة للموردين فقط.</div>';$uid=get_current_user_id();$gov=get_user_meta($uid,'tager_governorate',true);$center=get_user_meta($uid,'tager_center',true);ob_start();?><div class="tv47-wrap tv47-settings"><h1>موقع المورد ومناطق الخدمة</h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v47_save_location"><?php wp_nonce_field('tager_v47_save_location');?><label>المحافظة<select required name="governorate" data-tv47-gov><option value="">اختر المحافظة</option><?php foreach(self::govs() as $g=>$cs)echo '<option '.selected($gov,$g,false).'>'.esc_html($g).'</option>';?></select></label><label>المركز / المدينة<select required name="center" data-tv47-center><option value="">اختر المركز</option><?php foreach((self::govs()[$gov]??[]) as $c)echo '<option '.selected($center,$c,false).'>'.esc_html($c).'</option>';?></select></label><label>العنوان التفصيلي<textarea name="address"><?php echo esc_textarea(get_user_meta($uid,'store_address',true));?></textarea></label><label>الحد الأدنى لطلبية المورد (جنيه)<input type="number" min="0" step="0.01" name="minimum_order" value="<?php echo esc_attr(get_user_meta($uid,'vendor_min_order',true));?>"></label><button class="tv47-btn">حفظ البيانات</button></form></div><?php return ob_get_clean();}
    public static function save_location(){if(!is_user_logged_in()||!self::is_vendor())wp_die('Not allowed');check_admin_referer('tager_v47_save_location');$uid=get_current_user_id();$gov=sanitize_text_field($_POST['governorate']??'');$center=sanitize_text_field($_POST['center']??'');$map=self::govs();if(!isset($map[$gov])||!in_array($center,$map[$gov],true))wp_die('Invalid location');update_user_meta($uid,'tager_governorate',$gov);update_user_meta($uid,'tager_center',$center);update_user_meta($uid,'store_address',sanitize_textarea_field($_POST['address']??''));update_user_meta($uid,'vendor_min_order',(float)($_POST['minimum_order']??0));wp_safe_redirect(add_query_arg('saved','1',self::url('vendor-location-settings')));exit;}
}
Tager_V47_Discovery::init();
