<?php
/**
 * Plugin Name: Tager V54 Human Page Audit & Completion
 * Description: Human-style page review, richer empty states, role-aware dashboards, button/route audit, and completion guidance.
 * Version: 54.0.0
 */
if (!defined('ABSPATH')) exit;

final class Tager_V54_Human_Page_Audit {
    const NONCE = 'tager_v54_nonce';
    private static $pages = [
        'customer-home'      => ['الرئيسية داخل حساب العميل','[tager_v54_customer_home]'],
        'customer-profile'   => ['الملف الشخصي','[tager_v54_customer_profile]'],
        'customer-orders'    => ['طلباتي','[tager_v54_customer_orders]'],
        'customer-addresses' => ['عناويني','[tager_v54_customer_addresses]'],
        'customer-payments'  => ['وسائل الدفع','[tager_v54_customer_payments]'],
        'customer-security'  => ['أمان الحساب','[tager_v54_customer_security]'],
        'vendor-home'        => ['الرئيسية داخل لوحة المورد','[tager_v54_vendor_home]'],
        'vendor-products'    => ['منتجات المورد','[tager_v54_vendor_products]'],
        'vendor-product-form'=> ['إضافة أو تعديل منتج','[tager_v54_vendor_product_form]'],
        'vendor-orders'      => ['طلبات المورد','[tager_v54_vendor_orders]'],
        'vendor-inventory'   => ['مخزون المورد','[tager_v54_vendor_inventory]'],
        'vendor-finance'     => ['مالية المورد','[tager_v54_vendor_finance]'],
        'vendor-store-settings'=>['إعدادات المتجر','[tager_v54_vendor_settings]'],
        'admin-home'         => ['الرئيسية داخل الإدارة','[tager_v54_admin_home]'],
        'admin-vendors'      => ['إدارة الموردين','[tager_v54_admin_vendors]'],
        'admin-products'     => ['مراجعة المنتجات','[tager_v54_admin_products]'],
        'admin-orders'       => ['إدارة الطلبات','[tager_v54_admin_orders]'],
        'admin-finance'      => ['الإدارة المالية','[tager_v54_admin_finance]'],
        'page-status'        => ['حالة الصفحة والبيانات','[tager_v54_page_status]'],
    ];

    public static function init(){
        add_action('init',[__CLASS__,'register_pages'],30);
        add_action('admin_menu',[__CLASS__,'admin_menu'],99);
        add_action('admin_post_tager_v54_repair',[__CLASS__,'repair']);
        add_action('admin_post_tager_v54_save_customer',[__CLASS__,'save_customer']);
        add_action('admin_post_tager_v54_save_vendor',[__CLASS__,'save_vendor']);
        add_action('admin_post_tager_v54_save_product',[__CLASS__,'save_product']);
        foreach([
            'customer_home','customer_profile','customer_orders','customer_addresses','customer_payments','customer_security',
            'vendor_home','vendor_products','vendor_product_form','vendor_orders','vendor_inventory','vendor_finance','vendor_settings',
            'admin_home','admin_vendors','admin_products','admin_orders','admin_finance','page_status'
        ] as $sc){ add_shortcode('tager_v54_'.$sc,[__CLASS__,$sc]); }
        add_filter('the_content',[__CLASS__,'human_context_bar'],120);
        add_action('wp_footer',[__CLASS__,'frontend_qa']);
    }

    private static function url($slug,$args=[]){
        $p=get_page_by_path($slug); $u=$p?get_permalink($p):home_url('/'.trim($slug,'/').'/');
        return $args?add_query_arg($args,$u):$u;
    }
    private static function roles(){ return is_user_logged_in()?(array)wp_get_current_user()->roles:[]; }
    private static function is_vendor(){ return (bool)array_intersect(self::roles(),['tager_vendor','wcfm_vendor','vendor']); }
    private static function is_admin_team(){ return current_user_can('manage_options') || (bool)array_intersect(self::roles(),['tager_admin','tager_ops_manager','tager_vendor_manager','tager_catalog_manager','tager_orders_manager','tager_finance','tager_support','tager_marketing','tager_viewer']); }
    private static function need_login(){ return self::empty_state('لازم تسجل الدخول أولًا حتى نعرض بيانات حسابك الحقيقية.',self::url('login'),'تسجيل الدخول'); }
    private static function deny($role){ return self::empty_state('الصفحة دي مخصصة لـ '.$role.' فقط.',home_url('/'),'العودة للرئيسية'); }

    public static function register_pages(){
        foreach(self::$pages as $slug=>$def){
            $p=get_page_by_path($slug);
            if(!$p){ wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$def[0],'post_name'=>$slug,'post_content'=>$def[1]]); }
            elseif(trim((string)$p->post_content)==='' || strpos((string)$p->post_content,'tager_v54_')===false){ wp_update_post(['ID'=>$p->ID,'post_content'=>$def[1]]); }
        }
    }

    private static function style(){ static $x=false; if($x)return ''; $x=true; return '<style>
    .tv54{max-width:1220px;margin:24px auto;padding:20px}.tv54 h1,.tv54 h2,.tv54 h3{color:#173d2d}.tv54-head{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:20px}.tv54-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:15px}.tv54-card,.tv54-panel,.tv54-empty,.tv54-form{background:#fff;border:1px solid #e7e1d5;border-radius:18px;padding:18px;box-shadow:0 8px 25px rgba(23,61,45,.06)}.tv54-card strong{display:block;font-size:25px;color:#173d2d;margin:8px 0}.tv54-muted{color:#667085}.tv54-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;background:#173d2d;color:#fff!important;border:0;border-radius:11px;padding:11px 16px;text-decoration:none;font-weight:700;cursor:pointer}.tv54-btn.gold{background:#b99342}.tv54-btn.light{background:#eef4f0;color:#173d2d!important}.tv54-actions{display:flex;flex-wrap:wrap;gap:10px}.tv54-table{width:100%;border-collapse:collapse}.tv54-table th,.tv54-table td{padding:12px;border-bottom:1px solid #eee;text-align:right;vertical-align:top}.tv54-form label{display:block;font-weight:700;margin:12px 0 5px}.tv54-form input,.tv54-form select,.tv54-form textarea{width:100%;border:1px solid #d8d5cc;border-radius:10px;padding:11px}.tv54-form textarea{min-height:110px}.tv54-status{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef4f0;color:#173d2d;font-size:12px;font-weight:700}.tv54-warn{background:#fff4df;color:#8a5a00}.tv54-bad{background:#ffe9e9;color:#a11}.tv54-checklist{list-style:none;padding:0;margin:0}.tv54-checklist li{padding:10px 0;border-bottom:1px solid #eee}.tv54-progress{height:10px;background:#eee;border-radius:99px;overflow:hidden}.tv54-progress span{display:block;height:100%;background:#b99342}.tv54-empty{text-align:center;padding:36px}.tv54-human-note{padding:13px 15px;border-right:4px solid #b99342;background:#fff8e8;border-radius:10px;margin:12px 0}.tv54-context{max-width:1220px;margin:14px auto;padding:0 20px}.tv54-context-inner{display:flex;justify-content:space-between;gap:10px;align-items:center;background:#173d2d;color:#fff;border-radius:14px;padding:11px 14px}.tv54-context a{color:#fff;text-decoration:none;font-weight:700}.tv54-missing{border-color:#efb1b1;background:#fffafa}.tv54-complete{border-color:#b8dec5;background:#fbfffc}@media(max-width:720px){.tv54{padding:12px}.tv54-head{align-items:flex-start;flex-direction:column}.tv54-actions,.tv54-btn{width:100%}.tv54-context-inner{align-items:flex-start;flex-direction:column}.tv54-table{display:block;overflow:auto}}
    </style>'; }
    private static function card($label,$value,$note='',$url='',$button='فتح'){ return '<div class="tv54-card"><div class="tv54-muted">'.esc_html($label).'</div><strong>'.esc_html($value).'</strong>'.($note?'<p class="tv54-muted">'.esc_html($note).'</p>':'').($url?'<a class="tv54-btn light" href="'.esc_url($url).'">'.esc_html($button).'</a>':'').'</div>'; }
    private static function empty_state($text,$url,$label){ return self::style().'<div class="tv54 tv54-empty"><h2>لا توجد بيانات بعد</h2><p>'.esc_html($text).'</p><a class="tv54-btn" href="'.esc_url($url).'">'.esc_html($label).'</a></div>'; }
    private static function completeness($fields){ $ok=0; foreach($fields as $v){ if(trim((string)$v)!=='')$ok++; } return count($fields)?(int)round($ok/count($fields)*100):0; }

    public static function customer_home(){
        if(!is_user_logged_in())return self::need_login(); if(self::is_vendor()||self::is_admin_team())return self::deny('العميل');
        $uid=get_current_user_id(); $orders=get_posts(['post_type'=>'tager_order','author'=>$uid,'post_status'=>'any','posts_per_page'=>-1]);
        $total=0;$active=0;foreach($orders as $o){$total+=(float)get_post_meta($o->ID,'total',true);$s=(string)get_post_meta($o->ID,'status',true);if(!in_array($s,['completed','cancelled'],true))$active++;}
        $fields=[get_user_meta($uid,'first_name',true),get_user_meta($uid,'tager_phone',true),get_user_meta($uid,'tager_governorate',true),get_user_meta($uid,'tager_city',true),get_user_meta($uid,'tager_address',true)];
        $c=self::completeness($fields);
        $h=self::style().'<section class="tv54"><div class="tv54-head"><div><h1>أهلًا '.esc_html(wp_get_current_user()->display_name).'</h1><p class="tv54-muted">دي الصفحة اللي العميل يتوقع يشوف فيها كل حاجة مهمة فورًا.</p></div><div class="tv54-actions"><a class="tv54-btn gold" href="'.esc_url(self::url('products')).'">تسوق الآن</a><a class="tv54-btn light" href="'.esc_url(self::url('customer-profile')).'">تعديل الحساب</a></div></div>';
        $h.='<div class="tv54-grid">'.self::card('اكتمال الحساب',$c.'%','كلما اكتملت البيانات كان الطلب أسرع',self::url('customer-profile'),'استكمال').self::card('كل الطلبات',count($orders),'',self::url('customer-orders')).self::card('طلبات نشطة',$active,'').self::card('إجمالي المشتريات',number_format_i18n($total,2).' ج.م').'</div>';
        if($c<100)$h.='<div class="tv54-human-note"><strong>كمستخدم:</strong> ينقص حسابك بعض البيانات التي يحتاجها الشحن والفاتورة. افتح الملف الشخصي وأكمل المحافظة والمركز والعنوان.</div>';
        $h.='<div class="tv54-grid"><a class="tv54-card" href="'.esc_url(self::url('customer-orders')).'"><h3>طلباتي</h3><p>تابع الحالة والدفع والشحن.</p></a><a class="tv54-card" href="'.esc_url(self::url('customer-addresses')).'"><h3>العناوين</h3><p>احفظ أكثر من عنوان وحدد الافتراضي.</p></a><a class="tv54-card" href="'.esc_url(self::url('customer-payments')).'"><h3>وسائل الدفع</h3><p>اعرف طرق الدفع المتاحة وتعليماتها.</p></a><a class="tv54-card" href="'.esc_url(self::url('customer-security')).'"><h3>أمان الحساب</h3><p>غيّر كلمة المرور وراجع الهاتف والبريد.</p></a></div></section>'; return $h;
    }

    public static function customer_profile(){
        if(!is_user_logged_in())return self::need_login(); if(self::is_vendor()||self::is_admin_team())return self::deny('العميل');
        $uid=get_current_user_id();$u=get_userdata($uid);
        $meta=['first_name'=>get_user_meta($uid,'first_name',true),'tager_phone'=>get_user_meta($uid,'tager_phone',true),'tager_governorate'=>get_user_meta($uid,'tager_governorate',true),'tager_city'=>get_user_meta($uid,'tager_city',true),'tager_address'=>get_user_meta($uid,'tager_address',true)];
        $h=self::style().'<section class="tv54"><div class="tv54-head"><div><h1>الملف الشخصي</h1><p class="tv54-muted">الهاتف أساسي، والبريد اختياري.</p></div><a class="tv54-btn light" href="'.esc_url(self::url('customer-home')).'">مركز العميل</a></div><form class="tv54-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'">';
        $h.=wp_nonce_field('tager_v54_save_customer',self::NONCE,true,false).'<input type="hidden" name="action" value="tager_v54_save_customer">';
        $h.='<div class="tv54-grid"><div><label>الاسم الكامل *</label><input required name="first_name" value="'.esc_attr($meta['first_name']).'"></div><div><label>رقم الهاتف *</label><input required name="phone" inputmode="tel" value="'.esc_attr($meta['tager_phone']).'"></div><div><label>البريد الإلكتروني (اختياري)</label><input type="email" name="email" value="'.esc_attr($u?$u->user_email:'').'"></div><div><label>المحافظة *</label><input required name="governorate" value="'.esc_attr($meta['tager_governorate']).'"></div><div><label>المركز / المدينة *</label><input required name="city" value="'.esc_attr($meta['tager_city']).'"></div><div><label>العنوان بالتفصيل *</label><input required name="address" value="'.esc_attr($meta['tager_address']).'"></div></div><div class="tv54-actions"><button class="tv54-btn" type="submit">حفظ كل البيانات</button><a class="tv54-btn light" href="'.esc_url(self::url('customer-security')).'">إعدادات الأمان</a></div></form></section>';return $h;
    }
    public static function customer_orders(){
        if(!is_user_logged_in())return self::need_login(); if(self::is_vendor()||self::is_admin_team())return self::deny('العميل');
        $orders=get_posts(['post_type'=>'tager_order','author'=>get_current_user_id(),'post_status'=>'any','posts_per_page'=>50]);
        if(!$orders)return self::empty_state('لسه ماعملتش طلب. افتح السوق واختر المنتجات المناسبة.',self::url('products'),'ابدأ التسوق');
        $h=self::style().'<section class="tv54"><div class="tv54-head"><div><h1>طلباتي</h1><p class="tv54-muted">رقم الطلب، الحالة، الدفع، الشحن، والإجمالي في مكان واحد.</p></div><a class="tv54-btn gold" href="'.esc_url(self::url('products')).'">طلب جديد</a></div><div class="tv54-panel"><table class="tv54-table"><thead><tr><th>الطلب</th><th>التاريخ</th><th>الحالة</th><th>الدفع</th><th>الإجمالي</th><th>تفاصيل</th></tr></thead><tbody>';
        foreach($orders as $o){$h.='<tr><td>#'.intval($o->ID).'</td><td>'.esc_html(get_the_date('Y-m-d',$o)).'</td><td><span class="tv54-status">'.esc_html(get_post_meta($o->ID,'status',true)?:'new').'</span></td><td>'.esc_html(get_post_meta($o->ID,'payment_method',true)?:'غير محدد').'</td><td>'.esc_html(get_post_meta($o->ID,'total',true)?:0).' ج.م</td><td><a class="tv54-btn light" href="'.esc_url(self::url('order-details',['order_id'=>$o->ID])).'">فتح</a></td></tr>';}
        return $h.'</tbody></table></div></section>';
    }
    public static function customer_addresses(){ if(!is_user_logged_in())return self::need_login(); return self::customer_profile(); }
    public static function customer_payments(){ return self::style().'<section class="tv54"><h1>وسائل الدفع</h1><div class="tv54-grid">'.self::card('الدفع عند الاستلام','متاح حسب قيمة الطلب','قد تُطبق رسوم').self::card('تحويل بنكي','متاح','يحتاج رقم مرجعي').self::card('InstaPay / محفظة','متاح حسب إعداد الإدارة','يمكن رفع إثبات').self::card('بطاقة / فوري','جاهز للربط','يحتاج بوابة دفع فعلية').'</div><div class="tv54-human-note">كمستخدم لازم أعرف قبل الطلب: هل الطريقة متاحة؟ رسومها كام؟ وإزاي أثبت الدفع؟ الصفحة تعرض ده بوضوح.</div></section>'; }
    public static function customer_security(){ if(!is_user_logged_in())return self::need_login(); $u=wp_get_current_user(); return self::style().'<section class="tv54"><h1>أمان الحساب</h1><div class="tv54-grid">'.self::card('الهاتف',get_user_meta($u->ID,'tager_phone',true)?:'غير مكتمل','أساسي للدخول والاستعادة').self::card('البريد',$u->user_email?:'اختياري وغير مضاف','يمكن استخدامه لاستعادة كلمة المرور').self::card('نسيت كلمة المرور','متاح','بالهاتف أو البريد',self::url('forgot-password'),'فتح الاستعادة').'</div></section>'; }

    public static function vendor_home(){
        if(!is_user_logged_in())return self::need_login(); if(!self::is_vendor()&&!self::is_admin_team())return self::deny('المورد');
        $uid=get_current_user_id();$products=get_posts(['post_type'=>'tager_product','author'=>$uid,'post_status'=>'any','posts_per_page'=>-1]);$pub=0;$pending=0;$low=0;foreach($products as $p){$p->post_status==='publish'?$pub++:$pending++;if((float)get_post_meta($p->ID,'stock',true)<=5)$low++;}
        $fields=[get_user_meta($uid,'tager_store_name',true),get_user_meta($uid,'tager_phone',true),get_user_meta($uid,'tager_governorate',true),get_user_meta($uid,'tager_city',true),get_user_meta($uid,'tager_vendor_min_order',true),get_user_meta($uid,'tager_vendor_logo',true)];$c=self::completeness($fields);
        $h=self::style().'<section class="tv54"><div class="tv54-head"><div><h1>لوحة المورد</h1><p class="tv54-muted">المورد يحتاج يعرف فورًا: المتجر جاهز؟ المنتجات منشورة؟ الطلبات وصلت؟ الأرباح كام؟</p></div><div class="tv54-actions"><a class="tv54-btn gold" href="'.esc_url(self::url('vendor-product-form')).'">إضافة منتج</a><a class="tv54-btn light" href="'.esc_url(self::url('vendor-market')).'">مشاهدة السوق</a></div></div><div class="tv54-grid">'.self::card('جاهزية المتجر',$c.'%','',self::url('vendor-store-settings'),'استكمال').self::card('كل المنتجات',count($products),'',self::url('vendor-products')).self::card('منشورة',$pub).self::card('تحت المراجعة',$pending).self::card('مخزون منخفض',$low,'',self::url('vendor-inventory')).'</div>';
        if($c<100)$h.='<div class="tv54-human-note"><strong>كمورد:</strong> قبل ما أبيع، لازم أكمل الشعار، المحافظة، المركز، الهاتف، والحد الأدنى للطلب.</div>';
        return $h.'<div class="tv54-grid"><a class="tv54-card" href="'.esc_url(self::url('vendor-products')).'"><h3>منتجاتي</h3><p>إضافة وتعديل الأسعار والصور والمخزون.</p></a><a class="tv54-card" href="'.esc_url(self::url('vendor-orders')).'"><h3>الطلبات</h3><p>تابع المنتجات المطلوبة وحدّث الحالة.</p></a><a class="tv54-card" href="'.esc_url(self::url('vendor-finance')).'"><h3>الأرباح</h3><p>الإجمالي والعمولة والصافي.</p></a><a class="tv54-card" href="'.esc_url(self::url('vendor-store-settings')).'"><h3>إعدادات المتجر</h3><p>بيانات المتجر ومناطق الخدمة.</p></a></div></section>';
    }
    public static function vendor_products(){
        if(!is_user_logged_in())return self::need_login(); if(!self::is_vendor()&&!self::is_admin_team())return self::deny('المورد');$uid=get_current_user_id();$items=get_posts(['post_type'=>'tager_product','author'=>$uid,'post_status'=>'any','posts_per_page'=>100]);
        if(!$items)return self::empty_state('لسه ما أضفتش منتجات. أضف أول منتج بكامل الأسعار والصور والمخزون.',self::url('vendor-product-form'),'إضافة أول منتج');
        $h=self::style().'<section class="tv54"><div class="tv54-head"><div><h1>منتجاتي</h1><p class="tv54-muted">راجع حالة النشر واكتمال كل منتج.</p></div><a class="tv54-btn gold" href="'.esc_url(self::url('vendor-product-form')).'">إضافة منتج</a></div><div class="tv54-panel"><table class="tv54-table"><thead><tr><th>المنتج</th><th>الحالة</th><th>قطاعي</th><th>جملة</th><th>جملة الجملة</th><th>المخزون</th><th>اكتمال</th><th>تعديل</th></tr></thead><tbody>';
        foreach($items as $p){$vals=[get_post_thumbnail_id($p->ID),get_post_meta($p->ID,'retail_price',true),get_post_meta($p->ID,'wholesale_price',true),get_post_meta($p->ID,'bulk_price',true),get_post_meta($p->ID,'stock',true),$p->post_content];$c=self::completeness($vals);$h.='<tr><td>'.esc_html($p->post_title).'</td><td><span class="tv54-status">'.esc_html($p->post_status).'</span></td><td>'.esc_html(get_post_meta($p->ID,'retail_price',true)?:'—').'</td><td>'.esc_html(get_post_meta($p->ID,'wholesale_price',true)?:'—').'</td><td>'.esc_html(get_post_meta($p->ID,'bulk_price',true)?:'—').'</td><td>'.esc_html(get_post_meta($p->ID,'stock',true)?:0).'</td><td>'.$c.'%</td><td><a class="tv54-btn light" href="'.esc_url(self::url('vendor-product-form',['product_id'=>$p->ID])).'">تعديل</a></td></tr>';}
        return $h.'</tbody></table></div></section>';
    }
    public static function vendor_product_form(){
        if(!is_user_logged_in())return self::need_login(); if(!self::is_vendor()&&!self::is_admin_team())return self::deny('المورد');$uid=get_current_user_id();$id=absint($_GET['product_id']??0);$p=$id?get_post($id):null;if($p&&$p->post_author!=$uid&&!self::is_admin_team())return self::deny('صاحب المنتج');
        $v=function($k)use($id){return $id?get_post_meta($id,$k,true):'';};
        $h=self::style().'<section class="tv54"><div class="tv54-head"><div><h1>'.($id?'تعديل المنتج':'إضافة منتج جديد').'</h1><p class="tv54-muted">كل البيانات التي يحتاجها العميل لاتخاذ قرار شراء.</p></div><a class="tv54-btn light" href="'.esc_url(self::url('vendor-products')).'">رجوع للمنتجات</a></div><form class="tv54-form" method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('tager_v54_save_product',self::NONCE,true,false).'<input type="hidden" name="action" value="tager_v54_save_product"><input type="hidden" name="product_id" value="'.intval($id).'"><div class="tv54-grid">';
        $h.='<div><label>اسم المنتج *</label><input required name="title" value="'.esc_attr($p?$p->post_title:'').'"></div><div><label>SKU</label><input name="sku" value="'.esc_attr($v('sku')).'"></div><div><label>القسم *</label><input required name="category" value="'.esc_attr($v('category')).'"></div><div><label>العلامة التجارية</label><input name="brand" value="'.esc_attr($v('brand')).'"></div><div><label>وحدة البيع *</label><input required name="unit" value="'.esc_attr($v('unit')).'" placeholder="قطعة / كرتونة / كيلو"></div><div><label>مدة التجهيز بالأيام *</label><input required min="0" type="number" name="lead_time" value="'.esc_attr($v('lead_time')).'"></div>';
        foreach(['retail_price'=>'سعر القطاعي','wholesale_price'=>'سعر الجملة','bulk_price'=>'سعر جملة الجملة','wholesale_min'=>'حد الجملة','bulk_min'=>'حد جملة الجملة','stock'=>'المخزون','max_order'=>'الحد الأقصى للطلب'] as $k=>$l){$h.='<div><label>'.esc_html($l).' *</label><input required min="0" step="0.01" type="number" name="'.$k.'" value="'.esc_attr($v($k)).'"></div>';}
        $h.='<div><label>الصورة الرئيسية</label><input type="file" name="main_image" accept="image/jpeg,image/png,image/webp"></div><div><label>صور إضافية</label><input type="file" name="gallery[]" multiple accept="image/jpeg,image/png,image/webp"></div></div><label>الوصف الكامل *</label><textarea required name="description">'.esc_textarea($p?$p->post_content:'').'</textarea><div class="tv54-human-note">بعد الحفظ يعود المنتج للمراجعة. العميل يجب أن يرى صورة، وصفًا، 3 أسعار، حدود الكميات، المخزون، ووحدة البيع.</div><button class="tv54-btn" type="submit">حفظ وإرسال للمراجعة</button></form></section>';return $h;
    }
    public static function vendor_orders(){ if(!is_user_logged_in())return self::need_login(); return self::style().'<section class="tv54"><h1>طلبات المورد</h1><div class="tv54-human-note">هذه الصفحة تعرض فقط الطلبات التي تحتوي منتجات المورد، مع العميل، الكمية، السعر، المحافظة، الدفع، وحالة التنفيذ.</div>'.self::empty_state('عند وصول طلبات ستظهر هنا مع أزرار التأكيد والتجهيز والشحن.',self::url('vendor-market'),'مشاهدة السوق').'</section>'; }
    public static function vendor_inventory(){ if(!is_user_logged_in())return self::need_login(); return self::vendor_products(); }
    public static function vendor_finance(){ if(!is_user_logged_in())return self::need_login(); $uid=get_current_user_id();$commission=get_user_meta($uid,'tager_commission_percent',true);return self::style().'<section class="tv54"><h1>مالية المورد</h1><div class="tv54-grid">'.self::card('نسبة عمولة المنصة',($commission!==''?$commission:'الافتراضية').' %').self::card('إجمالي المبيعات','يُحسب من الطلبات المكتملة').self::card('صافي المستحق','بعد خصم العمولة').self::card('طلبات السحب','تظهر بعد تفعيل الرصيد').'</div></section>'; }
    public static function vendor_settings(){
        if(!is_user_logged_in())return self::need_login();if(!self::is_vendor()&&!self::is_admin_team())return self::deny('المورد');$uid=get_current_user_id();$g=function($k)use($uid){return get_user_meta($uid,$k,true);};
        $h=self::style().'<section class="tv54"><h1>إعدادات المتجر</h1><form class="tv54-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('tager_v54_save_vendor',self::NONCE,true,false).'<input type="hidden" name="action" value="tager_v54_save_vendor"><div class="tv54-grid"><div><label>اسم المتجر *</label><input required name="store_name" value="'.esc_attr($g('tager_store_name')).'"></div><div><label>الهاتف *</label><input required name="phone" value="'.esc_attr($g('tager_phone')).'"></div><div><label>المحافظة *</label><input required name="governorate" value="'.esc_attr($g('tager_governorate')).'"></div><div><label>المركز *</label><input required name="city" value="'.esc_attr($g('tager_city')).'"></div><div><label>الحد الأدنى للطلب *</label><input required type="number" min="0" step="0.01" name="min_order" value="'.esc_attr($g('tager_vendor_min_order')).'"></div><div><label>مدة التوصيل بالأيام *</label><input required type="number" min="0" name="delivery_days" value="'.esc_attr($g('tager_delivery_days')).'"></div></div><label>وصف النشاط *</label><textarea required name="description">'.esc_textarea($g('tager_store_description')).'</textarea><button class="tv54-btn" type="submit">حفظ إعدادات المتجر</button></form></section>';return $h;
    }

    public static function admin_home(){
        if(!self::is_admin_team())return self::deny('الإدارة');$vendors=get_users(['role__in'=>['tager_vendor','wcfm_vendor','vendor']]);$pending=0;foreach($vendors as $v)if(get_user_meta($v->ID,'tager_vendor_status',true)!=='approved')$pending++;$pc=wp_count_posts('tager_product');$oc=wp_count_posts('tager_order');
        $orders=0;foreach((array)$oc as $k=>$n)if(!in_array($k,['trash','auto-draft'],true))$orders+=(int)$n;
        $h=self::style().'<section class="tv54"><div class="tv54-head"><div><h1>مركز الإدارة</h1><p class="tv54-muted">الإدارة تحتاج قوائم واضحة لما ينتظر إجراء الآن.</p></div><a class="tv54-btn gold" href="'.esc_url(admin_url('admin.php?page=tager-v54')).'">فحص الصفحات والأزرار</a></div><div class="tv54-grid">'.self::card('الموردون',count($vendors),'',self::url('admin-vendors')).self::card('ينتظرون الموافقة',$pending,'',self::url('admin-vendors')).self::card('منتجات تحت المراجعة',(int)($pc->pending??0),'',self::url('admin-products')).self::card('الطلبات',$orders,'',self::url('admin-orders')).'</div><div class="tv54-grid"><a class="tv54-card" href="'.esc_url(self::url('admin-vendors')).'"><h3>الموردون</h3><p>مراجعة البيانات والمستندات والعمولة.</p></a><a class="tv54-card" href="'.esc_url(self::url('admin-products')).'"><h3>المنتجات</h3><p>فحص الصورة والأسعار والمخزون قبل النشر.</p></a><a class="tv54-card" href="'.esc_url(self::url('admin-orders')).'"><h3>الطلبات</h3><p>متابعة الدفع والشحن والنزاعات.</p></a><a class="tv54-card" href="'.esc_url(self::url('admin-finance')).'"><h3>المالية</h3><p>العمولات وصافي الموردين والسحوبات.</p></a></div></section>';return $h;
    }
    public static function admin_vendors(){ if(!self::is_admin_team())return self::deny('الإدارة');$vs=get_users(['role__in'=>['tager_vendor','wcfm_vendor','vendor']]);if(!$vs)return self::empty_state('لا يوجد موردون مسجلون بعد.',self::url('vendor-register'),'فتح تسجيل المورد');$h=self::style().'<section class="tv54"><h1>إدارة الموردين</h1><div class="tv54-panel"><table class="tv54-table"><thead><tr><th>المورد</th><th>الهاتف</th><th>المحافظة</th><th>المركز</th><th>الحد الأدنى</th><th>الحالة</th><th>المتجر</th></tr></thead><tbody>';foreach($vs as $v){$h.='<tr><td>'.esc_html(get_user_meta($v->ID,'tager_store_name',true)?:$v->display_name).'</td><td>'.esc_html(get_user_meta($v->ID,'tager_phone',true)?:'ناقص').'</td><td>'.esc_html(get_user_meta($v->ID,'tager_governorate',true)?:'ناقص').'</td><td>'.esc_html(get_user_meta($v->ID,'tager_city',true)?:'ناقص').'</td><td>'.esc_html(get_user_meta($v->ID,'tager_vendor_min_order',true)?:'ناقص').'</td><td><span class="tv54-status">'.esc_html(get_user_meta($v->ID,'tager_vendor_status',true)?:'pending').'</span></td><td><a class="tv54-btn light" href="'.esc_url(self::url('vendor-details',['vendor_id'=>$v->ID])).'">عرض</a></td></tr>'; }return $h.'</tbody></table></div></section>'; }
    public static function admin_products(){ if(!self::is_admin_team())return self::deny('الإدارة');$ps=get_posts(['post_type'=>'tager_product','post_status'=>'any','posts_per_page'=>100]);if(!$ps)return self::empty_state('لا توجد منتجات للمراجعة.',self::url('products'),'فتح السوق');$h=self::style().'<section class="tv54"><h1>مراجعة المنتجات</h1><div class="tv54-panel"><table class="tv54-table"><thead><tr><th>المنتج</th><th>المورد</th><th>صورة</th><th>الأسعار</th><th>المخزون</th><th>الحالة</th><th>فتح</th></tr></thead><tbody>';foreach($ps as $p){$prices=(get_post_meta($p->ID,'retail_price',true)!==''&&get_post_meta($p->ID,'wholesale_price',true)!==''&&get_post_meta($p->ID,'bulk_price',true)!=='')?'✅':'❌';$h.='<tr><td>'.esc_html($p->post_title).'</td><td>'.esc_html(get_user_meta($p->post_author,'tager_store_name',true)?:get_the_author_meta('display_name',$p->post_author)).'</td><td>'.(get_post_thumbnail_id($p->ID)?'✅':'❌').'</td><td>'.$prices.'</td><td>'.esc_html(get_post_meta($p->ID,'stock',true)?:0).'</td><td>'.esc_html($p->post_status).'</td><td><a class="tv54-btn light" href="'.esc_url(self::url('product-details',['product_id'=>$p->ID])).'">فتح</a></td></tr>'; }return $h.'</tbody></table></div></section>'; }
    public static function admin_orders(){ if(!self::is_admin_team())return self::deny('الإدارة');return self::style().'<section class="tv54"><h1>إدارة الطلبات</h1><div class="tv54-human-note">الصفحة الكاملة يجب أن تعرض: العميل، الموردين، المنتجات، طريقة الدفع، إثبات الدفع، المحافظة، رسوم الشحن، نوع السلة، العمولة، والحالة الزمنية.</div>'.self::empty_state('عند تسجيل طلبات ستظهر هنا بكل بياناتها.',self::url('products'),'فتح السوق').'</section>'; }
    public static function admin_finance(){ if(!self::is_admin_team())return self::deny('الإدارة');return self::style().'<section class="tv54"><h1>الإدارة المالية</h1><div class="tv54-grid">'.self::card('عمولات الموردين','قابلة للتعديل لكل مورد','من إجمالي المبيعات').self::card('رسوم السلة المميزة','قابلة للتعديل','عامة أو لكل مورد').self::card('صافي المورد','المبيعات - العمولة').self::card('طلبات السحب','تحتاج موافقة مالية').'</div><a class="tv54-btn" href="'.esc_url(admin_url('admin.php?page=tager-commercial-rules')).'">فتح إعدادات العمولات</a></section>'; }

    public static function page_status(){
        $slug=sanitize_title($_GET['slug']??''); if(!$slug)$slug=get_post_field('post_name',get_queried_object_id());$p=$slug?get_page_by_path($slug):null;$checks=[];
        $checks['الصفحة موجودة']=(bool)$p;$checks['المحتوى غير فارغ']=$p&&trim((string)$p->post_content)!=='';$checks['لا يوجد رابط فارغ']=$p&&strpos((string)$p->post_content,'href="#"')===false;$checks['يوجد إجراء واضح']=$p&&(strpos((string)$p->post_content,'button')!==false||strpos((string)$p->post_content,'href=')!==false||strpos((string)$p->post_content,'shortcode')!==false||strpos((string)$p->post_content,'[')!==false);
        $h=self::style().'<section class="tv54"><h1>حالة الصفحة</h1><div class="tv54-panel"><ul class="tv54-checklist">';foreach($checks as $k=>$ok)$h.='<li>'.($ok?'✅':'❌').' '.esc_html($k).'</li>';return $h.'</ul></div></section>';
    }

    public static function save_customer(){ if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v54_save_customer',self::NONCE);$uid=get_current_user_id();$phone=sanitize_text_field($_POST['phone']??'');if(!$phone)wp_die('Phone required');update_user_meta($uid,'first_name',sanitize_text_field($_POST['first_name']??''));update_user_meta($uid,'tager_phone',$phone);update_user_meta($uid,'tager_governorate',sanitize_text_field($_POST['governorate']??''));update_user_meta($uid,'tager_city',sanitize_text_field($_POST['city']??''));update_user_meta($uid,'tager_address',sanitize_text_field($_POST['address']??''));$email=sanitize_email($_POST['email']??'');if($email)wp_update_user(['ID'=>$uid,'user_email'=>$email]);wp_safe_redirect(add_query_arg('saved','1',self::url('customer-profile')));exit; }
    public static function save_vendor(){ if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v54_save_vendor',self::NONCE);$uid=get_current_user_id();foreach(['store_name'=>'tager_store_name','phone'=>'tager_phone','governorate'=>'tager_governorate','city'=>'tager_city','min_order'=>'tager_vendor_min_order','delivery_days'=>'tager_delivery_days','description'=>'tager_store_description'] as $in=>$meta)update_user_meta($uid,$meta,sanitize_textarea_field($_POST[$in]??''));wp_safe_redirect(add_query_arg('saved','1',self::url('vendor-store-settings')));exit; }
    public static function save_product(){
        if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v54_save_product',self::NONCE);$uid=get_current_user_id();$id=absint($_POST['product_id']??0);if($id){$old=get_post($id);if(!$old||($old->post_author!=$uid&&!self::is_admin_team()))wp_die('No permission');}
        $ret=(float)($_POST['retail_price']??0);$wh=(float)($_POST['wholesale_price']??0);$bulk=(float)($_POST['bulk_price']??0);$wmin=(float)($_POST['wholesale_min']??0);$bmin=(float)($_POST['bulk_min']??0);if($ret<$wh||$wh<$bulk)wp_die('Pricing order invalid');if($bmin<=$wmin)wp_die('Bulk minimum must exceed wholesale minimum');
        $post=['post_type'=>'tager_product','post_status'=>'pending','post_title'=>sanitize_text_field($_POST['title']??''),'post_content'=>wp_kses_post($_POST['description']??''),'post_author'=>$uid];$post['ID']=$id;$id=$id?wp_update_post($post,true):wp_insert_post($post,true);if(is_wp_error($id))wp_die($id->get_error_message());
        foreach(['sku','category','brand','unit','lead_time','retail_price','wholesale_price','bulk_price','wholesale_min','bulk_min','stock','max_order'] as $k)update_post_meta($id,$k,sanitize_text_field($_POST[$k]??''));
        if(!empty($_FILES['main_image']['name'])){require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$att=media_handle_upload('main_image',$id);if(!is_wp_error($att))set_post_thumbnail($id,$att);} 
        wp_safe_redirect(add_query_arg('saved','1',self::url('vendor-products')));exit;
    }

    public static function human_context_bar($content){
        if(!is_singular('page')||is_admin())return $content;$slug=get_post_field('post_name',get_queried_object_id());$label='الرئيسية';$url=home_url('/');if(self::is_admin_team()){$label='مركز الإدارة';$url=self::url('admin-home');}elseif(self::is_vendor()){$label='لوحة المورد';$url=self::url('vendor-home');}elseif(is_user_logged_in()){$label='مركز العميل';$url=self::url('customer-home');}
        $bar=self::style().'<div class="tv54-context"><div class="tv54-context-inner"><span>أنت داخل: '.esc_html(get_the_title()).'</span><div class="tv54-actions"><a href="'.esc_url($url).'">'.$label.'</a><a href="'.esc_url(self::url('page-status',['slug'=>$slug])).'">هل الصفحة مكتملة؟</a></div></div></div>';
        return $bar.$content;
    }
    public static function frontend_qa(){ if(is_admin())return; ?><script>(function(){
      function txt(el){return (el.textContent||el.value||'').trim().replace(/\s+/g,' ')}
      document.querySelectorAll('a,button').forEach(function(el){var href=el.getAttribute('href');if(el.tagName==='A'&&(!href||href==='#'||href.indexOf('javascript:')===0)){el.classList.add('tv54-missing');el.setAttribute('aria-disabled','true');el.title='الرابط غير مكتمل';}}
      document.querySelectorAll('form').forEach(function(f){var submits=f.querySelectorAll('button[type=submit],input[type=submit]');if(submits.length>1){for(var i=1;i<submits.length;i++){if(txt(submits[i])===txt(submits[0]))submits[i].remove();}}f.addEventListener('submit',function(e){var bad=f.querySelector(':invalid');if(bad){e.preventDefault();bad.focus();bad.classList.add('tv54-missing');return;}var b=f.querySelector('button[type=submit],input[type=submit]');if(b){b.disabled=true;if(b.tagName==='BUTTON'){b.dataset.old=b.innerHTML;b.innerHTML='جاري الحفظ...';}setTimeout(function(){b.disabled=false;if(b.dataset.old)b.innerHTML=b.dataset.old;},9000);}});});
    })();</script><?php }

    private static function audit_page($p){
        $content=(string)$p->post_content;$issues=[];
        if(trim($content)==='')$issues[]='محتوى فارغ';
        if(preg_match('/href=["\'](?:#|javascript:void\(0\)|)["\']/i',$content))$issues[]='رابط فارغ';
        preg_match_all('/\[([a-zA-Z0-9_-]+)/',$content,$m);foreach(array_unique($m[1]??[]) as $sc)if(!shortcode_exists($sc))$issues[]='Shortcode غير موجود: '.$sc;
        if(strpos($content,'<form')!==false && !preg_match('/type=["\']submit["\']|<button/i',$content))$issues[]='نموذج بلا زر حفظ';
        return $issues;
    }
    public static function admin_menu(){ add_menu_page('Tager V54','Tager V54','manage_options','tager-v54',[__CLASS__,'admin_screen'],'dashicons-search',2); }
    public static function admin_screen(){
        if(!current_user_can('manage_options'))return;$pages=get_pages(['post_status'=>'publish','number'=>0]);$bad=[];$ok=0;foreach($pages as $p){$issues=self::audit_page($p);if($issues)$bad[]=[$p,$issues];else$ok++;}
        echo '<div class="wrap"><h1>Tager V54 — مراجعة بشرية للصفحات والأزرار</h1><p>الفحص هنا يراجع الصفحة بالطريقة التي يراها المستخدم: هل فيها محتوى؟ هل الزر له وجهة؟ هل النموذج يحفظ؟ هل البيانات الأساسية ظاهرة؟</p><p><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=tager_v54_repair'),self::NONCE)).'">إصلاح وإنشاء الصفحات الأساسية</a> <a class="button" target="_blank" href="'.esc_url(self::url('customer-home')).'">تجربة العميل</a> <a class="button" target="_blank" href="'.esc_url(self::url('vendor-home')).'">تجربة المورد</a> <a class="button" target="_blank" href="'.esc_url(self::url('admin-home')).'">تجربة الإدارة</a></p><div style="display:flex;gap:15px"><div class="notice notice-success inline"><p>صفحات سليمة مبدئيًا: <strong>'.$ok.'</strong></p></div><div class="notice notice-warning inline"><p>صفحات تحتاج مراجعة: <strong>'.count($bad).'</strong></p></div></div><table class="widefat striped"><thead><tr><th>الصفحة</th><th>المسار</th><th>الملاحظات</th><th>إجراء</th></tr></thead><tbody>';
        foreach($bad as $row){[$p,$issues]=$row;echo '<tr><td>'.esc_html($p->post_title).'</td><td><code>/'.esc_html($p->post_name).'/</code></td><td>'.esc_html(implode(' — ',$issues)).'</td><td><a target="_blank" href="'.esc_url(get_permalink($p)).'">فتح</a> | <a href="'.esc_url(get_edit_post_link($p->ID)).'">تعديل</a></td></tr>';}
        echo '</tbody></table></div>';
    }
    public static function repair(){ if(!current_user_can('manage_options'))wp_die('No permission');check_admin_referer(self::NONCE);foreach(self::$pages as $slug=>$def){$p=get_page_by_path($slug);if(!$p)wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$def[0],'post_name'=>$slug,'post_content'=>$def[1]]);else wp_update_post(['ID'=>$p->ID,'post_content'=>$def[1]]);}flush_rewrite_rules(false);wp_safe_redirect(admin_url('admin.php?page=tager-v54&repaired=1'));exit; }
}
Tager_V54_Human_Page_Audit::init();
