<?php
/**
 * Plugin Name: Tager Marketplace Full Core
 * Description: Bilingual multi-vendor marketplace demo with customer registration, vendor approval, product moderation, roles, permissions, orders and admin control center.
 * Version: 3.0.0
 */
if (!defined('ABSPATH')) exit;

class Tager_Marketplace_Complete {
    const VERSION = '3.0.0';

    public static function init() {
        add_action('init', [__CLASS__, 'register']);
        add_action('init', [__CLASS__, 'bootstrap'], 30);
        add_action('wp_enqueue_scripts', [__CLASS__, 'assets']);
        add_filter('show_admin_bar', fn($show) => current_user_can('manage_options') ? $show : false);

        foreach ([
            'home','shop','vendor_register','vendor_dashboard','customer_register','customer_account','cart'
        ] as $sc) add_shortcode('tager_'.$sc, [__CLASS__, $sc]);

        add_action('admin_menu', [__CLASS__, 'admin_menu']);
        add_action('admin_post_nopriv_tager_customer_register', [__CLASS__, 'handle_customer_register']);
        add_action('admin_post_tager_customer_register', [__CLASS__, 'handle_customer_register']);
        add_action('admin_post_nopriv_tager_vendor_apply', [__CLASS__, 'handle_vendor_apply']);
        add_action('admin_post_tager_vendor_apply', [__CLASS__, 'handle_vendor_apply']);
        add_action('admin_post_tager_add_product', [__CLASS__, 'handle_add_product']);
        add_action('admin_post_tager_checkout', [__CLASS__, 'handle_checkout']);
        add_action('admin_post_tager_vendor_action', [__CLASS__, 'vendor_action']);
        add_action('admin_post_tager_product_action', [__CLASS__, 'product_action']);
        add_action('admin_post_tager_order_action', [__CLASS__, 'order_action']);
        add_action('admin_post_tager_save_settings', [__CLASS__, 'save_settings']);
    }

    public static function register() {
        register_post_type('tager_product', [
            'labels'=>['name'=>'Tager Products','singular_name'=>'Tager Product'],
            'public'=>true,'show_ui'=>true,'supports'=>['title','editor','thumbnail','author'],
            'rewrite'=>['slug'=>'product'],'menu_icon'=>'dashicons-products'
        ]);
        register_post_type('tager_order', [
            'labels'=>['name'=>'Tager Orders','singular_name'=>'Tager Order'],
            'public'=>false,'show_ui'=>true,'supports'=>['title','author'],'menu_icon'=>'dashicons-clipboard'
        ]);
        add_role('tager_customer','Customer',['read'=>true]);
        add_role('tager_vendor_pending','Vendor Pending',['read'=>true]);
        add_role('tager_vendor','Vendor',['read'=>true,'upload_files'=>true]);
    }

    public static function bootstrap() {
        if (get_option('tager_full_bootstrapped') === self::VERSION) return;
        if (wp_get_theme('tager-marketplace')->exists()) switch_theme('tager-marketplace');
        $pages = [
            'home'=>['الرئيسية','[tager_home]'],
            'shop'=>['المنتجات','[tager_shop]'],
            'customer-register'=>['تسجيل العميل','[tager_customer_register]'],
            'my-account'=>['حساب العميل','[tager_customer_account]'],
            'vendor-register'=>['انضم كمورد','[tager_vendor_register]'],
            'vendor-dashboard'=>['لوحة المورد','[tager_vendor_dashboard]'],
            'cart'=>['السلة','[tager_cart]'],
        ];
        $ids=[];
        foreach($pages as $slug=>$data){
            $p=get_page_by_path($slug);
            $ids[$slug]=$p?$p->ID:wp_insert_post(['post_title'=>$data[0],'post_name'=>$slug,'post_content'=>$data[1],'post_status'=>'publish','post_type'=>'page']);
        }
        update_option('page_on_front',$ids['home']); update_option('show_on_front','page'); update_option('tager_pages',$ids);
        if (!get_option('tager_settings')) update_option('tager_settings', [
            'vendor_auto_approve'=>0,'product_auto_publish'=>0,'vendor_can_edit'=>1,'vendor_can_delete'=>0,
            'commission_percent'=>10,'customer_must_login'=>1,'default_max_qty'=>9999
        ]);
        self::seed_products();
        update_option('tager_full_bootstrapped',self::VERSION);
    }

    private static function seed_products(){
        if(get_option('tager_full_seeded')) return;
        $items=[
            ['زيت طعام 1 لتر','Cooking Oil 1L',100,90,80,10,50,500,'زيوت'],
            ['سكر أبيض 1 كجم','White Sugar 1kg',45,40,36,20,100,1000,'مواد غذائية'],
            ['أرز مصري 5 كجم','Egyptian Rice 5kg',240,220,200,10,50,300,'مواد غذائية'],
            ['مناديل رول 6 حبات','Tissue Roll Pack of 6',85,75,68,12,60,600,'مناديل'],
        ];
        foreach($items as $x){
            $id=wp_insert_post(['post_type'=>'tager_product','post_status'=>'publish','post_title'=>$x[0],'post_content'=>'منتج تجريبي متاح قطاعي وجملة وجملة الجملة.']);
            foreach(['name_en'=>$x[1],'retail_price'=>$x[2],'wholesale_price'=>$x[3],'bulk_price'=>$x[4],'wholesale_min'=>$x[5],'bulk_min'=>$x[6],'stock'=>$x[7],'category_name'=>$x[8],'approval_status'=>'approved','max_qty'=>$x[7]] as $k=>$v) update_post_meta($id,$k,$v);
        }
        update_option('tager_full_seeded',1);
    }

    private static function settings(){return wp_parse_args(get_option('tager_settings',[]),['vendor_auto_approve'=>0,'product_auto_publish'=>0,'vendor_can_edit'=>1,'vendor_can_delete'=>0,'commission_percent'=>10,'customer_must_login'=>1,'default_max_qty'=>9999]);}
    private static function lang(){return (isset($_GET['lang'])&&$_GET['lang']==='en')?'en':'ar';}
    private static function t($ar,$en){return self::lang()==='en'?$en:$ar;}
    private static function url($slug){$p=get_option('tager_pages',[]);return isset($p[$slug])?get_permalink($p[$slug]):home_url('/'.$slug.'/');}
    private static function notice(){if(empty($_GET['msg']))return ''; $map=['registered'=>['تم إنشاء الحساب. يمكنك تسجيل الدخول الآن.','Account created. You can now sign in.'],'vendor_pending'=>['تم إرسال طلب المورد للمراجعة.','Vendor application submitted for review.'],'product_pending'=>['تم إرسال المنتج للمراجعة.','Product submitted for review.'],'order_done'=>['تم استلام الطلب بنجاح.','Order received successfully.']];$x=$map[sanitize_key($_GET['msg'])]??null;return $x?'<div class="notice success">'.esc_html(self::t($x[0],$x[1])).'</div>':'';}

    public static function assets(){wp_enqueue_style('tager-style',get_stylesheet_uri(),[],self::VERSION);wp_register_script('tager-js','',[],self::VERSION,true);wp_enqueue_script('tager-js');wp_add_inline_script('tager-js',self::js());}

    public static function home(){ob_start();?>
      <?php echo self::notice(); ?>
      <section class="tager-hero"><div><span class="eyebrow"><?php echo esc_html(self::t('سوق شامل للقطاعي والجملة','Retail and wholesale marketplace'));?></span><h1><?php echo esc_html(self::t('تاجر — اشترِ وبِع بسهولة','Tager — Buy and sell with ease'));?></h1><p><?php echo esc_html(self::t('حسابات عملاء، موردون، أسعار متدرجة، مراجعة إدارة، وطلبات كاملة.','Customer accounts, vendors, tiered pricing, admin approvals and complete orders.'));?></p><div class="hero-actions"><a class="btn primary" href="<?php echo esc_url(self::url('shop'));?>"><?php echo esc_html(self::t('تصفح المنتجات','Browse products'));?></a><a class="btn secondary" href="<?php echo esc_url(self::url('customer-register'));?>"><?php echo esc_html(self::t('سجل كعميل','Register as customer'));?></a><a class="btn secondary" href="<?php echo esc_url(self::url('vendor-register'));?>"><?php echo esc_html(self::t('انضم كمورد','Become a vendor'));?></a></div></div><div class="hero-card"><div class="metric"><b>3</b><span><?php echo esc_html(self::t('مستويات سعر','Pricing tiers'));?></span></div><div class="metric"><b>2</b><span><?php echo esc_html(self::t('أنواع حسابات','Account types'));?></span></div><div class="metric"><b>100%</b><span><?php echo esc_html(self::t('مراجعة الإدارة','Admin control'));?></span></div></div></section>
      <section class="section"><div class="section-head"><h2><?php echo esc_html(self::t('منتجات مميزة','Featured products'));?></h2></div><?php echo self::product_grid(4);?></section>
    <?php return ob_get_clean();}

    public static function shop(){return self::notice().'<section class="page-hero"><h1>'.esc_html(self::t('المنتجات','Products')).'</h1></section>'.self::product_grid(50);}
    private static function product_grid($limit){$q=new WP_Query(['post_type'=>'tager_product','post_status'=>'publish','posts_per_page'=>$limit,'meta_query'=>[['key'=>'approval_status','value'=>'approved']]]);ob_start();echo '<div class="product-grid">';while($q->have_posts()){$q->the_post();$id=get_the_ID();$name=self::lang()==='en'?(get_post_meta($id,'name_en',true)?:get_the_title()):get_the_title();$r=get_post_meta($id,'retail_price',true);$w=get_post_meta($id,'wholesale_price',true);$b=get_post_meta($id,'bulk_price',true);$wm=get_post_meta($id,'wholesale_min',true);$bm=get_post_meta($id,'bulk_min',true);$max=get_post_meta($id,'max_qty',true)?:9999;echo '<article class="product-card"><div class="product-image">'.(has_post_thumbnail()?get_the_post_thumbnail($id,'medium'):'<span>🛒</span>').'</div><div class="product-body"><h3>'.esc_html($name).'</h3><div class="price"><b>'.esc_html($r).' EGP</b></div><div class="tiers"><span>'.esc_html(self::t('جملة','Wholesale')).': '.esc_html($w).' / '.$wm.'+</span><span>'.esc_html(self::t('جملة الجملة','Bulk')).': '.esc_html($b).' / '.$bm.'+</span></div><div class="qty-row"><input type="number" min="1" max="'.esc_attr($max).'" value="1" id="qty-'.$id.'"><button class="btn primary" onclick="tagerAdd('.$id.',\''.esc_js($name).'\')">'.esc_html(self::t('أضف للسلة','Add to cart')).'</button></div></div></article>'; }wp_reset_postdata();echo '</div>';return ob_get_clean();}

    public static function customer_register(){if(is_user_logged_in())return '<section class="form-wrap"><h1>'.esc_html(self::t('أنت مسجل بالفعل','You are already signed in')).'</h1><a class="btn primary" href="'.esc_url(self::url('my-account')).'">'.esc_html(self::t('حسابي','My account')).'</a></section>';ob_start();?>
      <?php echo self::notice();?><section class="form-wrap"><h1><?php echo esc_html(self::t('تسجيل عميل جديد','Create customer account'));?></h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_customer_register"><?php wp_nonce_field('tager_customer_register');?><label><?php echo esc_html(self::t('الاسم الكامل','Full name'));?><input required name="name"></label><label><?php echo esc_html(self::t('البريد الإلكتروني','Email'));?><input required type="email" name="email"></label><label><?php echo esc_html(self::t('الهاتف','Phone'));?><input required name="phone"></label><label><?php echo esc_html(self::t('كلمة المرور','Password'));?><input required minlength="6" type="password" name="password"></label><button class="btn primary"><?php echo esc_html(self::t('إنشاء الحساب','Create account'));?></button></form><hr><h3><?php echo esc_html(self::t('لديك حساب؟','Already registered?'));?></h3><?php wp_login_form(['redirect'=>self::url('my-account')]);?></section>
    <?php return ob_get_clean();}

    public static function handle_customer_register(){check_admin_referer('tager_customer_register');$email=sanitize_email($_POST['email']??'');if(!$email||email_exists($email))wp_die('Email already exists');$uid=wp_create_user($email,sanitize_text_field($_POST['password']??''),$email);if(is_wp_error($uid))wp_die($uid->get_error_message());$u=new WP_User($uid);$u->set_role('tager_customer');wp_update_user(['ID'=>$uid,'display_name'=>sanitize_text_field($_POST['name']??'')]);update_user_meta($uid,'phone',sanitize_text_field($_POST['phone']??''));wp_safe_redirect(add_query_arg('msg','registered',self::url('customer-register')));exit;}

    public static function customer_account(){if(!is_user_logged_in())return self::customer_login();$u=wp_get_current_user();if(in_array('tager_vendor',$u->roles,true)||in_array('tager_vendor_pending',$u->roles,true))return '<section class="form-wrap"><a class="btn primary" href="'.esc_url(self::url('vendor-dashboard')).'">'.esc_html(self::t('فتح لوحة المورد','Open vendor dashboard')).'</a></section>';ob_start();?>
      <?php echo self::notice();?><section class="page-hero"><h1><?php echo esc_html(self::t('حساب العميل','Customer account'));?></h1><p><?php echo esc_html($u->display_name);?> — <?php echo esc_html($u->user_email);?></p><a class="btn secondary" href="<?php echo esc_url(wp_logout_url(home_url()));?>"><?php echo esc_html(self::t('تسجيل الخروج','Sign out'));?></a></section><section class="section"><h2><?php echo esc_html(self::t('طلباتي','My orders'));?></h2><?php echo self::customer_orders($u->ID,$u->user_email);?></section>
    <?php return ob_get_clean();}
    private static function customer_login(){ob_start();?><section class="form-wrap"><h1><?php echo esc_html(self::t('تسجيل دخول العميل','Customer sign in'));?></h1><?php wp_login_form(['redirect'=>self::url('my-account')]);?><p><a href="<?php echo esc_url(self::url('customer-register'));?>"><?php echo esc_html(self::t('إنشاء حساب جديد','Create a new account'));?></a></p></section><?php return ob_get_clean();}
    private static function customer_orders($uid,$email){$q=new WP_Query(['post_type'=>'tager_order','posts_per_page'=>-1,'meta_query'=>['relation'=>'OR',['key'=>'customer_user','value'=>$uid],['key'=>'email','value'=>$email]]]);ob_start();echo '<div class="table-wrap"><table><tr><th>#</th><th>'.esc_html(self::t('التاريخ','Date')).'</th><th>'.esc_html(self::t('الإجمالي','Total')).'</th><th>'.esc_html(self::t('الحالة','Status')).'</th></tr>';if(!$q->have_posts())echo '<tr><td colspan="4">'.esc_html(self::t('لا توجد طلبات بعد','No orders yet')).'</td></tr>';while($q->have_posts()){$q->the_post();$id=get_the_ID();echo '<tr><td>'.$id.'</td><td>'.esc_html(get_the_date()).'</td><td>'.esc_html(get_post_meta($id,'total',true)).' EGP</td><td>'.esc_html(get_post_meta($id,'order_status',true)).'</td></tr>';}wp_reset_postdata();echo '</table></div>';return ob_get_clean();}

    public static function vendor_register(){if(is_user_logged_in())return '<section class="form-wrap"><a class="btn primary" href="'.esc_url(self::url('vendor-dashboard')).'">'.esc_html(self::t('فتح لوحة المورد','Open vendor dashboard')).'</a></section>';ob_start();?>
      <?php echo self::notice();?><section class="form-wrap"><h1><?php echo esc_html(self::t('طلب انضمام مورد','Vendor application'));?></h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_vendor_apply"><?php wp_nonce_field('tager_vendor_apply');?><label><?php echo esc_html(self::t('اسم المسؤول','Contact name'));?><input required name="name"></label><label><?php echo esc_html(self::t('اسم المتجر','Store name'));?><input required name="store_name"></label><label><?php echo esc_html(self::t('البريد الإلكتروني','Email'));?><input required type="email" name="email"></label><label><?php echo esc_html(self::t('الهاتف','Phone'));?><input required name="phone"></label><label><?php echo esc_html(self::t('كلمة المرور','Password'));?><input required minlength="6" type="password" name="password"></label><label><?php echo esc_html(self::t('السجل التجاري/ملاحظات','Commercial registration / notes'));?><textarea name="notes"></textarea></label><button class="btn primary"><?php echo esc_html(self::t('إرسال للمراجعة','Submit for review'));?></button></form></section>
    <?php return ob_get_clean();}
    public static function handle_vendor_apply(){check_admin_referer('tager_vendor_apply');$email=sanitize_email($_POST['email']??'');if(!$email||email_exists($email))wp_die('Email already exists');$uid=wp_create_user($email,sanitize_text_field($_POST['password']??''),$email);if(is_wp_error($uid))wp_die($uid->get_error_message());$u=new WP_User($uid);$s=self::settings();$u->set_role($s['vendor_auto_approve']?'tager_vendor':'tager_vendor_pending');wp_update_user(['ID'=>$uid,'display_name'=>sanitize_text_field($_POST['name']??'')]);foreach(['store_name','phone','notes'] as $k)update_user_meta($uid,$k,sanitize_textarea_field($_POST[$k]??''));update_user_meta($uid,'vendor_status',$s['vendor_auto_approve']?'approved':'pending');wp_safe_redirect(add_query_arg('msg','vendor_pending',self::url('vendor-register')));exit;}

    public static function vendor_dashboard(){if(!is_user_logged_in())return self::vendor_login();$u=wp_get_current_user();if(in_array('tager_vendor_pending',$u->roles,true))return '<section class="form-wrap"><h1>'.esc_html(self::t('طلبك قيد المراجعة','Your application is under review')).'</h1><a href="'.esc_url(wp_logout_url(home_url())).'">'.esc_html(self::t('تسجيل الخروج','Sign out')).'</a></section>';if(!in_array('tager_vendor',$u->roles,true)&&!current_user_can('manage_options'))return '<section class="form-wrap"><p>'.esc_html(self::t('هذا الحساب ليس حساب مورد','This is not a vendor account')).'</p></section>';ob_start();?>
      <?php echo self::notice();?><section class="page-hero"><h1><?php echo esc_html(self::t('لوحة المورد','Vendor dashboard'));?></h1><p><?php echo esc_html(get_user_meta($u->ID,'store_name',true)?:$u->display_name);?></p></section><section class="section"><div class="feature-grid"><article><b><?php echo intval(self::vendor_count($u->ID));?></b><span><?php echo esc_html(self::t('منتج','Products'));?></span></article><article><b><?php echo intval(self::vendor_orders_count($u->ID));?></b><span><?php echo esc_html(self::t('طلب','Orders'));?></span></article><article><b><?php echo esc_html(self::vendor_sales($u->ID));?> EGP</b><span><?php echo esc_html(self::t('مبيعات','Sales'));?></span></article></div><h2><?php echo esc_html(self::t('إضافة منتج','Add product'));?></h2><form class="product-form" method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_add_product"><?php wp_nonce_field('tager_add_product');?><div class="form-grid"><label><?php echo esc_html(self::t('الاسم بالعربي','Arabic name'));?><input required name="title_ar"></label><label><?php echo esc_html(self::t('الاسم بالإنجليزي','English name'));?><input required name="title_en"></label><label><?php echo esc_html(self::t('سعر القطاعي','Retail price'));?><input required type="number" step="0.01" name="retail"></label><label><?php echo esc_html(self::t('سعر الجملة','Wholesale price'));?><input required type="number" step="0.01" name="wholesale"></label><label><?php echo esc_html(self::t('سعر جملة الجملة','Bulk price'));?><input required type="number" step="0.01" name="bulk"></label><label><?php echo esc_html(self::t('حد الجملة','Wholesale minimum'));?><input required type="number" name="wholesale_min"></label><label><?php echo esc_html(self::t('حد جملة الجملة','Bulk minimum'));?><input required type="number" name="bulk_min"></label><label><?php echo esc_html(self::t('أقصى كمية للطلب','Maximum order quantity'));?><input required type="number" name="max_qty"></label><label><?php echo esc_html(self::t('المخزون','Stock'));?><input required type="number" name="stock"></label><label><?php echo esc_html(self::t('القسم','Category'));?><input required name="category_name"></label></div><label><?php echo esc_html(self::t('الوصف','Description'));?><textarea required name="description"></textarea></label><label><?php echo esc_html(self::t('صورة المنتج','Product image'));?><input type="file" accept="image/*" name="product_image"></label><button class="btn primary"><?php echo esc_html(self::t('حفظ وإرسال للمراجعة','Save and submit'));?></button></form><h2><?php echo esc_html(self::t('منتجاتي','My products'));?></h2><?php echo self::vendor_products($u->ID);?><h2><?php echo esc_html(self::t('طلبات منتجاتي','My product orders'));?></h2><?php echo self::vendor_orders($u->ID);?></section>
    <?php return ob_get_clean();}
    private static function vendor_login(){ob_start();?><section class="form-wrap"><h1><?php echo esc_html(self::t('دخول المورد','Vendor sign in'));?></h1><?php wp_login_form(['redirect'=>self::url('vendor-dashboard')]);?><p><a href="<?php echo esc_url(self::url('vendor-register'));?>"><?php echo esc_html(self::t('طلب حساب مورد','Apply as vendor'));?></a></p></section><?php return ob_get_clean();}
    private static function vendor_count($uid){$x=wp_count_posts('tager_product');$q=new WP_Query(['post_type'=>'tager_product','author'=>$uid,'post_status'=>['publish','pending','draft'],'fields'=>'ids','posts_per_page'=>-1]);return $q->found_posts;}
    private static function vendor_products($uid){$q=new WP_Query(['post_type'=>'tager_product','author'=>$uid,'posts_per_page'=>-1,'post_status'=>['publish','pending','draft']]);ob_start();echo '<div class="table-wrap"><table><tr><th>'.esc_html(self::t('المنتج','Product')).'</th><th>'.esc_html(self::t('الحالة','Status')).'</th><th>'.esc_html(self::t('المخزون','Stock')).'</th></tr>';while($q->have_posts()){$q->the_post();echo '<tr><td>'.esc_html(get_the_title()).'</td><td>'.esc_html(get_post_meta(get_the_ID(),'approval_status',true)?:get_post_status()).'</td><td>'.esc_html(get_post_meta(get_the_ID(),'stock',true)).'</td></tr>';}wp_reset_postdata();echo '</table></div>';return ob_get_clean();}
    private static function vendor_orders_count($uid){return count(self::orders_for_vendor($uid));}
    private static function vendor_sales($uid){$sum=0;foreach(self::orders_for_vendor($uid) as $o){foreach((array)get_post_meta($o->ID,'items',true) as $i)if((int)get_post_field('post_author',(int)$i['id'])===$uid)$sum+=(float)$i['line_total'];}return number_format($sum,2);}
    private static function orders_for_vendor($uid){$orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1]);$out=[];foreach($orders as $o){foreach((array)get_post_meta($o->ID,'items',true) as $i){if((int)get_post_field('post_author',(int)$i['id'])===$uid){$out[]=$o;break;}}}return $out;}
    private static function vendor_orders($uid){$orders=self::orders_for_vendor($uid);ob_start();echo '<div class="table-wrap"><table><tr><th>#</th><th>'.esc_html(self::t('الحالة','Status')).'</th><th>'.esc_html(self::t('الإجمالي','Total')).'</th></tr>';if(!$orders)echo '<tr><td colspan="3">'.esc_html(self::t('لا توجد طلبات','No orders')).'</td></tr>';foreach($orders as $o)echo '<tr><td>'.$o->ID.'</td><td>'.esc_html(get_post_meta($o->ID,'order_status',true)).'</td><td>'.esc_html(get_post_meta($o->ID,'total',true)).' EGP</td></tr>';echo '</table></div>';return ob_get_clean();}
    public static function handle_add_product(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_add_product');$u=wp_get_current_user();if(!in_array('tager_vendor',$u->roles,true)&&!current_user_can('manage_options'))wp_die('Not allowed');$s=self::settings();$status=$s['product_auto_publish']?'publish':'pending';$id=wp_insert_post(['post_type'=>'tager_product','post_status'=>$status,'post_title'=>sanitize_text_field($_POST['title_ar']??''),'post_content'=>sanitize_textarea_field($_POST['description']??''),'post_author'=>$u->ID]);foreach(['name_en'=>'title_en','retail_price'=>'retail','wholesale_price'=>'wholesale','bulk_price'=>'bulk','wholesale_min'=>'wholesale_min','bulk_min'=>'bulk_min','max_qty'=>'max_qty','stock'=>'stock','category_name'=>'category_name'] as $meta=>$post)update_post_meta($id,$meta,sanitize_text_field($_POST[$post]??''));update_post_meta($id,'approval_status',$s['product_auto_publish']?'approved':'pending');if(!empty($_FILES['product_image']['name'])){require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$att=media_handle_upload('product_image',$id);if(!is_wp_error($att))set_post_thumbnail($id,$att);}wp_safe_redirect(add_query_arg('msg','product_pending',self::url('vendor-dashboard')));exit;}

    public static function cart(){ob_start();?>
      <section class="page-hero"><h1><?php echo esc_html(self::t('السلة','Cart'));?></h1></section><div id="tager-cart"></div><section class="form-wrap checkout"><h2><?php echo esc_html(self::t('إتمام الطلب','Checkout'));?></h2><?php if(self::settings()['customer_must_login']&&!is_user_logged_in()):?><div class="notice"><?php echo esc_html(self::t('يجب تسجيل الدخول كعميل قبل إتمام الطلب.','You must sign in as a customer before checkout.'));?> <a href="<?php echo esc_url(self::url('customer-register'));?>"><?php echo esc_html(self::t('تسجيل/دخول','Register / sign in'));?></a></div><?php else:$u=wp_get_current_user();?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" onsubmit="return tagerPrepareCheckout(this)"><input type="hidden" name="action" value="tager_checkout"><input type="hidden" name="cart_json" id="cart_json"><?php wp_nonce_field('tager_checkout');?><label><?php echo esc_html(self::t('الاسم','Name'));?><input required name="customer_name" value="<?php echo esc_attr($u->display_name);?>"></label><label><?php echo esc_html(self::t('الهاتف','Phone'));?><input required name="phone" value="<?php echo esc_attr(get_user_meta($u->ID,'phone',true));?>"></label><label><?php echo esc_html(self::t('البريد','Email'));?><input required type="email" name="email" value="<?php echo esc_attr($u->user_email);?>"></label><label><?php echo esc_html(self::t('العنوان','Address'));?><textarea required name="address"></textarea></label><button class="btn primary"><?php echo esc_html(self::t('تأكيد الطلب','Place order'));?></button></form><?php endif;?></section><script>document.addEventListener('DOMContentLoaded',tagerRenderCart);</script>
    <?php return ob_get_clean();}
    private static function price($id,$qty){$r=(float)get_post_meta($id,'retail_price',true);$w=(float)get_post_meta($id,'wholesale_price',true);$b=(float)get_post_meta($id,'bulk_price',true);$wm=(int)get_post_meta($id,'wholesale_min',true);$bm=(int)get_post_meta($id,'bulk_min',true);return $bm&&$qty>=$bm?$b:($wm&&$qty>=$wm?$w:$r);}
    public static function handle_checkout(){check_admin_referer('tager_checkout');$s=self::settings();if($s['customer_must_login']&&!is_user_logged_in())wp_die('Login required');$cart=json_decode(stripslashes($_POST['cart_json']??'[]'),true);if(!$cart)wp_die('Empty cart');$lines=[];$total=0;foreach($cart as $item){$id=(int)$item['id'];$qty=max(1,(int)$item['qty']);$max=(int)(get_post_meta($id,'max_qty',true)?:9999);$stock=(int)get_post_meta($id,'stock',true);if($qty>$max||$qty>$stock)wp_die('Quantity exceeds limits');$price=self::price($id,$qty);$line=$price*$qty;$total+=$line;$lines[]=['id'=>$id,'name'=>get_the_title($id),'qty'=>$qty,'unit_price'=>$price,'line_total'=>$line,'vendor_id'=>(int)get_post_field('post_author',$id)];update_post_meta($id,'stock',$stock-$qty);} $uid=get_current_user_id();$order=wp_insert_post(['post_type'=>'tager_order','post_status'=>'publish','post_title'=>'Order '.current_time('Ymd-His'),'post_author'=>$uid]);foreach(['customer_name','phone','email','address'] as $k)update_post_meta($order,$k,$k==='email'?sanitize_email($_POST[$k]??''):sanitize_textarea_field($_POST[$k]??''));update_post_meta($order,'customer_user',$uid);update_post_meta($order,'items',$lines);update_post_meta($order,'total',$total);update_post_meta($order,'order_status','New');wp_safe_redirect(add_query_arg('msg','order_done',self::url('my-account')));exit;}

    public static function admin_menu(){add_menu_page('Tager Control Center','Tager Control','manage_options','tager-control',[__CLASS__,'admin_page'],'dashicons-store',2);}
    public static function admin_page(){if(!current_user_can('manage_options'))return;$tab=sanitize_key($_GET['tab']??'dashboard');$tabs=['dashboard'=>'Dashboard','vendors'=>'Vendors','products'=>'Products','orders'=>'Orders','customers'=>'Customers','settings'=>'Settings'];echo '<div class="wrap"><h1>Tager Marketplace Control Center</h1><nav class="nav-tab-wrapper">';foreach($tabs as $k=>$v)echo '<a class="nav-tab '.($tab===$k?'nav-tab-active':'').'" href="'.esc_url(admin_url('admin.php?page=tager-control&tab='.$k)).'">'.$v.'</a>';echo '</nav>';if($tab==='vendors')self::admin_vendors();elseif($tab==='products')self::admin_products();elseif($tab==='orders')self::admin_orders();elseif($tab==='customers')self::admin_customers();elseif($tab==='settings')self::admin_settings();else self::admin_dashboard();echo '</div>';}
    private static function admin_dashboard(){echo '<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-top:20px">';$cards=[['Pending Vendors',count(get_users(['role'=>'tager_vendor_pending']))],['Approved Vendors',count(get_users(['role'=>'tager_vendor']))],['Pending Products',count(get_posts(['post_type'=>'tager_product','post_status'=>'pending','numberposts'=>-1]))],['Orders',wp_count_posts('tager_order')->publish??0]];foreach($cards as $c)echo '<div class="postbox" style="padding:20px"><h2>'.$c[0].'</h2><strong style="font-size:28px">'.$c[1].'</strong></div>';echo '</div><p>Use the tabs above to approve vendors, moderate products, manage orders, customers and permissions.</p>';}
    private static function action_url($action,$args,$nonce){return wp_nonce_url(add_query_arg(array_merge(['action'=>$action],$args),admin_url('admin-post.php')),$nonce);}
    private static function admin_vendors(){$users=array_merge(get_users(['role'=>'tager_vendor_pending']),get_users(['role'=>'tager_vendor']));echo '<h2>Vendor Management</h2><table class="widefat striped"><tr><th>Name</th><th>Store</th><th>Email</th><th>Status</th><th>Actions</th></tr>';foreach($users as $u){$st=get_user_meta($u->ID,'vendor_status',true)?:($u->roles[0]??'');$a=self::action_url('tager_vendor_action',['user'=>$u->ID,'do'=>'approve'],'tager_vendor_'.$u->ID);$r=self::action_url('tager_vendor_action',['user'=>$u->ID,'do'=>'reject'],'tager_vendor_'.$u->ID);$s=self::action_url('tager_vendor_action',['user'=>$u->ID,'do'=>'suspend'],'tager_vendor_'.$u->ID);echo '<tr><td>'.esc_html($u->display_name).'</td><td>'.esc_html(get_user_meta($u->ID,'store_name',true)).'</td><td>'.esc_html($u->user_email).'</td><td>'.esc_html($st).'</td><td><a class="button button-primary" href="'.$a.'">Approve</a> <a class="button" href="'.$s.'">Suspend</a> <a class="button button-link-delete" href="'.$r.'">Reject/Delete</a></td></tr>';}echo '</table>';}
    public static function vendor_action(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_GET['user']??0);check_admin_referer('tager_vendor_'.$id);$do=sanitize_key($_GET['do']??'');$u=new WP_User($id);if($do==='approve'){$u->set_role('tager_vendor');update_user_meta($id,'vendor_status','approved');}elseif($do==='suspend'){$u->set_role('tager_vendor_pending');update_user_meta($id,'vendor_status','suspended');}elseif($do==='reject')wp_delete_user($id);wp_safe_redirect(admin_url('admin.php?page=tager-control&tab=vendors'));exit;}
    private static function admin_products(){$ps=get_posts(['post_type'=>'tager_product','post_status'=>['publish','pending','draft'],'numberposts'=>-1]);echo '<h2>Product Moderation</h2><table class="widefat striped"><tr><th>Product</th><th>Vendor</th><th>Status</th><th>Price</th><th>Actions</th></tr>';foreach($ps as $p){$a=self::action_url('tager_product_action',['product'=>$p->ID,'do'=>'approve'],'tager_product_'.$p->ID);$r=self::action_url('tager_product_action',['product'=>$p->ID,'do'=>'reject'],'tager_product_'.$p->ID);$d=self::action_url('tager_product_action',['product'=>$p->ID,'do'=>'delete'],'tager_product_'.$p->ID);echo '<tr><td>'.esc_html($p->post_title).'</td><td>'.esc_html(get_the_author_meta('display_name',$p->post_author)).'</td><td>'.esc_html(get_post_meta($p->ID,'approval_status',true)?:$p->post_status).'</td><td>'.esc_html(get_post_meta($p->ID,'retail_price',true)).'</td><td><a class="button button-primary" href="'.$a.'">Approve</a> <a class="button" href="'.$r.'">Return to pending</a> <a class="button button-link-delete" href="'.$d.'">Delete</a></td></tr>';}echo '</table>';}
    public static function product_action(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_GET['product']??0);check_admin_referer('tager_product_'.$id);$do=sanitize_key($_GET['do']??'');if($do==='approve'){wp_update_post(['ID'=>$id,'post_status'=>'publish']);update_post_meta($id,'approval_status','approved');}elseif($do==='reject'){wp_update_post(['ID'=>$id,'post_status'=>'pending']);update_post_meta($id,'approval_status','pending');}elseif($do==='delete')wp_delete_post($id,true);wp_safe_redirect(admin_url('admin.php?page=tager-control&tab=products'));exit;}
    private static function admin_orders(){$os=get_posts(['post_type'=>'tager_order','numberposts'=>-1]);echo '<h2>Order Management</h2><table class="widefat striped"><tr><th>#</th><th>Customer</th><th>Total</th><th>Status</th><th>Update</th></tr>';foreach($os as $o){echo '<tr><td>'.$o->ID.'</td><td>'.esc_html(get_post_meta($o->ID,'customer_name',true)).'</td><td>'.esc_html(get_post_meta($o->ID,'total',true)).' EGP</td><td>'.esc_html(get_post_meta($o->ID,'order_status',true)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_order_action"><input type="hidden" name="order" value="'.$o->ID.'">'.wp_nonce_field('tager_order_'.$o->ID,'_wpnonce',true,false).'<select name="status"><option>New</option><option>Confirmed</option><option>Processing</option><option>Shipped</option><option>Completed</option><option>Cancelled</option></select> <button class="button">Update</button></form></td></tr>';}echo '</table>';}
    public static function order_action(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_POST['order']??0);check_admin_referer('tager_order_'.$id);update_post_meta($id,'order_status',sanitize_text_field($_POST['status']??'New'));wp_safe_redirect(admin_url('admin.php?page=tager-control&tab=orders'));exit;}
    private static function admin_customers(){$users=get_users(['role'=>'tager_customer']);echo '<h2>Customers</h2><table class="widefat striped"><tr><th>Name</th><th>Email</th><th>Phone</th><th>Registered</th></tr>';foreach($users as $u)echo '<tr><td>'.esc_html($u->display_name).'</td><td>'.esc_html($u->user_email).'</td><td>'.esc_html(get_user_meta($u->ID,'phone',true)).'</td><td>'.esc_html($u->user_registered).'</td></tr>';echo '</table>';}
    private static function admin_settings(){$s=self::settings();echo '<h2>Marketplace Settings & Permissions</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_save_settings">'.wp_nonce_field('tager_save_settings','_wpnonce',true,false).'<table class="form-table"><tr><th>Vendor auto approval</th><td><input type="checkbox" name="vendor_auto_approve" value="1" '.checked($s['vendor_auto_approve'],1,false).'></td></tr><tr><th>Product auto publish</th><td><input type="checkbox" name="product_auto_publish" value="1" '.checked($s['product_auto_publish'],1,false).'></td></tr><tr><th>Vendor can edit products</th><td><input type="checkbox" name="vendor_can_edit" value="1" '.checked($s['vendor_can_edit'],1,false).'></td></tr><tr><th>Vendor can delete products</th><td><input type="checkbox" name="vendor_can_delete" value="1" '.checked($s['vendor_can_delete'],1,false).'></td></tr><tr><th>Customer must login before checkout</th><td><input type="checkbox" name="customer_must_login" value="1" '.checked($s['customer_must_login'],1,false).'></td></tr><tr><th>Platform commission %</th><td><input type="number" min="0" max="100" name="commission_percent" value="'.esc_attr($s['commission_percent']).'"></td></tr></table><button class="button button-primary">Save Settings</button></form>';}
    public static function save_settings(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_save_settings');$s=self::settings();foreach(['vendor_auto_approve','product_auto_publish','vendor_can_edit','vendor_can_delete','customer_must_login'] as $k)$s[$k]=isset($_POST[$k])?1:0;$s['commission_percent']=min(100,max(0,(float)($_POST['commission_percent']??10)));update_option('tager_settings',$s);wp_safe_redirect(admin_url('admin.php?page=tager-control&tab=settings'));exit;}

    private static function js(){return "
    window.tagerCart=function(){try{return JSON.parse(localStorage.getItem('tager_cart')||'[]')}catch(e){return[]}};
    window.tagerAdd=function(id,name){var q=Math.max(1,parseInt(document.getElementById('qty-'+id).value||1)),c=tagerCart(),f=c.find(x=>x.id===id);if(f)f.qty+=q;else c.push({id:id,name:name,qty:q});localStorage.setItem('tager_cart',JSON.stringify(c));alert('".esc_js(self::t('تمت الإضافة للسلة','Added to cart'))."');};
    window.tagerRenderCart=function(){var el=document.getElementById('tager-cart');if(!el)return;var c=tagerCart();if(!c.length){el.innerHTML='<div class=notice>".esc_js(self::t('السلة فارغة','Your cart is empty'))."</div>';return;}var h='<div class=table-wrap><table><tr><th>".esc_js(self::t('المنتج','Product'))."</th><th>".esc_js(self::t('الكمية','Quantity'))."</th><th></th></tr>';c.forEach((x,i)=>h+='<tr><td>'+x.name+'</td><td><input type=number min=1 value='+x.qty+' onchange=tagerQty('+i+',this.value)></td><td><button onclick=tagerRemove('+i+')>×</button></td></tr>');el.innerHTML=h+'</table></div>';};
    window.tagerQty=function(i,v){var c=tagerCart();c[i].qty=Math.max(1,parseInt(v||1));localStorage.setItem('tager_cart',JSON.stringify(c));tagerRenderCart();};window.tagerRemove=function(i){var c=tagerCart();c.splice(i,1);localStorage.setItem('tager_cart',JSON.stringify(c));tagerRenderCart();};window.tagerPrepareCheckout=function(){var c=tagerCart();if(!c.length){alert('Empty cart');return false;}document.getElementById('cart_json').value=JSON.stringify(c);return true;};";}
}
Tager_Marketplace_Complete::init();
