<?php
/**
 * Plugin Name: Tager V6 Operations Suite
 * Description: Support tickets, product reviews, audit trail, low-stock alerts, notifications, vendor scorecards and operational dashboards.
 * Version: 6.0.0
 */
if (!defined('ABSPATH')) exit;

class Tager_V6_Operations {
  const VERSION='6.0.0';
  static function init(){
    add_action('init',[__CLASS__,'register']);
    add_action('init',[__CLASS__,'bootstrap'],60);
    add_action('admin_menu',[__CLASS__,'menus'],60);
    add_shortcode('tager_support',[__CLASS__,'support_page']);
    add_shortcode('tager_notifications',[__CLASS__,'notifications_page']);
    add_shortcode('tager_reviews',[__CLASS__,'reviews_page']);
    foreach(['support_submit','review_submit','ticket_status','notification_read'] as $a){
      add_action('admin_post_tager_'.$a,[__CLASS__,$a]);
      add_action('admin_post_nopriv_tager_'.$a,[__CLASS__,$a]);
    }
    add_action('admin_post_tager_vendor_score_save',[__CLASS__,'vendor_score_save']);
    add_action('admin_post_tager_bulk_product_action',[__CLASS__,'bulk_product_action']);
    add_action('admin_post_tager_low_stock_settings',[__CLASS__,'low_stock_settings']);
  }
  static function register(){
    register_post_type('tager_ticket',['labels'=>['name'=>'Support Tickets','singular_name'=>'Support Ticket'],'public'=>false,'show_ui'=>true,'supports'=>['title','editor','author'],'menu_icon'=>'dashicons-sos']);
    register_post_type('tager_review',['labels'=>['name'=>'Product Reviews','singular_name'=>'Product Review'],'public'=>false,'show_ui'=>true,'supports'=>['title','editor','author'],'menu_icon'=>'dashicons-star-filled']);
    register_post_type('tager_notice',['labels'=>['name'=>'Marketplace Notifications','singular_name'=>'Marketplace Notification'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor','author']]);
    register_post_type('tager_audit',['labels'=>['name'=>'Audit Log','singular_name'=>'Audit Entry'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor','author']]);
  }
  static function bootstrap(){
    if(get_option('tager_v6_bootstrapped')===self::VERSION)return;
    $pages=get_option('tager_pages',[]);
    foreach(['support'=>['الدعم والتذاكر','[tager_support]'],'notifications'=>['الإشعارات','[tager_notifications]'],'reviews'=>['التقييمات','[tager_reviews]']] as $slug=>$d){
      $p=get_page_by_path($slug);$id=$p?$p->ID:wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_name'=>$slug,'post_title'=>$d[0],'post_content'=>$d[1]]);$pages[$slug]=$id;
    }
    update_option('tager_pages',$pages);
    if(get_option('tager_low_stock_threshold')===false)update_option('tager_low_stock_threshold',10);
    update_option('tager_v6_bootstrapped',self::VERSION);
  }
  static function menus(){
    add_submenu_page('tager-control','Operations Dashboard','Operations Dashboard','manage_options','tager-operations',[__CLASS__,'operations_dashboard']);
    add_submenu_page('tager-control','Support Tickets','Support Tickets','manage_options','tager-support-admin',[__CLASS__,'support_admin']);
    add_submenu_page('tager-control','Reviews & Ratings','Reviews & Ratings','manage_options','tager-reviews-admin',[__CLASS__,'reviews_admin']);
    add_submenu_page('tager-control','Audit Log','Audit Log','manage_options','tager-audit-log',[__CLASS__,'audit_admin']);
    add_submenu_page('tager-control','Vendor Scorecards','Vendor Scorecards','manage_options','tager-vendor-scorecards',[__CLASS__,'vendor_scorecards']);
  }
  static function page($slug){$p=get_option('tager_pages',[]);return !empty($p[$slug])?get_permalink($p[$slug]):home_url('/'.$slug.'/');}
  static function nonce($a){return wp_nonce_field($a,'_wpnonce',true,false);}  
  static function audit($action,$object='',$object_id=0,$details=''){
    $id=wp_insert_post(['post_type'=>'tager_audit','post_status'=>'publish','post_title'=>sanitize_text_field($action),'post_content'=>sanitize_textarea_field($details),'post_author'=>get_current_user_id()]);
    if($id){update_post_meta($id,'object_type',$object);update_post_meta($id,'object_id',(int)$object_id);update_post_meta($id,'ip',sanitize_text_field($_SERVER['REMOTE_ADDR']??''));}
  }
  static function notify($uid,$title,$body,$type='info'){
    $id=wp_insert_post(['post_type'=>'tager_notice','post_status'=>'publish','post_title'=>$title,'post_content'=>$body,'post_author'=>(int)$uid]);
    if($id){update_post_meta($id,'notice_type',$type);update_post_meta($id,'notice_read',0);}return $id;
  }
  static function support_page(){
    if(!is_user_logged_in())return '<section class="form-wrap"><h1>الدعم</h1><p>سجّل الدخول أولًا لإرسال تذكرة.</p></section>';
    $uid=get_current_user_id();$tickets=get_posts(['post_type'=>'tager_ticket','author'=>$uid,'numberposts'=>50,'orderby'=>'date','order'=>'DESC']);ob_start();
    echo '<section class="dash-content"><h1>الدعم والتذاكر</h1><form class="form-grid" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_support_submit">'.self::nonce('tager_support_submit').'<input name="subject" required placeholder="عنوان المشكلة"><select name="priority"><option value="normal">عادية</option><option value="high">عاجلة</option><option value="urgent">حرجة</option></select><textarea name="message" required placeholder="اكتب تفاصيل المشكلة"></textarea><button class="btn primary">إرسال التذكرة</button></form><h2>تذاكري</h2><div class="table-wrap"><table><tr><th>#</th><th>العنوان</th><th>الأولوية</th><th>الحالة</th><th>آخر تحديث</th></tr>';
    foreach($tickets as $t)echo '<tr><td>'.$t->ID.'</td><td>'.esc_html($t->post_title).'</td><td>'.esc_html(get_post_meta($t->ID,'priority',true)).'</td><td>'.esc_html(get_post_meta($t->ID,'ticket_status',true)?:'open').'</td><td>'.esc_html(get_the_modified_date('', $t)).'</td></tr>';
    echo '</table></div></section>';return ob_get_clean();
  }
  static function support_submit(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_support_submit');$id=wp_insert_post(['post_type'=>'tager_ticket','post_status'=>'publish','post_title'=>sanitize_text_field($_POST['subject']??''),'post_content'=>sanitize_textarea_field($_POST['message']??''),'post_author'=>get_current_user_id()]);update_post_meta($id,'priority',sanitize_key($_POST['priority']??'normal'));update_post_meta($id,'ticket_status','open');self::audit('ticket_created','ticket',$id,'Customer created a support ticket');wp_safe_redirect(add_query_arg('sent',1,self::page('support')));exit;}
  static function notifications_page(){if(!is_user_logged_in())return '<p>سجّل الدخول أولًا.</p>';$uid=get_current_user_id();$ns=get_posts(['post_type'=>'tager_notice','author'=>$uid,'numberposts'=>100,'orderby'=>'date','order'=>'DESC']);ob_start();echo '<section class="dash-content"><h1>الإشعارات</h1><div class="notice-list">';foreach($ns as $n){$read=get_post_meta($n->ID,'notice_read',true);echo '<article class="notice-card '.(!$read?'unread':'').'"><h3>'.esc_html($n->post_title).'</h3><p>'.esc_html($n->post_content).'</p><small>'.esc_html(get_the_date('', $n)).'</small>'.(!$read?'<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_notification_read"><input type="hidden" name="notice" value="'.$n->ID.'">'.self::nonce('tager_notification_'.$n->ID).'<button class="btn secondary">تحديد كمقروء</button></form>':'').'</article>';}echo '</div></section>';return ob_get_clean();}
  static function notification_read(){if(!is_user_logged_in())wp_die('Login required');$id=(int)($_POST['notice']??0);check_admin_referer('tager_notification_'.$id);$p=get_post($id);if(!$p||(int)$p->post_author!==get_current_user_id())wp_die('Not allowed');update_post_meta($id,'notice_read',1);wp_safe_redirect(self::page('notifications'));exit;}
  static function reviews_page(){if(!is_user_logged_in())return '<p>سجّل الدخول أولًا لإضافة تقييم.</p>';$products=get_posts(['post_type'=>'tager_product','post_status'=>'publish','numberposts'=>100]);$my=get_posts(['post_type'=>'tager_review','author'=>get_current_user_id(),'numberposts'=>100]);ob_start();echo '<section class="dash-content"><h1>تقييم المنتجات</h1><form class="form-grid" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_review_submit">'.self::nonce('tager_review_submit').'<select name="product" required><option value="">اختر المنتج</option>';foreach($products as $p)echo '<option value="'.$p->ID.'">'.esc_html($p->post_title).'</option>';echo '</select><select name="rating" required><option value="5">5 ممتاز</option><option value="4">4 جيد جدًا</option><option value="3">3 جيد</option><option value="2">2 ضعيف</option><option value="1">1 سيئ</option></select><textarea name="comment" required placeholder="اكتب تقييمك"></textarea><button class="btn primary">إرسال التقييم</button></form><h2>تقييماتي</h2><div class="table-wrap"><table><tr><th>المنتج</th><th>التقييم</th><th>الحالة</th></tr>';foreach($my as $r)echo '<tr><td>'.esc_html(get_the_title((int)get_post_meta($r->ID,'product_id',true))).'</td><td>'.esc_html(get_post_meta($r->ID,'rating',true)).'/5</td><td>'.esc_html(get_post_meta($r->ID,'review_status',true)?:'pending').'</td></tr>';echo '</table></div></section>';return ob_get_clean();}
  static function review_submit(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_review_submit');$pid=(int)($_POST['product']??0);$rating=max(1,min(5,(int)($_POST['rating']??5)));$id=wp_insert_post(['post_type'=>'tager_review','post_status'=>'publish','post_title'=>'Review for product '.$pid,'post_content'=>sanitize_textarea_field($_POST['comment']??''),'post_author'=>get_current_user_id()]);update_post_meta($id,'product_id',$pid);update_post_meta($id,'rating',$rating);update_post_meta($id,'review_status','pending');self::audit('review_submitted','product',$pid,'Rating '.$rating);wp_safe_redirect(self::page('reviews'));exit;}
  static function operations_dashboard(){if(!current_user_can('manage_options'))return;$pending_v=count(get_users(['role'=>'tager_vendor_pending']));$pending_p=count(get_posts(['post_type'=>'tager_product','post_status'=>['pending','draft'],'numberposts'=>-1]));$open_t=count(get_posts(['post_type'=>'tager_ticket','numberposts'=>-1,'meta_key'=>'ticket_status','meta_value'=>'open']));$pending_r=count(get_posts(['post_type'=>'tager_review','numberposts'=>-1,'meta_key'=>'review_status','meta_value'=>'pending']));$low=self::low_stock_products();echo '<div class="wrap"><h1>Tager Operations Dashboard</h1><div style="display:grid;grid-template-columns:repeat(5,minmax(150px,1fr));gap:15px"><div class="postbox" style="padding:18px"><b>Pending Vendors</b><h2>'.$pending_v.'</h2></div><div class="postbox" style="padding:18px"><b>Pending Products</b><h2>'.$pending_p.'</h2></div><div class="postbox" style="padding:18px"><b>Open Tickets</b><h2>'.$open_t.'</h2></div><div class="postbox" style="padding:18px"><b>Pending Reviews</b><h2>'.$pending_r.'</h2></div><div class="postbox" style="padding:18px"><b>Low Stock</b><h2>'.count($low).'</h2></div></div><h2>Low Stock Products</h2><table class="widefat striped"><tr><th>Product</th><th>Vendor</th><th>Stock</th><th>Status</th></tr>';foreach($low as $p)echo '<tr><td>'.esc_html($p->post_title).'</td><td>'.esc_html(get_the_author_meta('display_name',$p->post_author)).'</td><td>'.esc_html(get_post_meta($p->ID,'stock',true)).'</td><td><span style="color:#b32d2e">Needs restocking</span></td></tr>';echo '</table><h2>Low Stock Settings</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_low_stock_settings">'.self::nonce('tager_low_stock_settings').'<input type="number" min="0" name="threshold" value="'.esc_attr(get_option('tager_low_stock_threshold',10)).'"> <button class="button button-primary">Save threshold</button></form></div>';}
  static function low_stock_products(){$th=(int)get_option('tager_low_stock_threshold',10);return get_posts(['post_type'=>'tager_product','post_status'=>'publish','numberposts'=>100,'meta_query'=>[['key'=>'stock','value'=>$th,'compare'=>'<=','type'=>'NUMERIC']]]);}
  static function low_stock_settings(){if(!current_user_can('manage_options'))wp_die('No');check_admin_referer('tager_low_stock_settings');update_option('tager_low_stock_threshold',max(0,(int)($_POST['threshold']??10)));self::audit('low_stock_threshold_updated','settings',0,'Threshold updated');wp_safe_redirect(admin_url('admin.php?page=tager-operations'));exit;}
  static function support_admin(){if(!current_user_can('manage_options'))return;$ts=get_posts(['post_type'=>'tager_ticket','numberposts'=>200,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>Support Tickets</h1><table class="widefat striped"><tr><th>#</th><th>User</th><th>Subject</th><th>Priority</th><th>Status</th><th>Action</th></tr>';foreach($ts as $t){echo '<tr><td>'.$t->ID.'</td><td>'.esc_html(get_the_author_meta('display_name',$t->post_author)).'</td><td>'.esc_html($t->post_title).'<br><small>'.esc_html(wp_trim_words($t->post_content,18)).'</small></td><td>'.esc_html(get_post_meta($t->ID,'priority',true)).'</td><td>'.esc_html(get_post_meta($t->ID,'ticket_status',true)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_ticket_status"><input type="hidden" name="ticket" value="'.$t->ID.'">'.self::nonce('tager_ticket_'.$t->ID).'<select name="status"><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><input name="reply" placeholder="Reply to user"><button class="button button-primary">Update</button></form></td></tr>';}echo '</table></div>';}
  static function ticket_status(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_POST['ticket']??0);check_admin_referer('tager_ticket_'.$id);$status=sanitize_key($_POST['status']??'open');update_post_meta($id,'ticket_status',$status);$p=get_post($id);$reply=sanitize_textarea_field($_POST['reply']??'');if($p&&$reply)self::notify($p->post_author,'تحديث تذكرة الدعم #'.$id,$reply,'support');self::audit('ticket_updated','ticket',$id,'Status '.$status);wp_safe_redirect(admin_url('admin.php?page=tager-support-admin'));exit;}
  static function reviews_admin(){if(!current_user_can('manage_options'))return;$rs=get_posts(['post_type'=>'tager_review','numberposts'=>200,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>Reviews & Ratings</h1><table class="widefat striped"><tr><th>User</th><th>Product</th><th>Rating</th><th>Comment</th><th>Status</th></tr>';foreach($rs as $r){$pid=(int)get_post_meta($r->ID,'product_id',true);echo '<tr><td>'.esc_html(get_the_author_meta('display_name',$r->post_author)).'</td><td>'.esc_html(get_the_title($pid)).'</td><td>'.esc_html(get_post_meta($r->ID,'rating',true)).'/5</td><td>'.esc_html(wp_trim_words($r->post_content,20)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_bulk_product_action"><input type="hidden" name="review" value="'.$r->ID.'">'.self::nonce('tager_review_admin_'.$r->ID).'<select name="decision"><option value="approved">Approve</option><option value="rejected">Reject</option></select><button class="button">Save</button></form></td></tr>';}echo '</table></div>';}
  static function bulk_product_action(){if(!current_user_can('manage_options'))wp_die('No');$rid=(int)($_POST['review']??0);check_admin_referer('tager_review_admin_'.$rid);$d=sanitize_key($_POST['decision']??'rejected');update_post_meta($rid,'review_status',$d);$r=get_post($rid);if($r)self::notify($r->post_author,'حالة التقييم','تم تحديث حالة تقييمك إلى '.$d,'review');self::audit('review_moderated','review',$rid,'Decision '.$d);wp_safe_redirect(admin_url('admin.php?page=tager-reviews-admin'));exit;}
  static function audit_admin(){if(!current_user_can('manage_options'))return;$logs=get_posts(['post_type'=>'tager_audit','numberposts'=>300,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>Audit Log</h1><table class="widefat striped"><tr><th>Date</th><th>User</th><th>Action</th><th>Object</th><th>Details</th><th>IP</th></tr>';foreach($logs as $l)echo '<tr><td>'.esc_html(get_the_date('Y-m-d H:i',$l)).'</td><td>'.esc_html(get_the_author_meta('display_name',$l->post_author)).'</td><td>'.esc_html($l->post_title).'</td><td>'.esc_html(get_post_meta($l->ID,'object_type',true)).' #'.esc_html(get_post_meta($l->ID,'object_id',true)).'</td><td>'.esc_html($l->post_content).'</td><td>'.esc_html(get_post_meta($l->ID,'ip',true)).'</td></tr>';echo '</table></div>';}
  static function vendor_scorecards(){if(!current_user_can('manage_options'))return;$vs=get_users(['role'=>'tager_vendor']);echo '<div class="wrap"><h1>Vendor Scorecards</h1><table class="widefat striped"><tr><th>Vendor</th><th>Store</th><th>Products</th><th>Orders</th><th>Rating</th><th>Risk</th><th>Save</th></tr>';foreach($vs as $v){$products=count(get_posts(['post_type'=>'tager_product','author'=>$v->ID,'numberposts'=>-1]));$orders=count(get_posts(['post_type'=>'tager_vendor_order','author'=>$v->ID,'numberposts'=>-1]));$rating=get_user_meta($v->ID,'vendor_score_rating',true)?:5;$risk=get_user_meta($v->ID,'vendor_risk_level',true)?:'low';echo '<tr><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><td>'.esc_html($v->display_name).'</td><td>'.esc_html(get_user_meta($v->ID,'store_name',true)).'</td><td>'.$products.'</td><td>'.$orders.'</td><td><input type="number" min="1" max="5" step="0.1" name="rating" value="'.esc_attr($rating).'" style="width:70px"></td><td><select name="risk"><option '.selected($risk,'low',false).' value="low">Low</option><option '.selected($risk,'medium',false).' value="medium">Medium</option><option '.selected($risk,'high',false).' value="high">High</option></select></td><td><input type="hidden" name="action" value="tager_vendor_score_save"><input type="hidden" name="vendor" value="'.$v->ID.'">'.self::nonce('tager_vendor_score_'.$v->ID).'<button class="button button-primary">Save</button></td></form></tr>';}echo '</table></div>';}
  static function vendor_score_save(){if(!current_user_can('manage_options'))wp_die('No');$uid=(int)($_POST['vendor']??0);check_admin_referer('tager_vendor_score_'.$uid);update_user_meta($uid,'vendor_score_rating',max(1,min(5,(float)($_POST['rating']??5))));update_user_meta($uid,'vendor_risk_level',sanitize_key($_POST['risk']??'low'));self::audit('vendor_score_updated','vendor',$uid,'Scorecard updated');wp_safe_redirect(admin_url('admin.php?page=tager-vendor-scorecards'));exit;}
}
Tager_V6_Operations::init();
