<?php
/**
 * Plugin Name: Tager Marketplace Pro Enhancements
 * Description: Customer accounts, vendor KYC, granular permissions, advanced products, multi-vendor order splitting, commissions, withdrawals, coupons, notifications and reports.
 * Version: 4.0.0
 */
if (!defined('ABSPATH')) exit;

class Tager_Pro_Enhancements {
    const V = '4.0.0';

    public static function init() {
        add_action('init', [__CLASS__, 'register'], 40);
        add_action('init', [__CLASS__, 'override_shortcodes'], 99);
        add_action('init', [__CLASS__, 'bootstrap'], 120);
        add_action('admin_menu', [__CLASS__, 'admin_menu'], 30);
        add_action('wp_enqueue_scripts', [__CLASS__, 'assets'], 30);

        foreach ([
            'profile_save','address_save','vendor_profile_save','vendor_product_save','vendor_withdrawal',
            'vendor_order_status','wishlist_toggle','coupon_create','coupon_delete','withdrawal_action','vendor_permission_save'
        ] as $a) add_action('admin_post_tager_'.$a, [__CLASS__, $a]);

        add_action('admin_post_nopriv_tager_wishlist_toggle', [__CLASS__, 'wishlist_toggle']);
        add_action('admin_post_nopriv_tager_pro_checkout', [__CLASS__, 'pro_checkout']);
        add_action('admin_post_tager_pro_checkout', [__CLASS__, 'pro_checkout']);
        add_action('admin_post_tager_vendor_kyc', [__CLASS__, 'vendor_kyc']);
        add_action('admin_post_nopriv_tager_vendor_kyc', [__CLASS__, 'vendor_kyc']);
        add_action('admin_post_tager_admin_vendor_review', [__CLASS__, 'admin_vendor_review']);
    }

    public static function register() {
        register_post_type('tager_suborder', [
            'labels'=>['name'=>'Vendor Suborders','singular_name'=>'Vendor Suborder'],
            'public'=>false,'show_ui'=>true,'supports'=>['title','author'],'menu_icon'=>'dashicons-list-view'
        ]);
        register_post_type('tager_withdrawal', [
            'labels'=>['name'=>'Vendor Withdrawals','singular_name'=>'Vendor Withdrawal'],
            'public'=>false,'show_ui'=>true,'supports'=>['title','author'],'menu_icon'=>'dashicons-money-alt'
        ]);
        register_post_type('tager_coupon', [
            'labels'=>['name'=>'Tager Coupons','singular_name'=>'Tager Coupon'],
            'public'=>false,'show_ui'=>false,'supports'=>['title','author']
        ]);
        register_taxonomy('tager_category','tager_product',[
            'labels'=>['name'=>'Product Categories','singular_name'=>'Product Category'],
            'public'=>true,'show_ui'=>true,'hierarchical'=>true,'rewrite'=>['slug'=>'category']
        ]);
    }

    public static function bootstrap() {
        if (get_option('tager_pro_bootstrap') === self::V) return;
        $pages = get_option('tager_pages', []);
        $extras = [
            'wishlist'=>['المفضلة','[tager_pro_wishlist]'],
            'vendor-store'=>['متجر المورد','[tager_pro_vendor_store]'],
            'order-tracking'=>['تتبع الطلب','[tager_pro_tracking]'],
        ];
        foreach ($extras as $slug=>$d) {
            $p=get_page_by_path($slug);
            $pages[$slug]=$p?$p->ID:wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_name'=>$slug,'post_title'=>$d[0],'post_content'=>$d[1]]);
        }
        update_option('tager_pages',$pages);
        if (!get_option('tager_pro_settings')) update_option('tager_pro_settings',[
            'min_withdrawal'=>1000,'withdrawal_days'=>7,'vendor_docs_required'=>1,'allow_vendor_coupons'=>1,
            'allow_vendor_order_status'=>1,'allow_vendor_product_edit'=>1,'allow_vendor_product_delete'=>0,
            'require_email'=>1,'platform_name'=>'Tager','currency'=>'EGP'
        ]);
        update_option('tager_pro_bootstrap',self::V);
    }

    public static function override_shortcodes() {
        remove_shortcode('tager_customer_account'); add_shortcode('tager_customer_account',[__CLASS__,'customer_account']);
        remove_shortcode('tager_vendor_dashboard'); add_shortcode('tager_vendor_dashboard',[__CLASS__,'vendor_dashboard']);
        remove_shortcode('tager_cart'); add_shortcode('tager_cart',[__CLASS__,'cart']);
        remove_shortcode('tager_shop'); add_shortcode('tager_shop',[__CLASS__,'shop']);
        add_shortcode('tager_pro_wishlist',[__CLASS__,'wishlist']);
        add_shortcode('tager_pro_vendor_store',[__CLASS__,'vendor_store']);
        add_shortcode('tager_pro_tracking',[__CLASS__,'tracking']);
    }

    private static function lang(){return (isset($_GET['lang'])&&$_GET['lang']==='en')?'en':'ar';}
    private static function t($ar,$en){return self::lang()==='en'?$en:$ar;}
    private static function pages(){return get_option('tager_pages',[]);}
    private static function url($slug){$p=self::pages();return isset($p[$slug])?get_permalink($p[$slug]):home_url('/'.$slug.'/');}
    private static function pro(){return wp_parse_args(get_option('tager_pro_settings',[]),['min_withdrawal'=>1000,'withdrawal_days'=>7,'vendor_docs_required'=>1,'allow_vendor_coupons'=>1,'allow_vendor_order_status'=>1,'allow_vendor_product_edit'=>1,'allow_vendor_product_delete'=>0]);}
    private static function vendor_ok($uid=0){$uid=$uid?:get_current_user_id();$u=get_userdata($uid);return $u && (in_array('tager_vendor',$u->roles,true)||current_user_can('manage_options')) && get_user_meta($uid,'vendor_status',true)!=='suspended';}
    private static function money($v){return number_format((float)$v,2).' EGP';}
    private static function nonce_field($a){return wp_nonce_field($a,'_wpnonce',true,false);}
    private static function status_badge($s){$map=['pending'=>'warning','approved'=>'success','rejected'=>'danger','suspended'=>'danger','New'=>'info','Confirmed'=>'info','Processing'=>'warning','Shipped'=>'info','Completed'=>'success','Cancelled'=>'danger'];return '<span class="tag '.($map[$s]??'info').'">'.esc_html($s).'</span>';}

    public static function assets(){
        wp_add_inline_style('tager-style', self::css());
        wp_add_inline_script('tager-js', self::js(), 'after');
    }

    public static function shop(){
        $q=sanitize_text_field($_GET['q']??''); $cat=(int)($_GET['cat']??0); $sort=sanitize_key($_GET['sort']??'newest');
        $args=['post_type'=>'tager_product','post_status'=>'publish','posts_per_page'=>24,'s'=>$q,'meta_query'=>[['key'=>'approval_status','value'=>'approved']]];
        if($cat)$args['tax_query']=[['taxonomy'=>'tager_category','field'=>'term_id','terms'=>$cat]];
        if($sort==='price_low'){$args['meta_key']='retail_price';$args['orderby']='meta_value_num';$args['order']='ASC';}
        elseif($sort==='price_high'){$args['meta_key']='retail_price';$args['orderby']='meta_value_num';$args['order']='DESC';}
        $terms=get_terms(['taxonomy'=>'tager_category','hide_empty'=>false]);
        ob_start(); ?>
        <section class="page-hero"><h1><?php echo esc_html(self::t('المنتجات','Products'));?></h1><p><?php echo esc_html(self::t('قطاعي، جملة، وجملة الجملة في مكان واحد','Retail, wholesale and bulk wholesale in one place'));?></p></section>
        <form class="market-filters" method="get">
          <input name="q" value="<?php echo esc_attr($q);?>" placeholder="<?php echo esc_attr(self::t('ابحث باسم المنتج','Search products'));?>">
          <select name="cat"><option value="0"><?php echo esc_html(self::t('كل الأقسام','All categories'));?></option><?php foreach($terms as $tm)echo '<option value="'.$tm->term_id.'" '.selected($cat,$tm->term_id,false).'>'.esc_html($tm->name).'</option>';?></select>
          <select name="sort"><option value="newest"><?php echo esc_html(self::t('الأحدث','Newest'));?></option><option value="price_low" <?php selected($sort,'price_low');?>><?php echo esc_html(self::t('السعر: الأقل','Price: low to high'));?></option><option value="price_high" <?php selected($sort,'price_high');?>><?php echo esc_html(self::t('السعر: الأعلى','Price: high to low'));?></option></select>
          <button class="btn primary"><?php echo esc_html(self::t('بحث','Search'));?></button>
        </form>
        <?php echo self::grid($args); return ob_get_clean();
    }

    private static function grid($args){$q=new WP_Query($args);ob_start();echo '<div class="product-grid">';if(!$q->have_posts())echo '<div class="empty-state">'.esc_html(self::t('لا توجد منتجات مطابقة','No matching products')).'</div>';while($q->have_posts()){$q->the_post();$id=get_the_ID();$name=self::lang()==='en'?(get_post_meta($id,'name_en',true)?:get_the_title()):get_the_title();$vendor=(int)get_post_field('post_author',$id);$store=get_user_meta($vendor,'store_name',true)?:get_the_author_meta('display_name',$vendor);$r=(float)get_post_meta($id,'retail_price',true);$w=(float)get_post_meta($id,'wholesale_price',true);$b=(float)get_post_meta($id,'bulk_price',true);$wm=(int)get_post_meta($id,'wholesale_min',true);$bm=(int)get_post_meta($id,'bulk_min',true);$max=(int)(get_post_meta($id,'max_qty',true)?:9999);$stock=(int)get_post_meta($id,'stock',true);echo '<article class="product-card"><div class="product-image">'.(has_post_thumbnail()?get_the_post_thumbnail($id,'medium'):'<span>📦</span>').'<button class="wish-btn" onclick="tagerWish('.$id.')">♡</button></div><div class="product-body"><small class="vendor-name">'.esc_html($store).'</small><h3>'.esc_html($name).'</h3><div class="price"><b>'.self::money($r).'</b></div><div class="tiers"><span>'.esc_html(self::t('جملة','Wholesale')).': '.self::money($w).' / '.$wm.'+</span><span>'.esc_html(self::t('جملة الجملة','Bulk')).': '.self::money($b).' / '.$bm.'+</span></div><div class="stock-line">'.esc_html(self::t('المتاح','Stock')).': '.$stock.'</div><div class="qty-row"><input type="number" min="1" max="'.esc_attr(min($max,$stock)).'" value="1" id="qty-'.$id.'"><button class="btn primary" onclick="tagerAdd('.$id.',\''.esc_js($name).'\')">'.esc_html(self::t('أضف للسلة','Add to cart')).'</button></div></div></article>'; }wp_reset_postdata();echo '</div>';return ob_get_clean();}

    public static function customer_account(){
        if(!is_user_logged_in()) return '<section class="form-wrap"><h1>'.esc_html(self::t('تسجيل الدخول','Sign in')).'</h1>'.wp_login_form(['echo'=>false,'redirect'=>self::url('my-account')]).'<p><a href="'.esc_url(wp_lostpassword_url()).'">'.esc_html(self::t('نسيت كلمة المرور؟','Forgot password?')).'</a></p><a href="'.esc_url(self::url('customer-register')).'">'.esc_html(self::t('إنشاء حساب جديد','Create account')).'</a></section>';
        $u=wp_get_current_user(); if(in_array('tager_vendor',$u->roles,true)||in_array('tager_vendor_pending',$u->roles,true))return '<section class="form-wrap"><a class="btn primary" href="'.esc_url(self::url('vendor-dashboard')).'">'.esc_html(self::t('فتح لوحة المورد','Open vendor dashboard')).'</a></section>';
        $tab=sanitize_key($_GET['tab']??'overview'); ob_start(); ?>
        <section class="dash-shell"><aside class="dash-menu"><h3><?php echo esc_html($u->display_name);?></h3><?php foreach(['overview'=>['نظرة عامة','Overview'],'orders'=>['طلباتي','My orders'],'addresses'=>['العناوين','Addresses'],'wishlist'=>['المفضلة','Wishlist'],'profile'=>['الملف الشخصي','Profile']] as $k=>$v)echo '<a class="'.($tab===$k?'active':'').'" href="'.esc_url(add_query_arg('tab',$k,self::url('my-account'))).'">'.esc_html(self::t($v[0],$v[1])).'</a>';?><a href="<?php echo esc_url(wp_logout_url(home_url()));?>"><?php echo esc_html(self::t('تسجيل الخروج','Sign out'));?></a></aside><main class="dash-content">
        <?php if($tab==='orders')self::customer_orders($u->ID);elseif($tab==='addresses')self::addresses($u->ID);elseif($tab==='wishlist')echo do_shortcode('[tager_pro_wishlist]');elseif($tab==='profile')self::profile_form($u);else self::customer_overview($u->ID);?>
        </main></section><?php return ob_get_clean();
    }

    private static function customer_overview($uid){$orders=get_posts(['post_type'=>'tager_order','author'=>$uid,'numberposts'=>-1]);$spent=0;foreach($orders as $o)$spent+=(float)get_post_meta($o->ID,'total',true);echo '<h1>'.esc_html(self::t('مرحبًا بك','Welcome')).'</h1><div class="stat-grid"><div><b>'.count($orders).'</b><span>'.esc_html(self::t('إجمالي الطلبات','Total orders')).'</span></div><div><b>'.self::money($spent).'</b><span>'.esc_html(self::t('إجمالي المشتريات','Total spent')).'</span></div><div><b>'.count((array)get_user_meta($uid,'tager_wishlist',true)).'</b><span>'.esc_html(self::t('المفضلة','Wishlist')).'</span></div></div>';}
    private static function customer_orders($uid){$orders=get_posts(['post_type'=>'tager_order','author'=>$uid,'numberposts'=>-1]);echo '<h2>'.esc_html(self::t('طلباتي','My orders')).'</h2><div class="table-wrap"><table><tr><th>#</th><th>'.esc_html(self::t('التاريخ','Date')).'</th><th>'.esc_html(self::t('الإجمالي','Total')).'</th><th>'.esc_html(self::t('الحالة','Status')).'</th></tr>';foreach($orders as $o)echo '<tr><td>'.$o->ID.'</td><td>'.esc_html(get_the_date('', $o)).'</td><td>'.self::money(get_post_meta($o->ID,'total',true)).'</td><td>'.self::status_badge(get_post_meta($o->ID,'order_status',true)).'</td></tr>';echo '</table></div>';}
    private static function addresses($uid){$a=(array)get_user_meta($uid,'tager_addresses',true);echo '<h2>'.esc_html(self::t('عناويني','My addresses')).'</h2>';foreach($a as $i=>$x)echo '<div class="address-card"><b>'.esc_html($x['label']??'').'</b><p>'.esc_html($x['address']??'').'</p><small>'.esc_html($x['phone']??'').'</small></div>';echo '<form class="form-grid" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_address_save">'.self::nonce_field('tager_address_save').'<input name="label" placeholder="'.esc_attr(self::t('اسم العنوان: المنزل','Label: Home')).'" required><input name="phone" placeholder="'.esc_attr(self::t('الهاتف','Phone')).'" required><textarea name="address" placeholder="'.esc_attr(self::t('العنوان بالتفصيل','Full address')).'" required></textarea><button class="btn primary">'.esc_html(self::t('إضافة العنوان','Add address')).'</button></form>';}
    private static function profile_form($u){echo '<h2>'.esc_html(self::t('الملف الشخصي','Profile')).'</h2><form class="form-grid" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_profile_save">'.self::nonce_field('tager_profile_save').'<input name="display_name" value="'.esc_attr($u->display_name).'" required><input name="email" type="email" value="'.esc_attr($u->user_email).'" required><input name="phone" value="'.esc_attr(get_user_meta($u->ID,'phone',true)).'" placeholder="Phone"><input name="password" type="password" placeholder="'.esc_attr(self::t('كلمة مرور جديدة (اختياري)','New password (optional)')).'"><button class="btn primary">'.esc_html(self::t('حفظ','Save')).'</button></form>';}
    public static function profile_save(){if(!is_user_logged_in())wp_die('Login');check_admin_referer('tager_profile_save');$id=get_current_user_id();$data=['ID'=>$id,'display_name'=>sanitize_text_field($_POST['display_name']??''),'user_email'=>sanitize_email($_POST['email']??'')];if(!empty($_POST['password']))$data['user_pass']=$_POST['password'];wp_update_user($data);update_user_meta($id,'phone',sanitize_text_field($_POST['phone']??''));wp_safe_redirect(add_query_arg('tab','profile',self::url('my-account')));exit;}
    public static function address_save(){if(!is_user_logged_in())wp_die('Login');check_admin_referer('tager_address_save');$id=get_current_user_id();$a=(array)get_user_meta($id,'tager_addresses',true);$a[]=['label'=>sanitize_text_field($_POST['label']??''),'phone'=>sanitize_text_field($_POST['phone']??''),'address'=>sanitize_textarea_field($_POST['address']??'')];update_user_meta($id,'tager_addresses',$a);wp_safe_redirect(add_query_arg('tab','addresses',self::url('my-account')));exit;}

    public static function vendor_dashboard(){
        if(!is_user_logged_in())return '<section class="form-wrap"><h1>'.esc_html(self::t('دخول المورد','Vendor sign in')).'</h1>'.wp_login_form(['echo'=>false,'redirect'=>self::url('vendor-dashboard')]).'</section>';
        $u=wp_get_current_user();$vstatus=get_user_meta($u->ID,'vendor_status',true);
        if(in_array('tager_vendor_pending',$u->roles,true)||$vstatus==='pending'||$vstatus==='suspended')return self::vendor_pending_screen($u,$vstatus);
        if(!self::vendor_ok($u->ID))return '<section class="form-wrap"><p>'.esc_html(self::t('هذا الحساب ليس حساب مورد','This is not a vendor account')).'</p></section>';
        $tab=sanitize_key($_GET['tab']??'overview');ob_start(); ?>
        <section class="dash-shell"><aside class="dash-menu"><h3><?php echo esc_html(get_user_meta($u->ID,'store_name',true)?:$u->display_name);?></h3><?php foreach(['overview'=>['الرئيسية','Overview'],'products'=>['المنتجات','Products'],'add-product'=>['إضافة منتج','Add product'],'orders'=>['الطلبات','Orders'],'earnings'=>['الأرباح','Earnings'],'withdrawals'=>['سحب الأرباح','Withdrawals'],'coupons'=>['الكوبونات','Coupons'],'settings'=>['إعدادات المتجر','Store settings']] as $k=>$v)echo '<a class="'.($tab===$k?'active':'').'" href="'.esc_url(add_query_arg('tab',$k,self::url('vendor-dashboard'))).'">'.esc_html(self::t($v[0],$v[1])).'</a>';?><a href="<?php echo esc_url(wp_logout_url(home_url()));?>"><?php echo esc_html(self::t('تسجيل الخروج','Sign out'));?></a></aside><main class="dash-content"><?php
        if($tab==='products')self::vendor_products($u->ID);elseif($tab==='add-product')self::vendor_product_form($u->ID);elseif($tab==='orders')self::vendor_orders($u->ID);elseif($tab==='earnings')self::vendor_earnings($u->ID);elseif($tab==='withdrawals')self::vendor_withdrawals($u->ID);elseif($tab==='coupons')self::vendor_coupons($u->ID);elseif($tab==='settings')self::vendor_settings($u);else self::vendor_overview($u->ID);?></main></section><?php return ob_get_clean();
    }

    private static function vendor_pending_screen($u,$status){$docs=get_user_meta($u->ID,'kyc_status',true);ob_start();?><section class="form-wrap"><h1><?php echo esc_html(self::t('طلب المورد','Vendor application'));?></h1><p><?php echo self::status_badge($status?:'pending');?></p><p><?php echo esc_html(self::t('ارفع المستندات المطلوبة لإتمام المراجعة.','Upload required documents to complete the review.'));?></p><form class="form-grid" method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_vendor_kyc"><?php echo self::nonce_field('tager_vendor_kyc');?><label><?php echo esc_html(self::t('السجل التجاري','Commercial registration'));?><input type="file" name="commercial_file" accept=".pdf,.jpg,.jpeg,.png"></label><label><?php echo esc_html(self::t('البطاقة الضريبية/الهوية','Tax card / ID'));?><input type="file" name="identity_file" accept=".pdf,.jpg,.jpeg,.png"></label><input name="bank_name" placeholder="<?php echo esc_attr(self::t('اسم البنك','Bank name'));?>"><input name="iban" placeholder="IBAN"><button class="btn primary"><?php echo esc_html(self::t('إرسال للمراجعة','Submit for review'));?></button></form><small><?php echo esc_html($docs?self::t('تم رفع المستندات','Documents uploaded'):self::t('لم تُرفع المستندات بعد','Documents not uploaded yet'));?></small></section><?php return ob_get_clean();}
    public static function vendor_kyc(){if(!is_user_logged_in())wp_die('Login');check_admin_referer('tager_vendor_kyc');$uid=get_current_user_id();require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';foreach(['commercial_file','identity_file'] as $f){if(!empty($_FILES[$f]['name'])){$att=media_handle_upload($f,0);if(!is_wp_error($att))update_user_meta($uid,$f.'_id',$att);}}update_user_meta($uid,'bank_name',sanitize_text_field($_POST['bank_name']??''));update_user_meta($uid,'iban',sanitize_text_field($_POST['iban']??''));update_user_meta($uid,'kyc_status','submitted');wp_safe_redirect(self::url('vendor-dashboard'));exit;}
    private static function vendor_overview($uid){$products=get_posts(['post_type'=>'tager_product','author'=>$uid,'post_status'=>['publish','pending','draft'],'numberposts'=>-1]);$subs=get_posts(['post_type'=>'tager_suborder','author'=>$uid,'numberposts'=>-1]);$sales=0;$pending=0;foreach($subs as $s){$sales+=(float)get_post_meta($s->ID,'vendor_net',true);if(get_post_meta($s->ID,'suborder_status',true)!=='Completed')$pending++;}echo '<h1>'.esc_html(self::t('لوحة المورد','Vendor dashboard')).'</h1><div class="stat-grid"><div><b>'.count($products).'</b><span>'.esc_html(self::t('المنتجات','Products')).'</span></div><div><b>'.count($subs).'</b><span>'.esc_html(self::t('الطلبات','Orders')).'</span></div><div><b>'.self::money($sales).'</b><span>'.esc_html(self::t('صافي الأرباح','Net earnings')).'</span></div><div><b>'.$pending.'</b><span>'.esc_html(self::t('طلبات جارية','Open orders')).'</span></div></div>';}
    private static function vendor_products($uid){$ps=get_posts(['post_type'=>'tager_product','author'=>$uid,'post_status'=>['publish','pending','draft'],'numberposts'=>-1]);echo '<h2>'.esc_html(self::t('منتجاتي','My products')).'</h2><div class="table-wrap"><table><tr><th>'.esc_html(self::t('المنتج','Product')).'</th><th>'.esc_html(self::t('السعر','Price')).'</th><th>'.esc_html(self::t('المخزون','Stock')).'</th><th>'.esc_html(self::t('الحالة','Status')).'</th></tr>';foreach($ps as $p)echo '<tr><td>'.esc_html($p->post_title).'</td><td>'.self::money(get_post_meta($p->ID,'retail_price',true)).'</td><td>'.(int)get_post_meta($p->ID,'stock',true).'</td><td>'.self::status_badge(get_post_meta($p->ID,'approval_status',true)?:$p->post_status).'</td></tr>';echo '</table></div>';}
    private static function vendor_product_form($uid){$terms=get_terms(['taxonomy'=>'tager_category','hide_empty'=>false]);echo '<h2>'.esc_html(self::t('إضافة منتج','Add product')).'</h2><form class="form-grid two" method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_vendor_product_save">'.self::nonce_field('tager_vendor_product_save').'<input name="title_ar" placeholder="اسم المنتج بالعربية" required><input name="title_en" placeholder="Product name in English"><textarea name="description_ar" placeholder="الوصف بالعربية" required></textarea><textarea name="description_en" placeholder="English description"></textarea><select name="category"><option value="0">'.esc_html(self::t('اختر القسم','Choose category')).'</option>';foreach($terms as $t)echo '<option value="'.$t->term_id.'">'.esc_html($t->name).'</option>';echo '</select><input name="sku" placeholder="SKU"><input type="number" step="0.01" name="retail" placeholder="سعر القطاعي" required><input type="number" step="0.01" name="wholesale" placeholder="سعر الجملة" required><input type="number" step="0.01" name="bulk" placeholder="سعر جملة الجملة" required><input type="number" name="wholesale_min" placeholder="حد الجملة الأدنى" required><input type="number" name="bulk_min" placeholder="حد جملة الجملة الأدنى" required><input type="number" name="max_qty" placeholder="الحد الأقصى للطلب" required><input type="number" name="stock" placeholder="المخزون" required><input type="number" step="0.01" name="weight" placeholder="الوزن كجم"><input name="dimensions" placeholder="الأبعاد"><label>الصورة الرئيسية<input type="file" name="product_image" accept="image/*"></label><label>صور إضافية<input type="file" name="gallery[]" accept="image/*" multiple></label><button class="btn primary">'.esc_html(self::t('إرسال للمراجعة','Submit for review')).'</button></form>';}
    public static function vendor_product_save(){if(!self::vendor_ok())wp_die('Not allowed');check_admin_referer('tager_vendor_product_save');$uid=get_current_user_id();$id=wp_insert_post(['post_type'=>'tager_product','post_status'=>'pending','post_author'=>$uid,'post_title'=>sanitize_text_field($_POST['title_ar']??''),'post_content'=>sanitize_textarea_field($_POST['description_ar']??'')]);$map=['name_en'=>'title_en','description_en'=>'description_en','retail_price'=>'retail','wholesale_price'=>'wholesale','bulk_price'=>'bulk','wholesale_min'=>'wholesale_min','bulk_min'=>'bulk_min','max_qty'=>'max_qty','stock'=>'stock','sku'=>'sku','weight'=>'weight','dimensions'=>'dimensions'];foreach($map as $m=>$f)update_post_meta($id,$m,sanitize_text_field($_POST[$f]??''));update_post_meta($id,'approval_status','pending');if(!empty($_POST['category']))wp_set_object_terms($id,[(int)$_POST['category']],'tager_category');require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';if(!empty($_FILES['product_image']['name'])){$att=media_handle_upload('product_image',$id);if(!is_wp_error($att))set_post_thumbnail($id,$att);}if(!empty($_FILES['gallery']['name'][0])){$ids=[];$files=$_FILES['gallery'];foreach($files['name'] as $i=>$n){if(!$n)continue;$_FILES['tager_gallery_one']=['name'=>$files['name'][$i],'type'=>$files['type'][$i],'tmp_name'=>$files['tmp_name'][$i],'error'=>$files['error'][$i],'size'=>$files['size'][$i]];$att=media_handle_upload('tager_gallery_one',$id);if(!is_wp_error($att))$ids[]=$att;}update_post_meta($id,'gallery_ids',$ids);}wp_safe_redirect(add_query_arg('tab','products',self::url('vendor-dashboard')));exit;}
    private static function vendor_orders($uid){$os=get_posts(['post_type'=>'tager_suborder','author'=>$uid,'numberposts'=>-1]);echo '<h2>'.esc_html(self::t('طلبات المتجر','Store orders')).'</h2><div class="table-wrap"><table><tr><th>#</th><th>'.esc_html(self::t('العميل','Customer')).'</th><th>'.esc_html(self::t('الإجمالي','Total')).'</th><th>'.esc_html(self::t('الحالة','Status')).'</th><th>'.esc_html(self::t('تحديث','Update')).'</th></tr>';foreach($os as $o){$st=get_post_meta($o->ID,'suborder_status',true);echo '<tr><td>'.$o->ID.'</td><td>'.esc_html(get_post_meta($o->ID,'customer_name',true)).'</td><td>'.self::money(get_post_meta($o->ID,'gross_total',true)).'</td><td>'.self::status_badge($st).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_vendor_order_status"><input type="hidden" name="suborder" value="'.$o->ID.'">'.self::nonce_field('tager_vendor_order_'.$o->ID).'<select name="status"><option>Confirmed</option><option>Processing</option><option>Shipped</option><option>Completed</option><option>Cancelled</option></select><button class="btn small">'.esc_html(self::t('حفظ','Save')).'</button></form></td></tr>';}echo '</table></div>';}
    public static function vendor_order_status(){if(!self::vendor_ok())wp_die('No');$id=(int)($_POST['suborder']??0);check_admin_referer('tager_vendor_order_'.$id);if((int)get_post_field('post_author',$id)!==get_current_user_id())wp_die('No');update_post_meta($id,'suborder_status',sanitize_text_field($_POST['status']??'Processing'));wp_safe_redirect(add_query_arg('tab','orders',self::url('vendor-dashboard')));exit;}
    private static function vendor_earnings($uid){$os=get_posts(['post_type'=>'tager_suborder','author'=>$uid,'numberposts'=>-1]);$gross=$commission=$net=0;foreach($os as $o){$gross+=(float)get_post_meta($o->ID,'gross_total',true);$commission+=(float)get_post_meta($o->ID,'platform_commission',true);$net+=(float)get_post_meta($o->ID,'vendor_net',true);}echo '<h2>'.esc_html(self::t('الأرباح','Earnings')).'</h2><div class="stat-grid"><div><b>'.self::money($gross).'</b><span>'.esc_html(self::t('إجمالي المبيعات','Gross sales')).'</span></div><div><b>'.self::money($commission).'</b><span>'.esc_html(self::t('عمولة المنصة','Platform commission')).'</span></div><div><b>'.self::money($net).'</b><span>'.esc_html(self::t('صافي المورد','Vendor net')).'</span></div></div>';}
    private static function available_balance($uid){$os=get_posts(['post_type'=>'tager_suborder','author'=>$uid,'numberposts'=>-1,'meta_key'=>'suborder_status','meta_value'=>'Completed']);$net=0;foreach($os as $o)$net+=(float)get_post_meta($o->ID,'vendor_net',true);$ws=get_posts(['post_type'=>'tager_withdrawal','author'=>$uid,'numberposts'=>-1,'meta_query'=>[['key'=>'withdrawal_status','value'=>['pending','approved','paid'],'compare'=>'IN']]]);foreach($ws as $w)$net-=(float)get_post_meta($w->ID,'amount',true);return max(0,$net);}
    private static function vendor_withdrawals($uid){$bal=self::available_balance($uid);$p=self::pro();$ws=get_posts(['post_type'=>'tager_withdrawal','author'=>$uid,'numberposts'=>-1]);echo '<h2>'.esc_html(self::t('سحب الأرباح','Withdrawals')).'</h2><div class="balance-card"><span>'.esc_html(self::t('الرصيد المتاح','Available balance')).'</span><b>'.self::money($bal).'</b></div><form class="form-grid" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_vendor_withdrawal">'.self::nonce_field('tager_vendor_withdrawal').'<input type="number" step="0.01" min="'.esc_attr($p['min_withdrawal']).'" max="'.esc_attr($bal).'" name="amount" placeholder="'.esc_attr(self::t('المبلغ','Amount')).'" required><button class="btn primary">'.esc_html(self::t('طلب سحب','Request withdrawal')).'</button></form><div class="table-wrap"><table><tr><th>#</th><th>'.esc_html(self::t('المبلغ','Amount')).'</th><th>'.esc_html(self::t('الحالة','Status')).'</th></tr>';foreach($ws as $w)echo '<tr><td>'.$w->ID.'</td><td>'.self::money(get_post_meta($w->ID,'amount',true)).'</td><td>'.self::status_badge(get_post_meta($w->ID,'withdrawal_status',true)).'</td></tr>';echo '</table></div>';}
    public static function vendor_withdrawal(){if(!self::vendor_ok())wp_die('No');check_admin_referer('tager_vendor_withdrawal');$uid=get_current_user_id();$amount=(float)($_POST['amount']??0);$p=self::pro();if($amount<$p['min_withdrawal']||$amount>self::available_balance($uid))wp_die('Invalid amount');$id=wp_insert_post(['post_type'=>'tager_withdrawal','post_status'=>'publish','post_author'=>$uid,'post_title'=>'Withdrawal '.current_time('Ymd-His')]);update_post_meta($id,'amount',$amount);update_post_meta($id,'withdrawal_status','pending');wp_safe_redirect(add_query_arg('tab','withdrawals',self::url('vendor-dashboard')));exit;}
    private static function vendor_coupons($uid){$cs=get_posts(['post_type'=>'tager_coupon','author'=>$uid,'numberposts'=>-1]);echo '<h2>'.esc_html(self::t('الكوبونات','Coupons')).'</h2><form class="form-grid" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_coupon_create">'.self::nonce_field('tager_coupon_create').'<input name="code" placeholder="CODE" required><input type="number" min="1" max="100" name="percent" placeholder="%" required><input type="date" name="expiry"><button class="btn primary">'.esc_html(self::t('إنشاء كوبون','Create coupon')).'</button></form><div class="table-wrap"><table><tr><th>'.esc_html(self::t('الكود','Code')).'</th><th>'.esc_html(self::t('الخصم','Discount')).'</th><th>'.esc_html(self::t('الصلاحية','Expiry')).'</th></tr>';foreach($cs as $c)echo '<tr><td>'.esc_html($c->post_title).'</td><td>'.(float)get_post_meta($c->ID,'percent',true).'%</td><td>'.esc_html(get_post_meta($c->ID,'expiry',true)).'</td></tr>';echo '</table></div>';}
    public static function coupon_create(){if(!self::vendor_ok())wp_die('No');check_admin_referer('tager_coupon_create');$code=strtoupper(sanitize_text_field($_POST['code']??''));if(!$code)wp_die('Code required');$id=wp_insert_post(['post_type'=>'tager_coupon','post_status'=>'publish','post_author'=>get_current_user_id(),'post_title'=>$code]);update_post_meta($id,'percent',min(100,max(1,(float)$_POST['percent'])));update_post_meta($id,'expiry',sanitize_text_field($_POST['expiry']??''));wp_safe_redirect(add_query_arg('tab','coupons',self::url('vendor-dashboard')));exit;}
    public static function coupon_delete(){wp_die('Not implemented');}
    private static function vendor_settings($u){echo '<h2>'.esc_html(self::t('إعدادات المتجر','Store settings')).'</h2><form class="form-grid" method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_vendor_profile_save">'.self::nonce_field('tager_vendor_profile_save').'<input name="store_name" value="'.esc_attr(get_user_meta($u->ID,'store_name',true)).'" placeholder="Store name" required><textarea name="store_description" placeholder="Description">'.esc_textarea(get_user_meta($u->ID,'store_description',true)).'</textarea><input name="support_phone" value="'.esc_attr(get_user_meta($u->ID,'support_phone',true)).'" placeholder="Support phone"><input name="shipping_policy" value="'.esc_attr(get_user_meta($u->ID,'shipping_policy',true)).'" placeholder="Shipping policy"><input name="return_policy" value="'.esc_attr(get_user_meta($u->ID,'return_policy',true)).'" placeholder="Return policy"><label>Store logo<input type="file" name="store_logo" accept="image/*"></label><label>Store banner<input type="file" name="store_banner" accept="image/*"></label><button class="btn primary">'.esc_html(self::t('حفظ','Save')).'</button></form>';}
    public static function vendor_profile_save(){if(!self::vendor_ok())wp_die('No');check_admin_referer('tager_vendor_profile_save');$uid=get_current_user_id();foreach(['store_name','store_description','support_phone','shipping_policy','return_policy'] as $k)update_user_meta($uid,$k,sanitize_textarea_field($_POST[$k]??''));require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';foreach(['store_logo','store_banner'] as $f)if(!empty($_FILES[$f]['name'])){$att=media_handle_upload($f,0);if(!is_wp_error($att))update_user_meta($uid,$f.'_id',$att);}wp_safe_redirect(add_query_arg('tab','settings',self::url('vendor-dashboard')));exit;}

    public static function cart(){ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('سلة المشتريات','Shopping cart'));?></h1></section><div id="tager-cart"></div><form class="checkout-card form-grid" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" onsubmit="return tagerPrepareCheckoutPro()"><input type="hidden" name="action" value="tager_pro_checkout"><input type="hidden" name="cart_json" id="cart_json"><?php echo self::nonce_field('tager_pro_checkout');?><input name="customer_name" value="<?php echo esc_attr(is_user_logged_in()?wp_get_current_user()->display_name:'');?>" placeholder="<?php echo esc_attr(self::t('الاسم الكامل','Full name'));?>" required><input name="phone" placeholder="<?php echo esc_attr(self::t('الهاتف','Phone'));?>" required><input type="email" name="email" value="<?php echo esc_attr(is_user_logged_in()?wp_get_current_user()->user_email:'');?>" placeholder="Email" required><textarea name="address" placeholder="<?php echo esc_attr(self::t('عنوان التوصيل','Delivery address'));?>" required></textarea><input name="coupon" placeholder="<?php echo esc_attr(self::t('كود الخصم','Coupon code'));?>"><select name="payment"><option value="cod"><?php echo esc_html(self::t('الدفع عند الاستلام','Cash on delivery'));?></option><option value="bank"><?php echo esc_html(self::t('تحويل بنكي','Bank transfer'));?></option></select><textarea name="notes" placeholder="<?php echo esc_attr(self::t('ملاحظات الطلب','Order notes'));?>"></textarea><label class="check"><input type="checkbox" required> <?php echo esc_html(self::t('أوافق على الشروط وسياسة الإرجاع','I agree to terms and returns policy'));?></label><button class="btn primary"><?php echo esc_html(self::t('تأكيد الطلب','Place order'));?></button></form><script>document.addEventListener('DOMContentLoaded',tagerRenderCart);</script><?php return ob_get_clean();}
    private static function price($id,$qty){$bm=(int)get_post_meta($id,'bulk_min',true);$wm=(int)get_post_meta($id,'wholesale_min',true);if($qty>=$bm)return(float)get_post_meta($id,'bulk_price',true);if($qty>=$wm)return(float)get_post_meta($id,'wholesale_price',true);return(float)get_post_meta($id,'retail_price',true);}
    public static function pro_checkout(){check_admin_referer('tager_pro_checkout');$base=wp_parse_args(get_option('tager_settings',[]),['customer_must_login'=>1,'commission_percent'=>10]);if($base['customer_must_login']&&!is_user_logged_in())wp_die('Login required');$cart=json_decode(stripslashes($_POST['cart_json']??'[]'),true);if(!$cart||!is_array($cart))wp_die('Empty cart');$group=[];$lines=[];$total=0;foreach($cart as $item){$id=(int)($item['id']??0);$qty=max(1,(int)($item['qty']??1));if(get_post_type($id)!=='tager_product'||get_post_status($id)!=='publish')wp_die('Invalid product');$stock=(int)get_post_meta($id,'stock',true);$max=(int)(get_post_meta($id,'max_qty',true)?:9999);if($qty>$stock||$qty>$max)wp_die('Quantity exceeds stock/limits');$price=self::price($id,$qty);$line=$price*$qty;$vendor=(int)get_post_field('post_author',$id);$row=['id'=>$id,'name'=>get_the_title($id),'qty'=>$qty,'unit_price'=>$price,'line_total'=>$line,'vendor_id'=>$vendor];$lines[]=$row;$group[$vendor][]=$row;$total+=$line;update_post_meta($id,'stock',$stock-$qty);} $uid=get_current_user_id();$coupon=strtoupper(sanitize_text_field($_POST['coupon']??''));$discount=0;if($coupon){$cs=get_posts(['post_type'=>'tager_coupon','title'=>$coupon,'post_status'=>'publish','numberposts'=>1]);if($cs){$c=$cs[0];$exp=get_post_meta($c->ID,'expiry',true);if(!$exp||$exp>=current_time('Y-m-d'))$discount=$total*((float)get_post_meta($c->ID,'percent',true)/100);}}$grand=max(0,$total-$discount);$order=wp_insert_post(['post_type'=>'tager_order','post_status'=>'publish','post_author'=>$uid,'post_title'=>'Order '.current_time('Ymd-His')]);foreach(['customer_name','phone','email','address','payment','notes'] as $k)update_post_meta($order,$k,$k==='email'?sanitize_email($_POST[$k]??''):sanitize_textarea_field($_POST[$k]??''));update_post_meta($order,'items',$lines);update_post_meta($order,'subtotal',$total);update_post_meta($order,'discount',$discount);update_post_meta($order,'total',$grand);update_post_meta($order,'order_status','New');update_post_meta($order,'tracking_code','TGR-'.$order.'-'.wp_rand(1000,9999));$rate=(float)$base['commission_percent'];foreach($group as $vendor=>$vlines){$gross=array_sum(array_column($vlines,'line_total'));$comm=$gross*$rate/100;$sub=wp_insert_post(['post_type'=>'tager_suborder','post_status'=>'publish','post_author'=>$vendor,'post_title'=>'Vendor order '.$order.'-'.$vendor]);update_post_meta($sub,'parent_order',$order);update_post_meta($sub,'items',$vlines);update_post_meta($sub,'gross_total',$gross);update_post_meta($sub,'platform_commission',$comm);update_post_meta($sub,'vendor_net',$gross-$comm);update_post_meta($sub,'suborder_status','New');update_post_meta($sub,'customer_name',sanitize_text_field($_POST['customer_name']??''));}wp_safe_redirect(add_query_arg(['msg'=>'order_done','order'=>$order],self::url('my-account')));exit;}

    public static function wishlist(){if(!is_user_logged_in())return '<div class="notice">'.esc_html(self::t('سجل الدخول لاستخدام المفضلة','Sign in to use wishlist')).'</div>';$ids=array_filter(array_map('intval',(array)get_user_meta(get_current_user_id(),'tager_wishlist',true)));return '<h2>'.esc_html(self::t('المفضلة','Wishlist')).'</h2>'.self::grid(['post_type'=>'tager_product','post__in'=>$ids?:[0],'post_status'=>'publish','posts_per_page'=>50]);}
    public static function wishlist_toggle(){if(!is_user_logged_in())wp_send_json_error(['login'=>true]);check_ajax_referer('tager_wish','nonce');$id=(int)($_POST['product']??0);$uid=get_current_user_id();$w=(array)get_user_meta($uid,'tager_wishlist',true);if(in_array($id,$w,true))$w=array_values(array_diff($w,[$id]));else$w[]=$id;update_user_meta($uid,'tager_wishlist',$w);wp_send_json_success(['count'=>count($w)]);}
    public static function vendor_store(){return '<section class="page-hero"><h1>'.esc_html(self::t('متاجر الموردين','Vendor stores')).'</h1></section>';}
    public static function tracking(){ob_start();$code=sanitize_text_field($_GET['tracking']??'');?><section class="form-wrap"><h1><?php echo esc_html(self::t('تتبع الطلب','Track order'));?></h1><form method="get"><input name="tracking" value="<?php echo esc_attr($code);?>" placeholder="TGR-..."><button class="btn primary"><?php echo esc_html(self::t('تتبع','Track'));?></button></form><?php if($code){$os=get_posts(['post_type'=>'tager_order','numberposts'=>1,'meta_key'=>'tracking_code','meta_value'=>$code]);echo $os?'<p>'.self::status_badge(get_post_meta($os[0]->ID,'order_status',true)).'</p>':'<p>'.esc_html(self::t('رقم التتبع غير صحيح','Tracking code not found')).'</p>';}?></section><?php return ob_get_clean();}

    public static function admin_menu(){add_submenu_page('tager-control','Vendor Applications','Vendor Applications','manage_options','tager-vendor-applications',[__CLASS__,'admin_vendor_applications']);add_submenu_page('tager-control','Withdrawals','Withdrawals','manage_options','tager-withdrawals',[__CLASS__,'admin_withdrawals']);add_submenu_page('tager-control','Reports','Reports','manage_options','tager-reports',[__CLASS__,'admin_reports']);}
    public static function admin_vendor_applications(){if(!current_user_can('manage_options'))return;$users=get_users(['role__in'=>['tager_vendor_pending','tager_vendor']]);echo '<div class="wrap"><h1>Vendor Applications & KYC</h1><table class="widefat striped"><tr><th>Vendor</th><th>Store</th><th>KYC</th><th>Bank / IBAN</th><th>Documents</th><th>Review</th></tr>';foreach($users as $u){$c=(int)get_user_meta($u->ID,'commercial_file_id',true);$i=(int)get_user_meta($u->ID,'identity_file_id',true);echo '<tr><td>'.esc_html($u->display_name).'<br>'.esc_html($u->user_email).'</td><td>'.esc_html(get_user_meta($u->ID,'store_name',true)).'</td><td>'.esc_html(get_user_meta($u->ID,'kyc_status',true)?:'not submitted').'</td><td>'.esc_html(get_user_meta($u->ID,'bank_name',true)).'<br>'.esc_html(get_user_meta($u->ID,'iban',true)).'</td><td>'.($c?'<a target="_blank" href="'.esc_url(wp_get_attachment_url($c)).'">Commercial</a> ':'').($i?'<a target="_blank" href="'.esc_url(wp_get_attachment_url($i)).'">Identity</a>':'').'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_admin_vendor_review"><input type="hidden" name="user" value="'.$u->ID.'">'.self::nonce_field('tager_admin_vendor_'.$u->ID).'<select name="decision"><option value="approve">Approve</option><option value="reject">Reject</option><option value="suspend">Suspend</option></select><input name="note" placeholder="Reason / note"><button class="button button-primary">Save</button></form></td></tr>';}echo '</table></div>';}
    public static function admin_vendor_review(){if(!current_user_can('manage_options'))wp_die('No');$uid=(int)($_POST['user']??0);check_admin_referer('tager_admin_vendor_'.$uid);$d=sanitize_key($_POST['decision']??'');$u=new WP_User($uid);if($d==='approve'){$u->set_role('tager_vendor');update_user_meta($uid,'vendor_status','approved');update_user_meta($uid,'kyc_status','approved');}elseif($d==='suspend'){$u->set_role('tager_vendor_pending');update_user_meta($uid,'vendor_status','suspended');}else{$u->set_role('tager_vendor_pending');update_user_meta($uid,'vendor_status','rejected');update_user_meta($uid,'kyc_status','rejected');}update_user_meta($uid,'admin_review_note',sanitize_textarea_field($_POST['note']??''));wp_safe_redirect(admin_url('admin.php?page=tager-vendor-applications'));exit;}
    public static function admin_withdrawals(){$ws=get_posts(['post_type'=>'tager_withdrawal','numberposts'=>-1]);echo '<div class="wrap"><h1>Vendor Withdrawals</h1><table class="widefat striped"><tr><th>#</th><th>Vendor</th><th>Amount</th><th>Status</th><th>Action</th></tr>';foreach($ws as $w)echo '<tr><td>'.$w->ID.'</td><td>'.esc_html(get_the_author_meta('display_name',$w->post_author)).'</td><td>'.self::money(get_post_meta($w->ID,'amount',true)).'</td><td>'.esc_html(get_post_meta($w->ID,'withdrawal_status',true)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_withdrawal_action"><input type="hidden" name="withdrawal" value="'.$w->ID.'">'.self::nonce_field('tager_withdrawal_'.$w->ID).'<select name="status"><option>approved</option><option>paid</option><option>rejected</option></select><button class="button">Update</button></form></td></tr>';echo '</table></div>';}
    public static function withdrawal_action(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_POST['withdrawal']??0);check_admin_referer('tager_withdrawal_'.$id);update_post_meta($id,'withdrawal_status',sanitize_key($_POST['status']??'approved'));wp_safe_redirect(admin_url('admin.php?page=tager-withdrawals'));exit;}
    public static function vendor_permission_save(){wp_die('Not implemented');}
    public static function admin_reports(){$orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1]);$sales=0;$discount=0;foreach($orders as $o){$sales+=(float)get_post_meta($o->ID,'total',true);$discount+=(float)get_post_meta($o->ID,'discount',true);} $subs=get_posts(['post_type'=>'tager_suborder','numberposts'=>-1]);$comm=0;foreach($subs as $s)$comm+=(float)get_post_meta($s->ID,'platform_commission',true);echo '<div class="wrap"><h1>Marketplace Reports</h1><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px"><div class="postbox" style="padding:20px"><b>Total orders</b><h2>'.count($orders).'</h2></div><div class="postbox" style="padding:20px"><b>Gross sales</b><h2>'.self::money($sales).'</h2></div><div class="postbox" style="padding:20px"><b>Platform commission</b><h2>'.self::money($comm).'</h2></div><div class="postbox" style="padding:20px"><b>Discounts</b><h2>'.self::money($discount).'</h2></div></div></div>';}

    private static function js(){return "
    window.tagerPrepareCheckoutPro=function(){var c=tagerCart();if(!c.length){alert('".esc_js(self::t('السلة فارغة','Cart is empty'))."');return false;}document.getElementById('cart_json').value=JSON.stringify(c);return true;};
    window.tagerWish=function(id){if(!window.tagerWishData){alert('".esc_js(self::t('سجل الدخول أولًا','Please sign in first'))."');return;}var f=new FormData();f.append('action','tager_wishlist_toggle');f.append('product',id);f.append('nonce',tagerWishData.nonce);fetch(tagerWishData.ajax,{method:'POST',body:f}).then(r=>r.json()).then(x=>alert(x.success?'".esc_js(self::t('تم تحديث المفضلة','Wishlist updated'))."':'".esc_js(self::t('تعذر التنفيذ','Unable to update'))."'));};";}
    private static function css(){return "
    .dash-shell{display:grid;grid-template-columns:240px 1fr;gap:24px;margin:24px 0}.dash-menu{background:#103b2a;color:#fff;border-radius:18px;padding:18px;display:flex;flex-direction:column;gap:6px;align-self:start;position:sticky;top:20px}.dash-menu h3{color:#fff;margin:0 0 12px}.dash-menu a{color:#fff;text-decoration:none;padding:11px;border-radius:10px}.dash-menu a:hover,.dash-menu a.active{background:rgba(255,255,255,.15)}.dash-content{min-width:0}.stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:18px 0}.stat-grid>div,.balance-card,.address-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px;box-shadow:0 8px 24px rgba(0,0,0,.04)}.stat-grid b,.balance-card b{display:block;font-size:24px;margin-bottom:6px}.market-filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px;margin:20px 0}.market-filters input,.market-filters select,.form-grid input,.form-grid select,.form-grid textarea{width:100%;padding:12px;border:1px solid #d7ddd9;border-radius:10px;background:#fff}.form-grid{display:grid;gap:12px}.form-grid.two{grid-template-columns:1fr 1fr}.form-grid textarea{min-height:100px}.tag{display:inline-block;padding:4px 9px;border-radius:999px;font-size:12px}.tag.success{background:#dcfce7;color:#166534}.tag.warning{background:#fef3c7;color:#92400e}.tag.danger{background:#fee2e2;color:#991b1b}.tag.info{background:#dbeafe;color:#1e40af}.wish-btn{position:absolute;top:10px;left:10px;border:0;background:#fff;border-radius:50%;width:36px;height:36px;font-size:22px;cursor:pointer}.product-image{position:relative}.vendor-name{color:#6b7280}.stock-line{font-size:12px;color:#4b5563;margin:8px 0}.checkout-card{max-width:760px;margin:24px auto;background:#fff;border:1px solid #e5e7eb;padding:24px;border-radius:18px}.balance-card{display:flex;justify-content:space-between;align-items:center}.btn.small{padding:7px 10px}.empty-state{grid-column:1/-1;padding:40px;text-align:center;background:#fff;border-radius:16px}.check{display:flex;gap:8px;align-items:center}.check input{width:auto}@media(max-width:850px){.dash-shell{grid-template-columns:1fr}.dash-menu{position:static;display:grid;grid-template-columns:repeat(2,1fr)}.stat-grid{grid-template-columns:repeat(2,1fr)}.market-filters,.form-grid.two{grid-template-columns:1fr}}";}
}
Tager_Pro_Enhancements::init();
add_action('wp_enqueue_scripts', function(){wp_localize_script('tager-js','tagerWishData',['ajax'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('tager_wish')]);},40);
add_action('wp_ajax_tager_wishlist_toggle',['Tager_Pro_Enhancements','wishlist_toggle']);
add_action('wp_ajax_nopriv_tager_wishlist_toggle',['Tager_Pro_Enhancements','wishlist_toggle']);
