<?php
/**
 * Plugin Name: Tager Growth & Security Suite V9
 * Description: PWA, advanced marketplace search, vendor SLA, disputes, favorites alerts, saved carts, login protection, privacy tools, API endpoints and executive KPIs.
 * Version: 9.0.0
 */
if (!defined('ABSPATH')) exit;

class Tager_V9_Growth_Security {
    const V='9.0.0';
    public static function init(){
        add_action('init',[__CLASS__,'register'],70);
        add_action('init',[__CLASS__,'bootstrap'],180);
        add_action('admin_menu',[__CLASS__,'admin_menu'],60);
        add_action('wp_enqueue_scripts',[__CLASS__,'assets'],80);
        add_action('rest_api_init',[__CLASS__,'rest']);
        add_filter('login_errors',[__CLASS__,'generic_login_error']);
        add_filter('authenticate',[__CLASS__,'rate_limit_login'],35,3);
        add_action('wp_login_failed',[__CLASS__,'record_failed_login']);
        add_action('wp_login',[__CLASS__,'clear_failed_login'],10,2);
        add_action('wp_head',[__CLASS__,'pwa_head']);
        add_action('template_redirect',[__CLASS__,'serve_pwa_files']);
        add_shortcode('tager_v9_search',[__CLASS__,'search_page']);
        add_shortcode('tager_v9_disputes',[__CLASS__,'disputes_page']);
        add_shortcode('tager_v9_saved_lists',[__CLASS__,'saved_lists_page']);
        add_shortcode('tager_v9_privacy',[__CLASS__,'privacy_page']);
        add_shortcode('tager_v9_vendor_scorecard',[__CLASS__,'vendor_scorecard']);
        foreach(['dispute_create','dispute_reply','dispute_status','saved_list_add','saved_list_delete','privacy_export','privacy_delete','vendor_sla_save'] as $a){
            add_action('admin_post_tager_v9_'.$a,[__CLASS__,$a]);
        }
    }
    public static function register(){
        register_post_type('tager_dispute',['labels'=>['name'=>'Marketplace Disputes','singular_name'=>'Dispute'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor','author']]);
        register_post_type('tager_dispute_reply',['labels'=>['name'=>'Dispute Replies','singular_name'=>'Dispute Reply'],'public'=>false,'show_ui'=>false,'supports'=>['editor','author']]);
        register_post_type('tager_saved_list',['labels'=>['name'=>'Saved Lists','singular_name'=>'Saved List'],'public'=>false,'show_ui'=>false,'supports'=>['title','author']]);
        register_post_type('tager_security_log',['labels'=>['name'=>'Security Logs','singular_name'=>'Security Log'],'public'=>false,'show_ui'=>false,'supports'=>['title','editor']]);
    }
    private static function pages(){return get_option('tager_pages',[]);} 
    private static function url($slug){$p=self::pages();return !empty($p[$slug])?get_permalink($p[$slug]):home_url('/'.$slug.'/');}
    private static function t($ar,$en){return (isset($_GET['lang'])&&$_GET['lang']==='en')?$en:$ar;}
    private static function nonce($a){return wp_nonce_field($a,'_wpnonce',true,false);}
    private static function money($v){return number_format((float)$v,2).' EGP';}
    public static function bootstrap(){
        if(get_option('tager_v9_bootstrap')===self::V)return;
        $pages=self::pages();
        $extra=[
            'market-search'=>['بحث السوق','[tager_v9_search]'],
            'disputes'=>['النزاعات','[tager_v9_disputes]'],
            'saved-lists'=>['القوائم المحفوظة','[tager_v9_saved_lists]'],
            'privacy-center'=>['مركز الخصوصية','[tager_v9_privacy]'],
            'vendor-scorecard'=>['تقييم المورد','[tager_v9_vendor_scorecard]'],
        ];
        foreach($extra as $slug=>$d){$p=get_page_by_path($slug);$pages[$slug]=$p?$p->ID:wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_name'=>$slug,'post_title'=>$d[0],'post_content'=>$d[1]]);} 
        update_option('tager_pages',$pages);
        if(get_option('tager_v9_settings')===false)update_option('tager_v9_settings',['max_login_attempts'=>5,'lock_minutes'=>15,'default_sla_hours'=>48,'enable_pwa'=>1,'enable_api'=>1]);
        update_option('tager_v9_bootstrap',self::V);
    }
    public static function assets(){
        wp_add_inline_style('tager-style','.v9-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.v9-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px}.v9-card h3{margin-top:0}.v9-search{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:10px}.v9-status{display:inline-flex;padding:5px 10px;border-radius:999px;background:#ecfdf5;font-size:12px}.v9-status.open{background:#fff7ed}.v9-status.closed{background:#f3f4f6}.v9-score{font-size:32px;font-weight:800}.v9-progress{height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden}.v9-progress span{display:block;height:100%;background:#0f766e}.v9-reply{border-inline-start:3px solid #d1d5db;padding:10px 14px;margin:10px 0;background:#f8fafc}.v9-install{position:fixed;bottom:18px;right:18px;z-index:9999;display:none}.v9-install button{border:0;border-radius:999px;padding:12px 18px;background:#111827;color:#fff;box-shadow:0 8px 28px rgba(0,0,0,.2)}@media(max-width:900px){.v9-grid,.v9-search{grid-template-columns:1fr 1fr}}@media(max-width:560px){.v9-grid,.v9-search{grid-template-columns:1fr}}');
        wp_add_inline_script('jquery','window.addEventListener("beforeinstallprompt",function(e){e.preventDefault();window.tagerInstallPrompt=e;var b=document.querySelector(".v9-install");if(b)b.style.display="block";});document.addEventListener("click",function(e){if(e.target&&e.target.matches("[data-v9-install]")){window.tagerInstallPrompt&&window.tagerInstallPrompt.prompt();}});if("serviceWorker" in navigator){navigator.serviceWorker.register("'.esc_js(home_url('/?tager-sw=1')).'");}');
    }
    public static function pwa_head(){
        $s=get_option('tager_v9_settings',[]);if(empty($s['enable_pwa']))return;
        echo '<link rel="manifest" href="'.esc_url(home_url('/?tager-manifest=1')).'"><meta name="theme-color" content="#0f766e"><meta name="mobile-web-app-capable" content="yes"><div class="v9-install"><button data-v9-install>'.esc_html(self::t('تثبيت تطبيق تاجر','Install Tager App')).'</button></div>';
    }
    public static function serve_pwa_files(){
        if(isset($_GET['tager-manifest'])){nocache_headers();header('Content-Type: application/manifest+json; charset=utf-8');echo wp_json_encode(['name'=>'Tager Marketplace','short_name'=>'Tager','start_url'=>home_url('/'),'display'=>'standalone','background_color'=>'#ffffff','theme_color'=>'#0f766e','icons'=>[]]);exit;}
        if(isset($_GET['tager-sw'])){nocache_headers();header('Content-Type: application/javascript; charset=utf-8');echo "const C='tager-v9';self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>c.addAll(['".esc_js(home_url('/'))."']))));self.addEventListener('fetch',e=>{if(e.request.method==='GET')e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)))})";exit;}
    }
    public static function admin_menu(){
        add_menu_page('Tager V9','Tager V9','manage_options','tager-v9',[__CLASS__,'dashboard'],'dashicons-chart-area',4);
        add_submenu_page('tager-v9','Disputes','Disputes','manage_options','tager-v9-disputes',[__CLASS__,'disputes_admin']);
        add_submenu_page('tager-v9','Vendor SLA','Vendor SLA','manage_options','tager-v9-sla',[__CLASS__,'sla_admin']);
        add_submenu_page('tager-v9','Security','Security','manage_options','tager-v9-security',[__CLASS__,'security_admin']);
        add_submenu_page('tager-v9','API & PWA','API & PWA','manage_options','tager-v9-settings',[__CLASS__,'settings_admin']);
    }
    public static function dashboard(){
        $orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1]);$sales=0;$open=0;$late=0;foreach($orders as $o){$sales+=(float)get_post_meta($o->ID,'total',true);$st=get_post_meta($o->ID,'order_status',true)?:'pending';if(!in_array($st,['completed','cancelled'],true))$open++;$due=get_post_meta($o->ID,'sla_due',true);if($due&&strtotime($due)<time()&&!in_array($st,['completed','cancelled'],true))$late++;}
        $disputes=get_posts(['post_type'=>'tager_dispute','numberposts'=>-1]);$openDis=0;foreach($disputes as $d)if((get_post_meta($d->ID,'status',true)?:'open')!=='closed')$openDis++;
        $sec=count(get_posts(['post_type'=>'tager_security_log','numberposts'=>-1,'date_query'=>[['after'=>'24 hours ago']]]));
        echo '<div class="wrap"><h1>Tager Enterprise V9</h1><div class="v9-grid"><div class="v9-card">Gross Sales<h2>'.esc_html(self::money($sales)).'</h2></div><div class="v9-card">Open Orders<h2>'.$open.'</h2></div><div class="v9-card">SLA Breaches<h2>'.$late.'</h2></div><div class="v9-card">Open Disputes<h2>'.$openDis.'</h2></div><div class="v9-card">Security Events 24h<h2>'.$sec.'</h2></div><div class="v9-card">PWA<h2>Ready</h2></div><div class="v9-card">REST API<h2>/tager/v1</h2></div><div class="v9-card">Version<h2>9.0.0</h2></div></div><h2>V9 capabilities</h2><p>Installable PWA, advanced catalog search, dispute workflows, vendor SLA scorecards, saved procurement lists, privacy center, login protection, security logs and read-only API endpoints.</p></div>';
    }
    public static function search_page(){
        $q=sanitize_text_field($_GET['q']??'');$min=(float)($_GET['min']??0);$max=(float)($_GET['max']??0);$tier=sanitize_key($_GET['tier']??'retail');$vendor=(int)($_GET['vendor']??0);$sort=sanitize_key($_GET['sort']??'newest');
        $args=['post_type'=>'tager_product','post_status'=>'publish','posts_per_page'=>24,'s'=>$q];if($vendor)$args['author']=$vendor;
        $meta=[];$priceKey=$tier==='bulk'?'bulk_price':($tier==='wholesale'?'wholesale_price':'retail_price');if($min)$meta[]=['key'=>$priceKey,'value'=>$min,'compare'=>'>=','type'=>'NUMERIC'];if($max)$meta[]=['key'=>$priceKey,'value'=>$max,'compare'=>'<=','type'=>'NUMERIC'];if($meta)$args['meta_query']=$meta;
        if($sort==='price_asc'){$args['meta_key']=$priceKey;$args['orderby']='meta_value_num';$args['order']='ASC';}elseif($sort==='price_desc'){$args['meta_key']=$priceKey;$args['orderby']='meta_value_num';$args['order']='DESC';}
        $rows=get_posts($args);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('بحث السوق المتقدم','Advanced Marketplace Search'));?></h1></section><form class="v9-search form-card" method="get"><input name="q" value="<?php echo esc_attr($q);?>" placeholder="<?php echo esc_attr(self::t('ابحث عن منتج','Search products'));?>"><select name="tier"><option value="retail">Retail</option><option value="wholesale" <?php selected($tier,'wholesale');?>>Wholesale</option><option value="bulk" <?php selected($tier,'bulk');?>>Bulk</option></select><input type="number" step="0.01" name="min" value="<?php echo esc_attr($min?:'');?>" placeholder="Min price"><input type="number" step="0.01" name="max" value="<?php echo esc_attr($max?:'');?>" placeholder="Max price"><select name="sort"><option value="newest">Newest</option><option value="price_asc" <?php selected($sort,'price_asc');?>>Price ↑</option><option value="price_desc" <?php selected($sort,'price_desc');?>>Price ↓</option></select><button class="btn primary"><?php echo esc_html(self::t('بحث','Search'));?></button></form><div class="v9-grid"><?php foreach($rows as $p){$price=(float)get_post_meta($p->ID,$priceKey,true);$verified=get_user_meta($p->post_author,'vendor_verified',true);?><article class="v9-card"><span class="v9-status"><?php echo esc_html(ucfirst($tier));?></span><h3><?php echo esc_html($p->post_title);?></h3><p><?php echo esc_html(wp_trim_words($p->post_content,18));?></p><strong><?php echo esc_html(self::money($price));?></strong><p><?php echo esc_html(get_the_author_meta('display_name',$p->post_author));?> <?php echo $verified?'✓':'';?></p></article><?php }?></div><?php if(!$rows)echo '<div class="v9-card">'.esc_html(self::t('لا توجد نتائج','No results found')).'</div>';return ob_get_clean();
    }
    public static function disputes_page(){
        if(!is_user_logged_in())return '<div class="notice">Login required</div>';$uid=get_current_user_id();$rows=get_posts(['post_type'=>'tager_dispute','numberposts'=>100,'meta_query'=>[['key'=>'participants','value'=>'|'.$uid.'|','compare'=>'LIKE']]]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('النزاعات','Disputes'));?></h1></section><form class="form-card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v9_dispute_create"><?php echo self::nonce('tager_v9_dispute_create');?><label>Order ID<input type="number" name="order_id" required></label><label>Reason<select name="reason"><option value="not_received">Not received</option><option value="damaged">Damaged</option><option value="wrong_item">Wrong item</option><option value="payment">Payment</option><option value="other">Other</option></select></label><label>Details<textarea name="details" required></textarea></label><button class="btn primary"><?php echo esc_html(self::t('فتح نزاع','Open dispute'));?></button></form><?php foreach($rows as $d){$st=get_post_meta($d->ID,'status',true)?:'open';?><div class="v9-card"><span class="v9-status <?php echo esc_attr($st);?>"><?php echo esc_html($st);?></span><h3>#<?php echo $d->ID.' '.esc_html($d->post_title);?></h3><p><?php echo esc_html($d->post_content);?></p><?php $replies=get_posts(['post_type'=>'tager_dispute_reply','numberposts'=>100,'meta_key'=>'dispute_id','meta_value'=>$d->ID,'orderby'=>'date','order'=>'ASC']);foreach($replies as $r){?><div class="v9-reply"><b><?php echo esc_html(get_the_author_meta('display_name',$r->post_author));?></b><p><?php echo esc_html($r->post_content);?></p></div><?php }if($st!=='closed'){?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v9_dispute_reply"><input type="hidden" name="dispute_id" value="<?php echo $d->ID;?>"><?php echo self::nonce('tager_v9_dispute_reply_'.$d->ID);?><textarea name="reply" required></textarea><button class="btn">Reply</button></form><?php }?></div><?php }return ob_get_clean();
    }
    public static function dispute_create(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v9_dispute_create');$order=(int)($_POST['order_id']??0);$vendor=(int)get_post_meta($order,'vendor_id',true);$uid=get_current_user_id();$id=wp_insert_post(['post_type'=>'tager_dispute','post_status'=>'publish','post_author'=>$uid,'post_title'=>'Order #'.$order.' - '.sanitize_text_field($_POST['reason']??'other'),'post_content'=>sanitize_textarea_field($_POST['details']??'')]);update_post_meta($id,'order_id',$order);update_post_meta($id,'vendor_id',$vendor);update_post_meta($id,'status','open');update_post_meta($id,'participants','|'.$uid.'|'.$vendor.'|');wp_safe_redirect(self::url('disputes'));exit;}
    public static function dispute_reply(){if(!is_user_logged_in())wp_die('Login required');$id=(int)($_POST['dispute_id']??0);check_admin_referer('tager_v9_dispute_reply_'.$id);$parts=get_post_meta($id,'participants',true);if(!current_user_can('manage_options')&&strpos($parts,'|'.get_current_user_id().'|')===false)wp_die('No access');wp_insert_post(['post_type'=>'tager_dispute_reply','post_status'=>'publish','post_author'=>get_current_user_id(),'post_content'=>sanitize_textarea_field($_POST['reply']??'')]);$rid=get_posts(['post_type'=>'tager_dispute_reply','numberposts'=>1,'orderby'=>'ID','order'=>'DESC'])[0]->ID??0;if($rid)update_post_meta($rid,'dispute_id',$id);wp_safe_redirect(wp_get_referer()?:self::url('disputes'));exit;}
    public static function disputes_admin(){if(!current_user_can('manage_options'))return;$rows=get_posts(['post_type'=>'tager_dispute','numberposts'=>200,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>Marketplace Disputes</h1><table class="widefat striped"><tr><th>#</th><th>Order</th><th>Customer</th><th>Reason</th><th>Status</th><th>Action</th></tr>';foreach($rows as $d){$st=get_post_meta($d->ID,'status',true)?:'open';echo '<tr><td>'.$d->ID.'</td><td>#'.(int)get_post_meta($d->ID,'order_id',true).'</td><td>'.esc_html(get_the_author_meta('display_name',$d->post_author)).'</td><td>'.esc_html($d->post_title).'</td><td>'.esc_html($st).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v9_dispute_status"><input type="hidden" name="dispute_id" value="'.$d->ID.'">'.self::nonce('tager_v9_dispute_status_'.$d->ID).'<select name="status"><option>open</option><option>under_review</option><option>resolved</option><option>closed</option></select> <button class="button">Update</button></form></td></tr>';}echo '</table></div>';}
    public static function dispute_status(){if(!current_user_can('manage_options'))wp_die('No');$id=(int)($_POST['dispute_id']??0);check_admin_referer('tager_v9_dispute_status_'.$id);update_post_meta($id,'status',sanitize_key($_POST['status']??'open'));wp_safe_redirect(admin_url('admin.php?page=tager-v9-disputes'));exit;}
    public static function saved_lists_page(){if(!is_user_logged_in())return '<div class="notice">Login required</div>';$uid=get_current_user_id();$rows=get_posts(['post_type'=>'tager_saved_list','author'=>$uid,'numberposts'=>100]);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('قوائم الشراء المحفوظة','Saved Procurement Lists'));?></h1></section><form class="form-card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v9_saved_list_add"><?php echo self::nonce('tager_v9_saved_list_add');?><label><?php echo esc_html(self::t('اسم القائمة','List name'));?><input name="name" required></label><label><?php echo esc_html(self::t('أرقام المنتجات مفصولة بفواصل','Product IDs separated by commas'));?><input name="products" placeholder="12,15,18"></label><button class="btn primary"><?php echo esc_html(self::t('حفظ القائمة','Save list'));?></button></form><div class="v9-grid"><?php foreach($rows as $r){$ids=array_filter(array_map('intval',explode(',',get_post_meta($r->ID,'product_ids',true))));?><div class="v9-card"><h3><?php echo esc_html($r->post_title);?></h3><p><?php echo count($ids);?> products</p><ul><?php foreach($ids as $pid){$p=get_post($pid);if($p)echo '<li>'.esc_html($p->post_title).'</li>';}?></ul><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v9_saved_list_delete"><input type="hidden" name="list_id" value="<?php echo $r->ID;?>"><?php echo self::nonce('tager_v9_saved_list_delete_'.$r->ID);?><button class="btn">Delete</button></form></div><?php }?></div><?php return ob_get_clean();}
    public static function saved_list_add(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v9_saved_list_add');$id=wp_insert_post(['post_type'=>'tager_saved_list','post_status'=>'publish','post_author'=>get_current_user_id(),'post_title'=>sanitize_text_field($_POST['name']??'List')]);update_post_meta($id,'product_ids',preg_replace('/[^0-9,]/','',$_POST['products']??''));wp_safe_redirect(self::url('saved-lists'));exit;}
    public static function saved_list_delete(){if(!is_user_logged_in())wp_die('Login required');$id=(int)($_POST['list_id']??0);check_admin_referer('tager_v9_saved_list_delete_'.$id);$p=get_post($id);if($p&&((int)$p->post_author===get_current_user_id()||current_user_can('manage_options')))wp_delete_post($id,true);wp_safe_redirect(self::url('saved-lists'));exit;}
    public static function privacy_page(){if(!is_user_logged_in())return '<div class="notice">Login required</div>';ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('مركز الخصوصية','Privacy Center'));?></h1></section><div class="v9-grid"><div class="v9-card"><h3><?php echo esc_html(self::t('تنزيل بياناتي','Download my data'));?></h3><p><?php echo esc_html(self::t('تنزيل ملف JSON يحتوي على بيانات الحساب والطلبات والقوائم.','Download a JSON file containing account, orders and saved lists.'));?></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tager_v9_privacy_export"><?php echo self::nonce('tager_v9_privacy_export');?><button class="btn primary">Export</button></form></div><div class="v9-card"><h3><?php echo esc_html(self::t('طلب حذف الحساب','Request account deletion'));?></h3><p><?php echo esc_html(self::t('سيتم تعطيل الحساب وإرسال الطلب للإدارة للمراجعة.','The account will be disabled and the request sent to admin review.'));?></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" onsubmit="return confirm('Are you sure?')"><input type="hidden" name="action" value="tager_v9_privacy_delete"><?php echo self::nonce('tager_v9_privacy_delete');?><button class="btn">Request deletion</button></form></div></div><?php return ob_get_clean();}
    public static function privacy_export(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v9_privacy_export');$u=wp_get_current_user();$orders=get_posts(['post_type'=>'tager_order','author'=>$u->ID,'numberposts'=>-1]);$lists=get_posts(['post_type'=>'tager_saved_list','author'=>$u->ID,'numberposts'=>-1]);$data=['user'=>['id'=>$u->ID,'name'=>$u->display_name,'email'=>$u->user_email,'registered'=>$u->user_registered],'orders'=>array_map(function($o){return ['id'=>$o->ID,'title'=>$o->post_title,'status'=>get_post_meta($o->ID,'order_status',true),'total'=>get_post_meta($o->ID,'total',true)];},$orders),'saved_lists'=>array_map(function($p){return ['name'=>$p->post_title,'products'=>get_post_meta($p->ID,'product_ids',true)];},$lists)];nocache_headers();header('Content-Type: application/json');header('Content-Disposition: attachment; filename="tager-my-data.json"');echo wp_json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;}
    public static function privacy_delete(){if(!is_user_logged_in())wp_die('Login required');check_admin_referer('tager_v9_privacy_delete');$uid=get_current_user_id();update_user_meta($uid,'deletion_requested',current_time('mysql'));update_user_meta($uid,'account_disabled_pending_review',1);wp_logout();wp_safe_redirect(home_url('/?deletion=requested'));exit;}
    public static function vendor_scorecard(){if(!is_user_logged_in())return '<div class="notice">Login required</div>';$uid=get_current_user_id();$u=wp_get_current_user();$vendor=in_array('tager_vendor',$u->roles,true)?$uid:(int)($_GET['vendor']??0);if(!$vendor)return '<div class="notice">Vendor required</div>';$score=self::vendor_score($vendor);ob_start();?><section class="page-hero"><h1><?php echo esc_html(self::t('بطاقة أداء المورد','Vendor Scorecard'));?></h1></section><div class="v9-grid"><div class="v9-card"><span class="v9-score"><?php echo esc_html($score['overall']);?>%</span><h3>Overall score</h3><div class="v9-progress"><span style="width:<?php echo esc_attr($score['overall']);?>%"></span></div></div><div class="v9-card"><h3>On-time fulfillment</h3><div class="v9-score"><?php echo esc_html($score['ontime']);?>%</div></div><div class="v9-card"><h3>Dispute rate</h3><div class="v9-score"><?php echo esc_html($score['dispute_rate']);?>%</div></div><div class="v9-card"><h3>Completion rate</h3><div class="v9-score"><?php echo esc_html($score['completion']);?>%</div></div></div><?php return ob_get_clean();}
    private static function vendor_score($vendor){$orders=get_posts(['post_type'=>'tager_order','numberposts'=>-1,'meta_key'=>'vendor_id','meta_value'=>$vendor]);$total=count($orders);$completed=0;$ontime=0;foreach($orders as $o){$st=get_post_meta($o->ID,'order_status',true);if($st==='completed')$completed++;$due=get_post_meta($o->ID,'sla_due',true);$done=get_post_meta($o->ID,'completed_at',true);if($st==='completed'&&(!$due||!$done||strtotime($done)<=strtotime($due)))$ontime++;}$dis=count(get_posts(['post_type'=>'tager_dispute','numberposts'=>-1,'meta_key'=>'vendor_id','meta_value'=>$vendor]));$completion=$total?round($completed/$total*100):100;$ot=$completed?round($ontime/$completed*100):100;$dr=$total?round($dis/$total*100):0;$overall=max(0,round($completion*.45+$ot*.45+(100-$dr)*.10));return ['overall'=>$overall,'completion'=>$completion,'ontime'=>$ot,'dispute_rate'=>$dr];}
    public static function sla_admin(){if(!current_user_can('manage_options'))return;$vendors=get_users(['role'=>'tager_vendor']);echo '<div class="wrap"><h1>Vendor SLA Settings</h1><table class="widefat striped"><tr><th>Vendor</th><th>SLA hours</th><th>Verified</th><th>Score</th><th>Save</th></tr>';foreach($vendors as $v){$hours=(int)(get_user_meta($v->ID,'vendor_sla_hours',true)?:48);$score=self::vendor_score($v->ID);echo '<tr><td>'.esc_html($v->display_name).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tager_v9_vendor_sla_save"><input type="hidden" name="vendor" value="'.$v->ID.'">'.self::nonce('tager_v9_vendor_sla_'.$v->ID).'<input type="number" min="1" name="hours" value="'.$hours.'"></td><td><label><input type="checkbox" name="verified" value="1" '.checked(get_user_meta($v->ID,'vendor_verified',true),1,false).'> Verified</label></td><td>'.$score['overall'].'%</td><td><button class="button button-primary">Save</button></form></td></tr>';}echo '</table></div>';}
    public static function vendor_sla_save(){if(!current_user_can('manage_options'))wp_die('No');$v=(int)($_POST['vendor']??0);check_admin_referer('tager_v9_vendor_sla_'.$v);update_user_meta($v,'vendor_sla_hours',max(1,(int)($_POST['hours']??48)));update_user_meta($v,'vendor_verified',empty($_POST['verified'])?0:1);wp_safe_redirect(admin_url('admin.php?page=tager-v9-sla'));exit;}
    public static function generic_login_error(){return 'Login failed. Please check your credentials and try again.';}
    private static function ip(){return sanitize_text_field($_SERVER['REMOTE_ADDR']??'0.0.0.0');}
    public static function rate_limit_login($user,$username,$password){if(empty($username))return $user;$s=get_option('tager_v9_settings',[]);$max=(int)($s['max_login_attempts']??5);$mins=(int)($s['lock_minutes']??15);$key='tager_fail_'.md5(strtolower($username).'|'.self::ip());$data=get_transient($key);if(is_array($data)&&($data['count']??0)>=$max)return new WP_Error('too_many_attempts','Too many login attempts. Try again in '.$mins.' minutes.');return $user;}
    public static function record_failed_login($username){$s=get_option('tager_v9_settings',[]);$mins=(int)($s['lock_minutes']??15);$key='tager_fail_'.md5(strtolower($username).'|'.self::ip());$d=get_transient($key);$count=is_array($d)?(int)$d['count']:0;set_transient($key,['count'=>$count+1],$mins*MINUTE_IN_SECONDS);wp_insert_post(['post_type'=>'tager_security_log','post_status'=>'publish','post_title'=>'Failed login','post_content'=>'User: '.sanitize_text_field($username).' | IP: '.self::ip()]);}
    public static function clear_failed_login($username,$user){delete_transient('tager_fail_'.md5(strtolower($username).'|'.self::ip()));}
    public static function security_admin(){if(!current_user_can('manage_options'))return;$rows=get_posts(['post_type'=>'tager_security_log','numberposts'=>200,'orderby'=>'date','order'=>'DESC']);echo '<div class="wrap"><h1>Security Events</h1><table class="widefat striped"><tr><th>Date</th><th>Event</th><th>Details</th></tr>';foreach($rows as $r)echo '<tr><td>'.esc_html($r->post_date).'</td><td>'.esc_html($r->post_title).'</td><td>'.esc_html($r->post_content).'</td></tr>';echo '</table></div>';}
    public static function settings_admin(){if(!current_user_can('manage_options'))return;$s=get_option('tager_v9_settings',[]);if($_SERVER['REQUEST_METHOD']==='POST'&&check_admin_referer('tager_v9_settings')){$s=['max_login_attempts'=>max(3,(int)($_POST['max_login_attempts']??5)),'lock_minutes'=>max(5,(int)($_POST['lock_minutes']??15)),'default_sla_hours'=>max(1,(int)($_POST['default_sla_hours']??48)),'enable_pwa'=>empty($_POST['enable_pwa'])?0:1,'enable_api'=>empty($_POST['enable_api'])?0:1];update_option('tager_v9_settings',$s);echo '<div class="notice notice-success"><p>Saved.</p></div>';}echo '<div class="wrap"><h1>API, PWA & Security Settings</h1><form method="post">';wp_nonce_field('tager_v9_settings');echo '<table class="form-table"><tr><th>Max login attempts</th><td><input type="number" name="max_login_attempts" value="'.esc_attr($s['max_login_attempts']??5).'"></td></tr><tr><th>Lock duration (minutes)</th><td><input type="number" name="lock_minutes" value="'.esc_attr($s['lock_minutes']??15).'"></td></tr><tr><th>Default vendor SLA hours</th><td><input type="number" name="default_sla_hours" value="'.esc_attr($s['default_sla_hours']??48).'"></td></tr><tr><th>Installable PWA</th><td><label><input type="checkbox" name="enable_pwa" value="1" '.checked(!empty($s['enable_pwa']),true,false).'> Enabled</label></td></tr><tr><th>Read-only API</th><td><label><input type="checkbox" name="enable_api" value="1" '.checked(!empty($s['enable_api']),true,false).'> Enabled</label></td></tr></table><button class="button button-primary">Save Settings</button></form><h2>API endpoints</h2><code>'.esc_html(rest_url('tager/v1/products')).'</code><br><code>'.esc_html(rest_url('tager/v1/vendors')).'</code></div>';}
    public static function rest(){
        register_rest_route('tager/v1','/products',['methods'=>'GET','callback'=>[__CLASS__,'api_products'],'permission_callback'=>'__return_true']);
        register_rest_route('tager/v1','/vendors',['methods'=>'GET','callback'=>[__CLASS__,'api_vendors'],'permission_callback'=>'__return_true']);
        register_rest_route('tager/v1','/orders/(?P<id>\d+)',['methods'=>'GET','callback'=>[__CLASS__,'api_order'],'permission_callback'=>function(){return is_user_logged_in();}]);
    }
    private static function api_enabled(){return !empty((get_option('tager_v9_settings',[]))['enable_api']);}
    public static function api_products($req){if(!self::api_enabled())return new WP_Error('disabled','API disabled',['status'=>403]);$q=sanitize_text_field($req->get_param('q')?:'');$rows=get_posts(['post_type'=>'tager_product','post_status'=>'publish','posts_per_page'=>min(100,max(1,(int)($req->get_param('per_page')?:20))),'s'=>$q]);return array_map(function($p){return ['id'=>$p->ID,'name'=>$p->post_title,'description'=>wp_strip_all_tags($p->post_content),'vendor_id'=>$p->post_author,'retail_price'=>(float)get_post_meta($p->ID,'retail_price',true),'wholesale_price'=>(float)get_post_meta($p->ID,'wholesale_price',true),'bulk_price'=>(float)get_post_meta($p->ID,'bulk_price',true),'stock'=>(int)get_post_meta($p->ID,'stock',true)];},$rows);}
    public static function api_vendors(){if(!self::api_enabled())return new WP_Error('disabled','API disabled',['status'=>403]);return array_map(function($u){$s=self::vendor_score($u->ID);return ['id'=>$u->ID,'name'=>$u->display_name,'verified'=>(bool)get_user_meta($u->ID,'vendor_verified',true),'score'=>$s['overall']];},get_users(['role'=>'tager_vendor']));}
    public static function api_order($req){$id=(int)$req['id'];$o=get_post($id);if(!$o||$o->post_type!=='tager_order')return new WP_Error('not_found','Order not found',['status'=>404]);$uid=get_current_user_id();$vendor=(int)get_post_meta($id,'vendor_id',true);if(!current_user_can('manage_options')&&(int)$o->post_author!==$uid&&$vendor!==$uid)return new WP_Error('forbidden','Forbidden',['status'=>403]);return ['id'=>$id,'title'=>$o->post_title,'status'=>get_post_meta($id,'order_status',true),'total'=>(float)get_post_meta($id,'total',true),'vendor_id'=>$vendor,'created'=>$o->post_date];}
}
Tager_V9_Growth_Security::init();
